### ISSUE TITLE
Supporting C# implementation on Linux

### ISSUE THREAD

**Issue by itn3000** [Microsoft/FASTER#10]
Are there plan for supporting C# implementation on Linux?

**Comment by ronnyek** [comment]
Based solely on just looking at code... it looks like faster.core nuspec already to some degree targets netstandard2.0, which seems like it means it could be consumed from a netcoreapp2 application and possibly run on linux out of box.

**Comment by badrishc** [comment]
Yes, we do plan to add support Linux for the C# implementation. The main missing piece is the file system API (IDevice for storage).

**Comment by itn3000** [comment]
I tried to work FASTER sample app on linux, I found some fixes needed for linux.
I created PR #14.
There is still problems about storage API, but memory-only storage seems to work anyway.

**Comment by badrishc** [comment]
Thanks, this is now pulled into master. As for storage API, we need an implementation of LocalStorageDevice that is .NET core compatible, as maybe even one that optimizes for Linux file system API. This is open (see https://github.com/Microsoft/FASTER/issues/1#issuecomment-421593674)

**Comment by badrishc** [comment]
Updated master with storage support in .NET core, full C# FASTER should now work on Linux.
