### ISSUE TITLE
Read Value with Key Comparison

### ISSUE THREAD

**Issue by vibeeshan025** [Microsoft/FASTER#101]
Is there any way to query the index. Example If the Key is Long. I want to get all the keys in the range of 2000 - 5000.

**Comment by vibeeshan025** [comment]
Can I use **LogScan** for this.

**Comment by badrishc** [comment]
Sure, LogScan will return all key-value pairs in the database, and you can post-filter based on your condition. Note that if you spill to disk, a given key might have more than one version in the log, and logscan will return all versions during the scan.
