### ISSUE TITLE
What is the use of "Context" FASTER

### ISSUE THREAD

**Issue by vibeeshan025** [Microsoft/FASTER#104]
I would like to know what is the real use of "Context". 

The docs says.

> User-defined context for the operation. Use Empty if there is no context necesssary

Currently my assumption Is, that it is for the application developers to send parameters to IFunctions, and read the values inside the IFunctions implementation. IFunctions can use the value to do some fine grained optimization / customization. If my assemption is correct, will it's usage stays same as now forever.

Thanks in advance.

**Comment by badrishc** [comment]
That is correct. Context allows user to send some operation-specific information to the callback (because the operation call stack is not available in the asynchronous callback).
