### ISSUE TITLE
Cannot access a closed Stream when writing byte array

### ISSUE THREAD

**Issue by somecoder2019** [Microsoft/FASTER#105]
I have the below class which is on the lines of the code given in examples to serialize FAsterKV keys. As you can see I am utilizing a utility class to serialize the object to byte array. I verified that that method doesn't throw exceptions. But the writer.Write is throwing exception given below:

```
    public class StoreKeySerializer : BinaryObjectSerializer<StoreKey>
    {
        public override void Serialize(ref StoreKey key)
        {
            writer.Write(FasterUtilities.ObjectToByteArray(key.ConfKey));
        }

        public override void Deserialize(ref StoreKey key)
        {
            key.ConfKey = (Guid)FasterUtilities.ByteArrayToObject(reader.ReadAllBytes());
        }
    }
```

```
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
```

**Comment by badrishc** [comment]
The issue might be with ReadAllBytes. Remember that the method is supposed to deserialize only part of the steam. You cannot extract all bytes from the steam. For variable length objects, you need to write out the number of bytes into the stream so you can read the right number back during deserialization.
