### ISSUE TITLE
How do i add generic values ?

### ISSUE THREAD

**Issue by hariharan618** [Microsoft/FASTER#109]
I am already using to the default Microsoft.Runtime.Caching library. Now we have project dependency on .Net Framework as well as .NET Core. Was searching for a common library and found this. All the examples are either with `long` or custom class values. 

`    public static void Add<T>(T objectToCache, string key, long cacheDuration)
        {
            Cache.Add(key, objectToCache, DateTime.Now.AddMilliseconds(cacheDuration));
        }
`
I tried it like this

`public class Funcs : IFunctions<string, object, dynamic, dynamic, Empty>
    {
    }`

and getting a error stating ` error CS1966: 'Funcs': cannot implement a dynamic interface 'IFunctions<string, object, dynamic, dynamic, Empty>'`

How do i add a `string key` and the value can be anything. 
Any help here would be appreciated.
Thanks for your time and work between,

**Comment by badrishc** [comment]
Looks like dynamic interfaces are not supported in C#. Perhaps what you store could instead be a wrapper (say TypedObject) that contains an `object` and a type, with maybe a getter that returns the dynamic type?

Or, you may just use objects in your interface and cast it based on application-level information: IFunctions<string, object, object, object, Empty>.
