### ISSUE TITLE
Issue with culture != InvariantCulture

### ISSUE THREAD

**Issue by rafael-aero** [Microsoft/FASTER#11]
Hi, 

Just noticed a bug when running the ClassCache C# test in a culture that uses ',' as decimal separator:

Errors during code-gen compilation:
C:\Users\####\AppData\Local\Temp\2\FASTER\gzwgtyln\PersistentMemoryMalloc.cs(91,49): error CS1073: Unexpected token ','

Adding
`System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;
`
fixed the issue, so seems to be a culture issue.

**Comment by mike-barnett** [comment]
Sorry about that! Can you provide me with a repro? What could I set the current thread's culture do which would cause the bug to show up?

**Comment by mike-barnett** [comment]
Thanks @nic-hartley, but I mean I don't even know how to set the culture such that I can see the problem. What should I do to get the test to fail?

**Comment by badrishc** [comment]
This is now fixed, let us know if you run into any more issues.
