### ISSUE TITLE
How do I run samples on macOS

### ISSUE THREAD

**Issue by fenix2222** [Microsoft/FASTER#110]
I can see that both `LocalStorageDevice` and `ManagedStorageDevice` use `Native32` interop and is specific to Windows, does this work with macOS or Linux?

**Comment by badrishc** [comment]
ManagedLocalStorageDevice does not use Native32 if you are in .NET Core. It has been tested to work on Linux. Let me know if you run into issued

**Comment by badrishc** [comment]
Can you provide more details on the error you are encountering in .Net core on Mac? This should be easy to fix once we know where the issue is.

**Comment by fenix2222** [comment]
@badrishc I am going to work on it on Saturday, I will let you know how I go.
