### ISSUE TITLE
Why does a read request have a monotonic serial number?

### ISSUE THREAD

**Issue by matthewbrookes** [Microsoft/FASTER#116]
Hi, I understand for `Upsert` and `RMW` why a monotonic number is used for each operation to fulfill the CPR guarantee "if operation X is persisted, then all operations before X in the input operation sequence are persisted as well (and none after)". What I'm curious about is why it's necessary for a `Read` operation? Does it give some kind of consistency guarantee related to the monotonic number used in the other two operations?

In case it's relevant, I'm referring to the C++ version.

Thanks

**Comment by badrishc** [comment]
Reads are associated with sequence numbers so that we know when and whether the data accessed by the read is persisted or not. Said another way, at a CPR checkpoint boundary, we guarantee that the reads before that point have accessed no data updates after the checkpoint.

**Comment by matthewbrookes** [comment]
Great, thanks for the explanation!
