### ISSUE TITLE
Bug in cs Utility.HashBytes

### ISSUE THREAD

**Issue by Akisoft41** [Microsoft/FASTER#121]
### wrong:
            if ((len & 1) > 0)
            {
                char* pC = (char*)pwString;
                hashState = magicno * hashState + (ulong)*pC;
            }

### correct:
            if ((len & 1) > 0)
            {
                byte* pC = (byte*)pwString;
                hashState = magicno * hashState + (ulong)*pC;
            }

Best regards & many thanks

**Comment by badrishc** [comment]
This method wasn't actually used inside FASTER, but might have been a problem if applications were using it to compute hash codes of unsafe byte chunks. Fixed and merged, thanks!
