### ISSUE TITLE
Is it possible to use read only C++ FASTER in iOS and Android?

### ISSUE THREAD

**Issue by topinvestor** [microsoft/FASTER#124]
Is it possible to use read only C++ FASTER in iOS and Android?

The usage should be read only database - the database 
is generated once and used in read only mode in the 
smartphone.

The scenario is this:
1) generate the FASTER database in OS X
2) add C++ library and generated database in iOS or Android

**Comment by badrishc** [comment]
You can possibly generate the database on the server in OSX, then take a checkpoint. In the Android/iOS client, you can restore that checkpoint and issue your read workload. It should work, but we've never tried it before.
