### ISSUE TITLE
How to store a variable length Key? [C++]

### ISSUE THREAD

**Issue by matthewbrookes** [microsoft/FASTER#127]
Hi,

I am trying to create a key which is able to store an arbitrary length array. I have been trying to apply the same trick as done for [variable-sized values](https://github.com/microsoft/FASTER/wiki/Variable-length-values) where the `jemalloc` allocator leaves enough space at the end of the value for the value to be written to. My issue is I don't know when it is appropriate to write to the buffer in the key class. When does the Key object get instantiated/allocated? After this point and before `key.hash()` is called I should be able to write the array into the buffer, right?

If you have a recommendation for a better way to support a variable length key then I'd be very grateful for some advice.

Thanks.

**Comment by badrishc** [comment]
After allocating space on the log, FASTER will perform a [placement new](http://www.parashift.com/c++-faq-lite/memory-pools.html) to write the key to the location, see https://github.com/microsoft/FASTER/blob/550f0e392cbc26840125b14ee73cfc1af0ffd123/cc/src/core/record.h#L67

That is where you could write the data from the input key buffer into FASTER memory (in the key constructor). Unfortunately, we do not have a test case for it, but if you create one, we might be able to add it to our test suite, and use it as a reference implementation for other users as well.

**Comment by matthewbrookes** [comment]
Thanks for getting back to me on this. That link was really helpful for understanding the allocation stuff. I've managed to implement this and can definitely contribute back a test case to show how I've done it.

**Comment by matthewbrookes** [comment]
Made a PR https://github.com/microsoft/FASTER/pull/128. Let me know what you think :)
