### ISSUE TITLE
Future of FASTER

### ISSUE THREAD

**Issue by forestbat** [microsoft/FASTER#129]
Do you want to improve Faster to make it as powerful as Redis？

**Comment by badrishc** [comment]
The core FASTER library continues to evolve and expand its feature set based on use cases in production (see our recent pull requests and releases for more info). Note that FASTER is not directly comparable to Redis, as FASTER is not just a cache. FASTER can index and access data larger than memory, as well as take consistent checkpoints for recovery, more like a persistent hash key-value store + cache combination. FASTER is multi-threaded and latch-free as well, which gives it very high performance on a single machine.

Some recently completed and ongoing/future work items on our roadmap can be found at https://microsoft.github.io/FASTER/roadmap. 

From a research perspective, we plan to making a distributed elastic version of FASTER available in the next 6 months. We also plan to release a new storage and query layer for flexible-schema data such as JSON and CSV (based on extending FASTER) in the future. You can read more about this storage layer, called _FishStore_, in our new [research paper](https://badrish.net/papers/fishstore-sigmod19.pdf).
