### ISSUE TITLE
Fastest way to duplicate an entire FasterKV object?

### ISSUE THREAD

**Issue by slope-taylor** [microsoft/FASTER#143]
I have a use case where I need to actually duplicate the entire state and spin off another run using that current state snapshot.

Is there a way to quickly do this in memory?  Using the new iterator concept I think I could do something manually, I was just curious if there is another way to do this?

Thanks in advance for any advice.

**Comment by badrishc** [comment]
Adding @peterfreiling

**Comment by peterfreiling** [comment]
I did something similar with checkpoints - take a checkpoint of the source faster instance, copy the checkpoint directory to a new location, create a new faster instance pointing to the new checkpoint directory, then restore the new faster instance from the original checkpoint token.
I used FoldOver checkpoints, which flushes the entire log to disk before taking the checkpoint.

If you can't use checkpoints, your iterator approach should work.
