### ISSUE TITLE
Example implementing Keys and Values as fixed length Strings

### ISSUE THREAD

**Issue by KWLandry** [microsoft/FASTER#146]
Just picking up FASTER as a possible approach to solving a 500 million record lookup in the shortest possible time. 
The Keys would be a fixed 32 character length string and the Values a triplet of 32 character strings each, or simply a fixed length string of 96 characters. In any case, Keys and Values would always be fixed length strings. 
I'd like to ask if someone could work up an example in playground that shows the way to go about implementing this? That is, I've studied the managedsample and managedsample2 examples in playground, as well as the others, and, have an idea, but am not entirely clear on how to go about this with strings, but especially if there are some optimizations that are possible when using fixed length strings. Such as, with fixed length strings can a serializer function be avoided, as well as an objlog?  Am sure this would be helpful for others, so hopefully this would be a great add to the playground.

Thanks for your help,

**Comment by badrishc** [comment]
This is not too difficult to do in FASTER with optimal performance (no serializer or object log) -- just create a struct of the appropriate size, and have methods in it that will re-create the fixed-size string for you when you need it, and perhaps a static method that can return the fixed size struct, given a string as parameter. Use this struct directly with FASTER.

For example, a 32 character string might look like:

struct MyStruct
{
   char char1;
   ...
   char char32;
}

Or to simplify:

struct MyStruct
{
   long long1;
   ...
   long long8;
}

Then you can compute the string on demand with this information.

Yes, an example would be great to add to playground.

**Comment by marius-klimantavicius** [comment]
Gist - https://gist.github.com/marius-klimantavicius/8e4e9bbaf4e4dbad96cfcdb15c7ffb4b
When creating this example I found that `char` is non-blittable type, thus the struct has `byte Data`. Compile with `/unsafe`.

**Comment by KWLandry** [comment]
Excellent,
Thank you,
KWL

**Comment by badrishc** [comment]
Excellent example. This should make its way into playground.
