### ISSUE TITLE
Mixed use of IDevice and direct local file access

### ISSUE THREAD

**Issue by tli2** [microsoft/FASTER#148]
In the checkpointing code (`Checkpoint.cs, FasterKV::GlobalMoveToNextState`), logs are written through the `IDevice` interface by calling `Devices::CreateLogDevice`. However, on the recovery code path (`Contexts.cs, IndexRecoveryInfo::Recover`), the system is hard-coded to use `StreamReader` on the given file path, assuming that the file exists on the local disk.

This results in failure of recovery tests when one naively changes the implementation of `Devices::CreateLogDevice` to supply a non-file based device, but fails to special case checkpointing code. 

The failure to find recovery file also seems to be silent.

**Comment by badrishc** [comment]
Closing as PR has merged.
