### ISSUE TITLE
Memory reorder in Protect, ProtectAndDrain and Unprotect.

### ISSUE THREAD

**Issue by Transpeptidase** [microsoft/FASTER#149]
In function ``Protect``, 

> https://github.com/microsoft/FASTER/blob/master/cc/src/core/light_epoch.h

``` cpp
inline uint64_t Protect() {
    uint32_t entry = Thread::id();
    table_[entry].local_current_epoch = current_epoch.load();
    return table_[entry].local_current_epoch;
  }
```
Because of CPU memory consistency model, the store of  `` table_[entry].local_current_epoch``  may be reordered after some protected code sections. Then, the ``ComputeNewSafeToReclaimEpoch`` function will get the wrong ``safe_to_reclaim_epoch``.

**Comment by tli2** [comment]
Do you have a trace that triggers this problem or did you find it through inspection?

**Comment by Transpeptidase** [comment]
```
-------------- thread T1 ----------------------
| epoch 2   local_current_epoch == kUnprotected
| epoch 2   tmp = current_epoch.load() = 2              
| epoch 2   read shared memory A
| epoch 3   read shared memory A                      --------------> thread T2 Drains
| epoch 3   local_current_epoch = tmp = 2                            
| epoch 3   local_current_epoch = kUnprotected      
| epoch 3                                                                 
```

In the above example,  "local_current_epoch = tmp = 2" can be reordered after reading shared memory.
When thread T2 Drains,  it will calculate ``safe_to_reclaim_epoch`` equal to 2. But epoch 2 is not safe (thread T1 is reading shared memory A)

**Comment by tli2** [comment]
I was more asking if you have a test case or workload you used to reliably reproduce this? That would be helpful in verifying if the bug is fixed.

**Comment by Transpeptidase** [comment]
[test.txt](https://github.com/microsoft/FASTER/files/3355333/test.txt)

This is test source code. 
Run ``g++ -std=c++14 -pthread test.cc thread.cc lss_allocator.cc  -O3`` under directory ``core``.

To make the bug easy to reproduce， insert ``clflush`` in the ``Protect`` (make store of ``local_current_epoch`` easy to be reordered)

``` cpp
 inline uint64_t Protect() {
  
    uint32_t entry = Thread::id();
  
    asm volatile("clflush (%0)" ::"r"(&table_[entry].local_current_epoch));
  
    table_[entry].local_current_epoch = current_epoch.load();
    return table_[entry].local_current_epoch;
  }   

```

**Comment by Transpeptidase** [comment]
[test.txt](https://github.com/microsoft/FASTER/files/3355333/test.txt)

This is test source code. 
Run ``g++ -std=c++14 -pthread test.cc thread.cc lss_allocator.cc  -O3`` under directory ``core``.

To make the bug easy to reproduce， insert ``clflush`` in the ``Protect`` (make store of ``local_current_epoch`` easy to be reordered)

``` cpp
 inline uint64_t Protect() {
  
    uint32_t entry = Thread::id();
  
    asm volatile("clflush (%0)" ::"r"(&table_[entry].local_current_epoch));
  
    table_[entry].local_current_epoch = current_epoch.load();
    return table_[entry].local_current_epoch;
  }   

```
