### ISSUE TITLE
Question on Upserts and storage

### ISSUE THREAD

**Issue by ndgroth** [microsoft/FASTER#159]
Hello,

While playing with the benchmark.cc process, I thought I'd separate the actual upload of the data (setup_store) from the benchmark code (run_benchmark), thus marking 2 binaries out of it. One to handle the upload of data, and the other to done processing. What I noticed is that the setup_store doesn't create any file of the filesystem. So when I run the benchmark part there is no file to open to run the benchmark on. What am I missing? Must those 2 activities be done in the same binary? Isn't all data flushed to disk?

Best regards.

**Comment by badrishc** [comment]
FASTER is based on the concept of a hybrid log, whose tail is in memory, in the mutable region. In the benchmark, the size of the mutable region is larger than the dataset. Hence all the data fits in memory and disk is not accessed.

You can force a flush of data to disk by calling Checkpoint on FASTER. See an example of C++ checkpointing [here](https://github.com/Microsoft/FASTER/tree/master/cc/playground/sum_store-dir) and [here](https://github.com/microsoft/FASTER/blob/master/cc/test/recovery_test.h).

So, in essence, you can run the setup code and take a checkpoint. Then, a different process can recover from the checkpoint and perform the "run" part of the benchmark.
