### ISSUE TITLE
How to read key/value from disk

### ISSUE THREAD

**Issue by marius-klimantavicius** [microsoft/FASTER#166]
Initially my wrapper (using variable length structs) had code similar to this:
```C#
do {
  status = _faster.Read(...);
  if (status == Status.PENDING)
    _faster.CompletePending(true);
} while (status == Status.PENDING);
```

However once I flushed (`FlushAndEvict(true)` and restarted app) I was getting infinite loop as `Read(...)` was always returning Status.PENDING. After investigation I found that `ReadCompletionCallback` is being invoked in this case.

My question - is this the intended way to read value:
```C#
status = _faster.Read(.., ref output);
if (status == Status.PENDING)
{
  _faster.CompletePending(true);
  return RetrieveValueFromReadCompletionCallback(...); // return value from ReadCompletionCallback
}
return output;
```

If status is `PENDING` then (at some point) call `CompletePending(...)` and retrieve/use the value provided in `ReadCompletionCallback`, otherwise (status != `PENDING`) simply return/use `output` value.

**Comment by badrishc** [comment]
Correct, reads can either return PENDING or not. If PENDING, you can call CompletePending, and the system will return the value via the ReadCompletionCallback, which allows you to populate the "output" variable.

If your "output" were a class object, then the write performed into output by the callback would be available in the main thread as well (after CompletePending is over).

**Comment by marius-klimantavicius** [comment]
Got it, thanks.
