### ISSUE TITLE
[C++] Support for log compaction (port from C#)

### ISSUE THREAD

**Issue by badrishc** [microsoft/FASTER#172]
The C# version of FASTER has the ability to compact a portion of the head of the log, copying live records to the tail. We need to port this capability to C++. This is a straightforward enhancement and the design is already flushed out in the C# version. More info can be found in the C# PR https://github.com/microsoft/FASTER/pull/112

Depends on https://github.com/microsoft/FASTER/issues/171

**Comment by chinkulkarni** [comment]
Have assigned this issue to myself. I should be able to issue a PR soon.
