### ISSUE TITLE
[C++] Warning level 4

### ISSUE THREAD

**Issue by wtom76** [microsoft/FASTER#173]
Hi.
Are there plans to refactor C++ part of the project to be conformant with /W4?

**Comment by badrishc** [comment]
No such plans right now. Can you elaborate why this is of interest?

**Comment by wtom76** [comment]
Hi badrishc,
I use /W4 in my code, and if I include FASTER headers, I will receive a bunch of warnings.
Of corse they can be disabled, but to clean FASTER code from level 4 warnings looks like better solution to me.
Thanks

**Comment by badrishc** [comment]
Makes sense. If this is of interest, feel free to submit a PR. Otherwise, this will have to wait until other higher priority work items are competed.

**Comment by wtom76** [comment]
OK =)
