### ISSUE TITLE
Enumerate Keys

### ISSUE THREAD

**Issue by ThiagoT1** [microsoft/FASTER#181]
First of all, thanks a lot for the amazing work done here.

Is there any recommended strategy on how to iterate over all the keys from a given collection?

In absence of that, I'm guessing some Segmented Index must be maintained by the user? 😱 

Thanks!

**Comment by badrishc** [comment]
You can iterate over the log using our log scan interface (https://github.com/microsoft/FASTER/pull/90). This would iterate through all entries in the log. You might see a key more than once if it was subsequently updated on the log (i.e., when you updated the key, it was no longer in the mutable region and therefore had to be copied to tail).

To get exact iterator semantics (read only current value of each key), you need to scan the log from head to tail and build an in-memory hash table (using FASTER) of the latest values of keys. Then you can simply iterate through this in-memory hash table's entries. We do something very similar in our log compaction code here: https://github.com/microsoft/FASTER/blob/f3c3eb000c2a8f43fa0d8a3aee315cc47087550e/cs/src/core/Index/FASTER/LogAccessor.cs#L183

It would be interesting and useful to expose this as a general iterator functionality on FASTER.
