### ISSUE TITLE
Segment size is constrained to power of 2

### ISSUE THREAD

**Issue by tli2** [microsoft/FASTER#182]
In the current implementation each segment in the FASTER log is restricted to have size that is a power of 2. This is presumably for performance.

This is problematic for metadevices as segment sizes of a logical device is inferred from its subcomponents, which are subject to the same constraint. So for a sharded device to work, there can only be power of 2 many shards. 

I don't know if this will be an issue, but it is certainly inconvenient for now.

**Comment by badrishc** [comment]
Segment sizes are a power of two only for performance reasons. It can be relaxed later if necessary.
