### ISSUE TITLE
Is it possible to use FASTER as a Producer/Consumer persistent storage?

### ISSUE THREAD

**Issue by KarenTazayan** [microsoft/FASTER#185]
Hello,

The scenario described below:

1. Application **A**, which works on .NET, generates a lot of lightweight events.
2. It needs temporarily persists them on the local storage and sends events to the Azure Event Hubs.

The **Producer** is a piece of code that generates those events (single thread or multiple threads).
The **Consumer** is a single thread that sends those events via AMQP.

The requirements are the following:

1. Minimize the possibility of losing events during the sending process.
2. At the same time, we should have a high throughput.

Can we achieve it with FASTER? The solution looks like a realtime persistent queue.

Thanks in advance!

**Comment by badrishc** [comment]
We are exposing the write-ahead log functionality of FASTER as a first-class citizen, which sounds exactly like what you need. It can be viewed as a persistent queue. The latest version - not yet merged into master - can be found at this PR: https://github.com/microsoft/FASTER/pull/177

**Comment by KarenTazayan** [comment]
Ok, thank you very much. Looking forward to it.

**Comment by badrishc** [comment]
FasterLog is now generally available in master and in NuGet. Read more about the functionality, including how to use it as a persistent queue, here:

* https://github.com/microsoft/FASTER/blob/master/docs/cs/FasterLog.md
* https://microsoft.github.io/FASTER/docs/fasterlog
