### ISSUE TITLE
[FasterLog] Recovery after truncate fails in debug builds

### ISSUE THREAD

**Issue by hiteshmadan** [microsoft/FASTER#197]
I see an assertion failure in this assert in Recovery.cs RestoreHybridLog() : Debug.Assert(beginAddress <= headAddress);

This happens on any open after a truncate operation is committed to disk.

**Comment by badrishc** [comment]
Is this occurring after the fix we pushed for https://github.com/microsoft/FASTER/issues/191 ?

**Comment by hiteshmadan** [comment]
syncing to latest fixed it.
