### ISSUE TITLE
Update README: The sentence "up to 160 million operations per second"

### ISSUE THREAD

**Issue by maxpert** [Microsoft/FASTER#2]
It would have made more sense to compare it with RocksDB, LevelDB or similar on same environment and configurations. Putting out plain numbers sets no context, just to quote an example, MySQL Cluster has been benched at 200m ops/s (where operations are part of 2PC transactions!). And that in 2015! https://www.mysql.com/why-mysql/benchmarks/mysql-cluster/

**Comment by kierenj** [comment]
That's on 32 data nodes, vs this one CPU I believe?

**Comment by jahunter-m** [comment]
The FASTER paper shows numbers for FASTER, RocksDB, etc. on the same hardware. If the paper isn't already linked from the README, it might be good to link it.

**Comment by maxpert** [comment]
Would be really nice if you can put in a benchmark wiki with table upfront so people don't have to digg in. I went through paper and found the benchmarks.
