### ISSUE TITLE
Can this storage support for Java?

### ISSUE THREAD

**Issue by wenjian1314** [Microsoft/FASTER#21]

**Comment by jahunter-m** [comment]
To support Java, FASTER would need a way to malloc() and pin memory addresses, and work with pointers. (C# FASTER relies on C# "unsafe" support.)

**Comment by badrishc** [comment]
There is no plan to support Java as of now. You could probably write inter-op code to invoke the C++ API, but we don't intend to follow that route. If we have better unsafe and struct value type support in Java, a port may be possible in the future.
