### ISSUE TITLE
`System.Exception` thrown in high load/slow storage scenarios.

### ISSUE THREAD

**Issue by jmrnilsson** [microsoft/FASTER#211]
When load testing FasterLog with AspNetCore 3.0 and [wg/wrk](https://github.com/wg/wrk) I noticed that the pretty generic `System.Exception` was thrown. Because of this exceptions need to be caught with a [when-condition](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/when).

I'd be very helpful if a typed exception was thrown instead. Preferably something FasterLog-specific.

https://github.com/microsoft/FASTER/blob/4d90dac4fd893f15a2f761c4b93ca99515276a30/cs/src/core/Allocator/PendingFlushList.cs#L36

Previously I’ve been working with semaphores for async/await to remedy this. Now I am considering a middleware that throttles writes instead.

*Example*

```bash
mmq-service-kestrel_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
mmq-service-kestrel_1  | fail: Microsoft.AspNetCore.Server.Kestrel[13]
mmq-service-kestrel_1  |       Connection id "0HLRGN4EHAL15", Request id "0HLRGN4EHAL15:00000002": An unhandled exception was thrown by the application.
mmq-service-kestrel_1  | System.Exception: Unable to add item to list
mmq-service-kestrel_1  |    at FASTER.core.PendingFlushList.Add(PageAsyncFlushResult`1 t)
mmq-service-kestrel_1  |    at FASTER.core.AllocatorBase`2.AsyncFlushPages(Int64 fromAddress, Int64 untilAddress)
mmq-service-kestrel_1  |    at FASTER.core.AllocatorBase`2.OnPagesMarkedReadOnly(Int64 newSafeReadOnlyAddress)
mmq-service-kestrel_1  |    at FASTER.core.AllocatorBase`2.<>c__DisplayClass88_0.<ShiftReadOnlyToTail>b__0()
mmq-service-kestrel_1  |    at FASTER.core.LightEpoch.BumpCurrentEpoch(Action onDrain)
mmq-service-kestrel_1  |    at FASTER.core.AllocatorBase`2.ShiftReadOnlyToTail(Int64& tailAddress)
mmq-service-kestrel_1  |    at FASTER.core.FasterLog.CommitInternal(Boolean spinWait)
mmq-service-kestrel_1  |    at FASTER.core.FasterLog.CommitAsync(CancellationToken token)
mmq-service-kestrel_1  |    at Service_Kestrel.FasterWriter.CommitAsync(CancellationToken token) in /src/Faster/FasterWriter.cs:line 26
mmq-service-kestrel_1  |    at Service_Kestrel.RequestHandlers.FasterHttpHandler.HandleRequest(HttpContext context) in /src/RequestHandlers/FasterHandler.cs:line 27
mmq-service-kestrel_1  |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
mmq-service-kestrel_1  |    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
mmq-service-kestrel_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 applicat
```

**Comment by badrishc** [comment]
Makes sense, we will fix this in the next release. Thanks for the report.

**Comment by badrishc** [comment]
This exception means you have more than 8 pending page flushes, which seems unnecessary. Generally, if you issue the next commit after the previous one finishes, your should not run into this problem. It's usually better to wait and issue a larger flush than issue many small flushes that all go pending.

**Comment by jmrnilsson** [comment]
Yes, you're absolutely right. This was back when I was trying different techniques for committing. I was probably bombarding the FASTER with commits at that point.

**Comment by badrishc** [comment]
Would love to hear the results of your experimentation, and if there are ways we can help.

**Comment by jmrnilsson** [comment]
Sure I’ll try to keep you posted on any general findings. As of yet I don’t have a lot of details, I’m still getting to know the API.

I’m getting about 30-50% (70-90 MB/s) saturation of my particular brand of SATA SSD when posting documents over HTTP. Which feels pretty good at this point in time. I believe this is limited by the benchmarking tool I put together, or possibly by using HTTP on top FASTER. This amounts to about 9 000 documents/s. I also have benchmarked with [wrk](https://github.com/wg/wrk) in Docker and can reach some 25 000 documents/s. But I’m sure to what extent I can trust the results from sending the same document over and over.
