### ISSUE TITLE
[C#]: "Unable to add item to list" exception in FasterLog

### ISSUE THREAD

**Issue by Utilisator** [microsoft/FASTER#229]
Is it possible to Write (TryEnqueue) in FasterLog and periodically read from same FasterLog and truncateuntil simultaneously?
I get "Unable to add item to list" exception during this process

**Comment by badrishc** [comment]
Yes, it is expected to perform write, read, truncate simultaneously. Can you check if this issue helps solve the problem: https://github.com/microsoft/FASTER/issues/211? If not, a repro would help us diagnose.

**Comment by badrishc** [comment]
Any update on this? Thanks!

**Comment by Utilisator** [comment]
The problem depends on Nlog sync logging via FASTER. Now I'm testing async version of NLog logging with faster and trying to reproduce this error. I'll update next week.

**Comment by Utilisator** [comment]
Now it works fine, thanks
