### ISSUE TITLE
[C++] Support io_uring for Linux IO

### ISSUE THREAD

**Issue by badrishc** [microsoft/FASTER#231]
In the current version of FASTER C++, on Linux, we use `libaio` for async IO handling. It is a known issue that `libaio` is not very efficient. Recently, `io_uring` is released with Linux kernel 5.1, which advertises to be a high performance aysnc IO library. It would be useful to try it and see if we can improve disk performance on Linux by replacing `libaio` with it.

More details for io_uring can be found here: http://kernel.dk/io_uring.pdf

**Comment by dongx-psu** [comment]
I think I got some time recently on this. Will try get a version out this month.
