### ISSUE TITLE
[C#] Recover Fails For Updated Data (FoldOIver CheckPoint Only)

### ISSUE THREAD

**Issue by ThiagoT1** [microsoft/FASTER#235]
Hello, there!

Out of 80 tests, only a specific scenario is failing, only when using FoldOver checkpoints.

Repo:
https://github.com/ThiagoT1/FasterDictionary/blob/afaf01e564c0609e327139848d93b5e3d1cd1b90/tests/FasterDictionary.Tests/Recover/RecoverTests.cs#L193

The failing tests do this:

- Upsert N entries
- Take a full checkPoint
- Recover
- Upsert the same N entries to a different value
- Take a full checkpoint
- Recover (FAILS HERE!)
- Read 100 entries

Code:

```csharp
        
public async Task AddUpdateGet(int loops, CheckpointType checkpointType)
{
	var options = GetOptions($"{nameof(AddIterateUpdateIterate)}-{loops}");

	options.CheckPointType = checkpointType;
	options.DeleteOnClose = false;

	FasterDictionary<int, string>.ReadResult result;
	using (var dictionary = new FasterDictionary<int, string>(TestHelper.GetKeyComparer<int>(), options))
	{
		for (var i = 0; i < loops; i++)
			dictionary.Upsert(i, (i + 1).ToString()).Dismiss();


		await dictionary.Save();
	}


	using (var dictionary = new FasterDictionary<int, string>(TestHelper.GetKeyComparer<int>(), options))
	{
		for (var i = 0; i < loops; i++)
			dictionary.Upsert(i, (i + 2).ToString()).Dismiss();


		await dictionary.Save();
	}

	options.DeleteOnClose = true;

	//FAILS HERE
	using (var dictionary = new FasterDictionary<int, string>(TestHelper.GetKeyComparer<int>(), options))
	{
		for (var i = 0; i < 100; i++)
		{
			var guid = GetGuid(i);
			result = await dictionary.TryGet(i);
			Assert.True(result.Found);
			Assert.Equal((result.Key + 2).ToString(), result.Value);
		}

		result = await dictionary.TryGet(loops);
		Assert.False(result.Found);

	}
}
```

Failed Tests ScreenShot
![image](https://user-images.githubusercontent.com/16569217/72614864-17d12b00-3912-11ea-88b0-d201f25af72d.png)

Could you please take a look?

**Comment by badrishc** [comment]
Is there a branch you can point to, with the repro?

**Comment by ThiagoT1** [comment]
Sorry.

https://github.com/ThiagoT1/FasterDictionary/tree/switch-to-system.text.json?files=1

**Comment by badrishc** [comment]
Problem located - fix coming up shortly.

**Comment by badrishc** [comment]
Fix is now in master, pls verify.

**Comment by badrishc** [comment]
Btw, a PR to port some of these more comprehensive objlog tests to FASTER would also be useful to ensure no regressions in future.

**Comment by ThiagoT1** [comment]
Thanks a lot! 

About the Tests PR, I'll sure look into it. 
Must it exclude the wrapper class (FasterDictionary<,>)? 
Maybe I could extend FasterDictionary<,> to accept serialization code and make it more flexible. Right now its coupled to JSON.

**Comment by badrishc** [comment]
Is this close enough to what you are doing, to extend with tests that check your corner cases:

https://github.com/microsoft/FASTER/blob/master/cs/test/ObjectRecoveryTest2.cs

**Comment by ThiagoT1** [comment]
The fix worked! 80 tests passing!

taking a look at https://github.com/microsoft/FASTER/blob/master/cs/test/ObjectRecoveryTest2.cs
