### ISSUE TITLE
[C#] When Recover Fails, Process Crashes

### ISSUE THREAD

**Issue by ThiagoT1** [microsoft/FASTER#236]
This is related to https://github.com/microsoft/FASTER/issues/235.

When recover fails, usually the serializer will be activated with a bad data stream.
The actual call stack of deserialization will cause an unhandled exception to bubble up and kill the process.
A possible workaround would be to catch the exception on the site. But then it would not be pretty the wire the explosion back to business code.
Also, a corrupted data stream is a show stopper anyway.

## Call Stack Root:
 	System.Private.CoreLib.dll!System.Threading._IOCompletionCallback.PerformIOCompletionCallback(uint errorCode, uint numBytes, System.Threading.NativeOverlapped* pNativeOverlapped)	Unknown

![image](https://user-images.githubusercontent.com/16569217/72616005-bc546c80-3914-11ea-8340-7f01f3906718.png)

## Process Crash

> The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.Text.Json.JsonException: The input does not contain any JSON tokens. 
> [REMOVED FOR CONCISION]
>    at FasterDictionary.FasterDictionary`2.BaseSerializer`2.Deserialize(TContent& obj) in C:\Codigo\FasterDictionary\FasterDictionary\src\FasterDictionary\FasterDictionary.Serializers.cs:line 88
>    at FasterDictionary.FasterDictionary`2.ValueSerializer.Deserialize(ValueEnvelope& obj) in C:\Codigo\FasterDictionary\FasterDictionary\src\FasterDictionary\FasterDictionary.Serializers.cs:line 41
>    at FASTER.core.GenericAllocator`2.Deserialize(Byte* raw, Int64 ptr, Int64 untilptr, Record`2[] src, Stream stream)
>    at FASTER.core.GenericAllocator`2.AsyncReadPageWithObjectsCallback[TContext](UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlap)
>    at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pNativeOverlapped)

## Proposal

There should be a way to communicate a bad stream back to the Recover call site.
Could we have a context (maybe as a parameter to serializer methods), so we can signal any problems?
I'd gladly detail and prepare a PR.

**Comment by badrishc** [comment]
Couldn't you add your own context to the serializer?

**Comment by ThiagoT1** [comment]
I could, but then I would have to wrap the Recover call to make the failure observable.
Also, I would have no way to tell FASTER to abort the deserialization step, and no control over the overall state of of KV, maybe even with the chance that the Recover call never completes.

Does that make sense?

**Comment by badrishc** [comment]
I think so. Perhaps you can create a proposal PR for this and we can review?

**Comment by ThiagoT1** [comment]
Just to report, I'll have some news on that PR by the weekend.

**Comment by badrishc** [comment]
Do you still have this on plan? If not, we should close as we won't be fixing it since with after the bug-fixes it appears we will not need this.

**Comment by ThiagoT1** [comment]
Yes.
This still happens.
Could we take a look at #246 first?

**Comment by badrishc** [comment]
Closing as it's not impacting anyone at this point. Let's reopen if we have a PR to address the situation.
