### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by blunney1** [Microsoft/FASTER#24]
The repo is missing the traditional LICENSE file that explicitly states license terms for the source code.  I note there are comments in the source code referencing the MIT license.  Please add a LICENSE file that makes the terms explicit.  A sample MIT license file can be found at 

https://opensource.org/licenses/MIT.

**Comment by badrishc** [comment]
Are you referring to something other than what we already have at https://github.com/Microsoft/FASTER/blob/master/LICENSE
