### ISSUE TITLE
Use byte array as key

### ISSUE THREAD

**Issue by Phylum123** [microsoft/FASTER#243]
Hi, I am trying to use a blittable, variable length byte array as a key and value for a FasterKV database. I looked at you fixedlenstruct as an a example because you take a string, set a pointer to a byte and then fill an array of charts, that the byte points to (this is my rough interpretation that may be quite wrong). I haven't used pointers and variables addresses, since school (which was LONG ago), so I dont fully understand what is going on, but I took a crack at it and got many errors. If you could set me on the path, that would be great. Thanks

**Comment by ThiagoT1** [comment]
This code does pretty much that, abeilt converting anthing to json, and the json string to a byte array:

https://github.com/ThiagoT1/FasterDictionary/tree/unsafe-0.0.3-fastread
https://github.com/ThiagoT1/FasterDictionary/blob/unsafe-0.0.3-fastread/src/FasterDictionary/FasterDictionary.Types.cs

Please note that currently async methods won't support this strategy.

This could be fixed by PR https://github.com/microsoft/FASTER/pull/242

**Comment by Phylum123** [comment]
Thank you for your  code. It looks really good. I guess what I was more looking at was this, an kinda an explanation about how it works:

The code is below the questions:

1. The struct in the code is blittable (though fixed length), with a single byte. I assume this byte somehow points to the string passed into the constructor?
2. In the constructor you can see how they do a pointer to a pointer (i think ) and fill it with the passed in string as an array of chars. How does this byte retain its pointer to this string? After the "fixed" statement is over can't the garbage collector move the memory?
3. The GetHashCode64 method seems to just reference the memory at the address of where they magically placed the array of characters and it produces a hash code. 

I guess these are the parts that aren't clear to me. I would love to do the same thing, but with a byte array. Have a Key type that has a single byte that points to a  byte array, so that it is blittable and variable in length (any sized byte array works). I know this is just me lacking the c/c++ pointer knowledge, but looking this stuff up didn't clear up everything.
 
`    /// <summary>
    /// Represents a fixed length struct type (Length = 32)
    /// </summary>
    [StructLayout(LayoutKind.Explicit, Size = _maxLength)]
    public unsafe struct FixedLenKey : IFasterEqualityComparer<FixedLenKey>
    {
        private const int _maxLength = 32;

        [FieldOffset(0)]
        private byte data;

        public FixedLenKey(string v)
        {
            if (_maxLength < 2 * (v.Length + 1))
                throw new Exception("Insufficient space to store string");

            fixed (byte* ptr = &data)
            {
                var data = (char*)ptr;
                for (var i = 0; i < _maxLength / sizeof(char); i++)
                {
                    if (i < v.Length)
                        *(data + i) = v[i];
                    else
                        *(data + i) = '\0';
                }
            }
        }

        public void CopyTo(ref FixedLenKey dst)
        {
            fixed (byte* source = &data, destination = &dst.data)
                Buffer.MemoryCopy(source, destination, _maxLength, _maxLength);
        }

        public bool Equals(ref FixedLenKey k1, ref FixedLenKey k2)
        {
            fixed (byte* pk1 = &k1.data, pk2 = &k2.data)
            {
                for (var i = 0; i < _maxLength; i++)
                {
                    var left = *(pk1 + i);
                    var right = *(pk2 + i);
                    if (left != right)
                        return false;
                }
            }

            return true;
        }

        public long GetHashCode64(ref FixedLenKey k)
        {
            fixed (byte* data = &k.data)
                return Utility.HashBytes(data, _maxLength);
        }

        public override string ToString()
        {
            fixed (byte* ptr = &data)
                return new string((char*)ptr);
        }
    }
`

**Comment by ThiagoT1** [comment]
Trying to help a bit. First of all, take a loot at this comment from Mr. Badrish when I asked something similar:

> **Q:** It seems like the unsafe struct VarLenType uses a hack strategy to collaboratively (with FASTER) trick the struct to a blittable type.
> Is that assessment correct?
> **A:** C# does not support variable-length value types. What we do with variable length structs is an unsafe typecast of raw memory into the struct type in order to access its methods in a type-aware manner, instead of just falling back to raw bytes. It's compliant with C#, but yes it's a workaround. If you don't want to go down that route, the C# compliant way to support variable length is to use generic class objects (but at higher overhead). (...)

https://gitter.im/Microsoft/FASTER?at=5dc58e63ca778c1fbfc8de05


Now to your questions:
**Q**: The struct in the code is blittable (though fixed length), with a single byte. I assume this byte somehow points to the string passed into the constructor?
**A:** The trick here is to *fool* the runtime into passing around a struct (only works by ref) that actually points to more bytes (or less) than its explicitly declared members would require. By converting a byte array to a pointer and casting it to the blittable struct type, you can pretend to have type-awareness, as Badrish's answer ilustrate. 


**Q:** In the constructor you can see how they do a pointer to a pointer (i think ) and fill it with the passed in string as an array of chars. How does this byte retain its pointer to this string? After the "fixed" statement is over can't the garbage collector move the memory?
**A:** You should not try to do that in the constructor, and instead rely on the ```ToByteArray``` and ```CopyTo``` methods to store and retrieve the actual bytes you're passing around (always by ref!).
In this sense, having a single ```int Size``` field at position 0 will help you know how many bytes to read thru.
Actually, FASTER will ```new()``` your struct every time it needs one, and them call you Functions class so you can convert the array to the struct, and vice versa. 

https://github.com/microsoft/FASTER/blob/8f14cf4401677d3cd6297f927bf2f90e64b04236/cs/test/VLTestTypes.cs#L143-L166

Thats why you use the array type as the FasterKV's Outupt generic parameter.

https://github.com/microsoft/FASTER/blob/8f14cf4401677d3cd6297f927bf2f90e64b04236/cs/test/VLTestTypes.cs#L113

As to the GC, my understanding is that it won't corrupt the type casted struct, as long as you hold a reference to the array that backs it, specially if you stackalloc'ed the array.
**Anyway, I would be happy to be pointed to some hard guarantee on that.** 

**Q**: The GetHashCode64 method seems to just reference the memory at the address of where they magically placed the array of characters and it produces a hash code.
**A:** This functions just iterates thru the length of the infected :space_invader: struct, to try and produce a distributed enough hash code, so the equals function has to run less often.



Hope it helps!

**Comment by Phylum123** [comment]
Thank you so much for your help. I think I have made a working model of what I was going for. I have ran some simple tests and it seems to work. This allows you to use a variable length byte array as a key or value in faster. So if you were to use this as your key and value; your key and value are of this type (currently called TestByteArrayType) and your input and output would be byte[].

`    [StructLayout(LayoutKind.Explicit)]
    public unsafe struct TestByteArrayType : IFasterEqualityComparer<TestByteArrayType>, IVariableLengthStruct<TestByteArrayType>
    {
        [FieldOffset(0)]
        public int ArrayLength;

        [FieldOffset(4)]
        public byte Data;

        public TestByteArrayType(byte[] bArray)
        {
            ArrayLength = bArray.Length;

            fixed (byte* ptr = &Data)
            {
                var data = (byte*)ptr;
                for (var i = 0; i < ArrayLength; i++)
                {
                    *(data + i) = bArray[i];
                }
            }
        }

        public void ToByteArray(ref byte[] dst)
        {
            dst = new byte[ArrayLength];
            byte* src = (byte*)Unsafe.AsPointer(ref this);
            src += sizeof(int);
            for (int i = 0; i < ArrayLength; i++)
            {
                dst[i] = *src;
                src++;
            }
        }

        public void CopyTo(ref TestByteArrayType dst)
        {
            var fulllength = sizeof(int) + ArrayLength * sizeof(byte);

            Buffer.MemoryCopy(Unsafe.AsPointer(ref this),
                Unsafe.AsPointer(ref dst), fulllength, fulllength);
        }

        public bool Equals(ref TestByteArrayType k1, ref TestByteArrayType k2)
        {
            fixed (byte* pk1 = &k1.Data, pk2 = &k2.Data)
            {
                for (var i = 0; i < ArrayLength; i++)
                {
                    var left = *(pk1 + i);
                    var right = *(pk2 + i);
                    if (left != right)
                        return false;
                }
            }

            return true;
        }

        public long GetHashCode64(ref TestByteArrayType k)
        {
            fixed (byte* data = &k.Data)
                return Utility.HashBytes(data, ArrayLength);
        }

        public int GetAverageLength()
        {
            return 64 * sizeof(byte);
        }

        public int GetInitialLength<Input>(ref Input input)
        {
            return 64 * sizeof(byte);
        }

        public int GetLength(ref TestByteArrayType t)
        {
            return ArrayLength * sizeof(byte);
        }

        public override string ToString()
        {
            fixed (byte* ptr = &Data)
                return new string((char*)ptr);
        }
    }
`
