### ISSUE TITLE
[C#] Continuations Should be Properly Wired

### ISSUE THREAD

**Issue by ThiagoT1** [microsoft/FASTER#246]
Currently, ```ReadAsync``` continuations will try to complete  every pending read.
This leads to unnecessary race conditions  on the ```FasterExecutionContext```members.

https://github.com/microsoft/FASTER/blob/bd5ad88df06e881559f56fd2b3c085e12f3229bf/cs/src/core/Index/FASTER/FASTERThread.cs#L258-L262

I sense this is like this since KVSession is not (should it be?) thread safe, maybe still in a gray area between the older thread affinity from FasterKV and the WIP adoption of TPL.
However, when using the async methods, there's nothing preventing multi-threaded continuations (and that is the correct way to go).

Actually, here's everything we need to know exactly what request is completed:
https://github.com/microsoft/FASTER/blob/bd5ad88df06e881559f56fd2b3c085e12f3229bf/cs/src/core/Allocator/AllocatorBase.cs#L1449

Could we refactor some code,  so async continuations get properly wired and only complete the corresponding read request, rather than competing for shared state?

**Comment by badrishc** [comment]
A given session is expected to be single concurrency (similar to Orleans grains), as it creates a sequence of operations with IDs. For the purpose of recovery, we need prefixes to commit such that all operations before a prefix have committed and none after. As long as these requirements are met, it should be fine for individual reads to commit.

If you need concurrency then you would use multiple sessions.

**Comment by ThiagoT1** [comment]
I agree and think that is ok.

A  few points to consider, though, as to why this needs some work:

---

1) Even if KVSession should not be concurrent, there should not be anything preventing async continuations. Currently, this code does:

https://github.com/microsoft/FASTER/blob/bd5ad88df06e881559f56fd2b3c085e12f3229bf/cs/src/core/Index/FASTER/FASTERThread.cs#L512-L516

This code breaks whenever we call ```ClientSession<>.ReadAsync``` multiple times, without awaiting it right away (batching completions to make disk reads FASTER, as a way to work around https://github.com/microsoft/FASTER/issues/238.

On read continuations, why would we need the ```readSerialNo```, given the ```request.id``` is making sure we are completing the right request?

---


2) Callbacks on the Functions class could migrate to the Context class, that if derived from an interface, could be used to fulfill https://github.com/microsoft/FASTER/issues/230.

If that makes sense, could we have a PR that goes that direction?

If we could, how much are we willing to break the API? Could we have nested IFunctions and (future) IContext interfaces nested to FasterKV<,,,>, since the Generic Parameters have to be the same?

It would make code a lot simpler to undestand (see [Dictionary<TKey, TValue>.KeyCollection](https://github.com/microsoft/referencesource/blob/a7bd3242bd7732dec4aebb21fbc0f6de61c2545e/mscorlib/system/collections/generic/dictionary.cs#L801))

**Comment by ThiagoT1** [comment]
Plus,
If this code executes, the readAsync completion will be lost (returns default), right?

https://github.com/microsoft/FASTER/blob/bd5ad88df06e881559f56fd2b3c085e12f3229bf/cs/src/core/ClientSession/FASTERAsync.cs#L85-L99

Also, 

Any scheduled ReadAsync continuations will make this explode, eventually (the ```Debug.Assert``` is already failing while, well, debugging):

https://github.com/microsoft/FASTER/blob/bd5ad88df06e881559f56fd2b3c085e12f3229bf/cs/src/core/ClientSession/FASTERAsync.cs#L107-L115

**Comment by badrishc** [comment]
Will take a look at this the coming week, thx.

**Comment by badrishc** [comment]
I took a brief look at the associated PR. The changes have some subtle implications on recovery. The current system is carefully designed to handle concurrent checkpointing operations, so some code paths that do not normally trigger might occur if there are concurrent calls to FASTER while checkpointing is being done.

The best way to move forward might be to provide us with simple example snippets of what use case is currently not working (or nor working efficiently) using the current API and we can look into a fundamental solution that does not interfere with concurrent recovery.

Note also that a FASTER client session is expected to be mono-threaded. In other words, only one thread may be operating on a session at a given time instant. You can issue multiple async operations without await, that is okay. You can efficiently "group complete" all the pending async operations on a session by calling CompletePendingAsync.

**Comment by badrishc** [comment]
A given FASTER client session consists of an ordered sequence of operations with assigned serial numbers per operation. When we checkpoint, we guarantee that some deterministic prefix, in serialNumber space, of these operations (non-pending) are fully persisted, and none after. This implies no non-determinism within a session.

If you want full async support with parallel continuations, and you do not care about the above prefix recovery guarantees, you can simply create a pool of sessions. Individual calls can "rent" out a session (e.g., from a thread-local pool) to perform an operation and then return the session to the pool when done. This ensures mono-threaded operation within each client session while providing a fully general async experience.

See these threads for our thinking and ideas in this space before arriving at the solution currently used in FASTER:
* https://github.com/microsoft/FASTER/issues/140
* https://github.com/microsoft/FASTER/pull/130

**Comment by ThiagoT1** [comment]
Thanks for the time!

I'll try to answer why current code is not OK for the async API.

As stated on the above comments, the only way the current async API (for Read) works is if you issue a ReadAsync call and **await it before making the next one**. This will work because the continuation will be single-thread(edly) execute, and find the same ```pendingContext.serialNum```, thus eventually setting the (Status, Output) correctly.

> You can efficiently "group complete" all the pending async operations on a session by calling CompletePendingAsync.

With current code you can't, since ```pendingContext.serialNum``` will change under the continuations and make a lot (or all) of them fail.

https://github.com/microsoft/FASTER/blob/bd5ad88df06e881559f56fd2b3c085e12f3229bf/cs/src/core/Index/FASTER/FASTERThread.cs#L512-L516

> Related, how are you ending up with multi-threaded continuations when a client session is only used by one logical session.

You just need to issue another ReadAsync call before waiting for the last one, which is what the below code does:

```csharp
var tasks = new List<ValueTask<FasterDictionary<string[], string>.ReadResult>>(loops);

for (var i = 0; i < loops; i += step)
{
	tasks.Add(dictionary.TryGet(keys[i]));
}

for (var i = 0; i < loops; i += step)
{
	result = await tasks[i];
	Assert.True(result.Found);
	Assert.Equal((i + 10).ToString(), result.Value);
}
```
https://github.com/ThiagoT1/FasterDictionary/blob/7a160be9390e6e82e41f5439747ef520d261bf80/tests/FasterDictionary.Tests/UseCases/ArrayAsKeyTests.cs#L138

BTW, this branch works OK with the patched (PR) code, while failing with the current one.

While making the PR, I was very careful to look at every execution path I was affecting.

Could you please elaborate on what's the impact for recoveries? Maybe I could adhere to the "old" behavior, while moving the code forward.

If the need is to control how many reads are pending at any given moment, that could easily be patched to the PR.

Also, this change is very important if we we want to achieve some very nice goals:

- Get rid of periodic calls like ```CompletePending``` and ``` CompleteRetryRequests```
- Ensuse every continuation started by (say) an IO only completes **its** pending state, avoiding shared state with other continuations while improving performance and predictability
- Rewire Request Retries to be done when a latch is released, instead of when someone remembers to call some other method.

Thanks a lot!

**Comment by ThiagoT1** [comment]
> 
> 
> A given FASTER client session consists of an ordered sequence of operations with assigned serial numbers per operation. When we checkpoint, we guarantee that some deterministic prefix, in serialNumber space, of these operations (non-pending) are fully persisted, and none after. This implies no non-determinism within a session.

I get this for write operations. Do Read calls affect this?

> 
> If you want full async support with parallel continuations, and you do not care about the above prefix recovery guarantees, you can simply create a pool of sessions. Individual calls can "rent" out a session (e.g., from a thread-local pool) to perform an operation and then return the session to the pool when done. This ensures mono-threaded operation within each client session while providing a fully general async experience.

This would be at the unlimited cost of creating a session per concurrent call to Read, or saying **NO!** when said pool is out of capacity. Thread pool AsyncState machinery should handle that instead, no?


> See these threads for our thinking and ideas in this space before arriving at the solution currently used in FASTER:
> 
>     * #140
> 
>     * #130

If the continuation state control was to be handled by .NET / Operating System (as it should, right?), then the only control necessary would be what continuations are pending, so Check Points could behave as expected.

```FasterExecutionContext```'s role should be constrained to keep track of pending continuations, if this is needed. Not provide state control for them to be carried out.

**Comment by badrishc** [comment]
> I get this for write operations. Do Read calls affect this?

Serial numbers are assigned to writes and reads equally. A Read might read unpersisted data from main memory, later after checkpoint we know that the read becomes "guaranteed" in that the read was for data that is now committed.

**Comment by ThiagoT1** [comment]
I sense that was expressed in the ```waitForCommit```  parameter. If this is correct, its execution path is unchanged, along with its state control.
We are even incrementing ```clientSession.ctx.serialNum``` by 1, as the original code did that implicitly.

**Comment by badrishc** [comment]
I think its fine to "bugfix" in order to make sure that the following min-repro works correctly:
```cs
var t1 = s.ReadAsync();
var t2 = s.ReadAsync();
await t1; await t2;
```

This is fine because there is no parallelism of continuations in the above. However, if we allowed parallel continuations, then strict mono-threadedness per session would be violated. E.g., this code is NOT okay because of potentially parallel invocation of reads for 3 and 2:

```cs
var t1 = s.ReadAsync(1).ContinueWith(() => { s.ReadAsync(3); });
var t2 = s.ReadAsync(2);
await t1; await t2;
```

**Comment by ThiagoT1** [comment]
> 
> This is fine because there is no parallelism of continuations in the above.

This would be true as long as the external call to ```Native.ReadFile``` executes callbacks in a synchronous (and FIFO) manner. Not sure that's the case. Even less sure when dealing with different file handles 😨 

> However, if we allowed parallel continuations, then strict mono-threadedness per session would be violated.
> 
This is true.

However, we could craft state control as to allow for multi threaded (and out of order) continuations, as long as the ReadAsync call itself was done in a mono threaded manner.

BTW, that's what ther PR does *now*. And we have some numbers:

## Tests:

---

### 1 Batched

As such, this test takes 9 mins (1M items):

https://github.com/ThiagoT1/FasterDictionary/blob/f66f78deb21b61d7e1659902bd47245fc3973d87/tests/FasterDictionary.Tests/UseCases/ArrayAsKeyTests.cs#L136-L153

![image](https://user-images.githubusercontent.com/16569217/75206838-0b808f00-5756-11ea-8f71-70ca379300b7.png)

![image](https://user-images.githubusercontent.com/16569217/75206852-12a79d00-5756-11ea-9dc4-04be3ce72a63.png)

---

### 2 Sync await

And this one takes 19 mins (1M items):

https://github.com/ThiagoT1/FasterDictionary/blob/01f99ac727add71b417fdaeeb4436c74a3a6ad89/tests/FasterDictionary.Tests/UseCases/ArrayAsKeyTests.cs#L138-L144

![image](https://user-images.githubusercontent.com/16569217/75206865-19361480-5756-11ea-998b-9125115d543c.png)

![image](https://user-images.githubusercontent.com/16569217/75206871-1dfac880-5756-11ea-93bd-454df56299ca.png)

---

BTW, whats takes the CPU on the batched test is this:

![image](https://user-images.githubusercontent.com/16569217/75207149-af6a3a80-5756-11ea-9c87-78cb9a329329.png)

**Comment by badrishc** [comment]
In this situation below, we may need to ensure that we get prefix guarantee for the session, i.e., all three reads are persisted when the third read returns:

```cs
s.ReadAsync(1);
s.ReadAsync(2);
await s.ReadAsync(3, waitForCommit: true);
```

**Comment by ThiagoT1** [comment]
I believe it's already done.

This is bcz (on PR code) every call to ReadAsync already increments ```clientSession.ctx.serialNum```, and that's what ```clientSession.WaitForCommitAsync``` checks before short circuiting.

Could you look at that?

**Comment by ThiagoT1** [comment]
BTW, the problem here (and its not new) is that a 

```csharp
await s.ReadAsync(3, waitForCommit: true);
```

that's not followed by a check point being taken will hang forever.

This is bcz if the serialNum is too high, the Check Point task will be awaited.  And boom!

https://github.com/microsoft/FASTER/blob/bd5ad88df06e881559f56fd2b3c085e12f3229bf/cs/src/core/ClientSession/ClientSession.cs#L392-L406

This should be handled in a future PR, IMHO.

**Comment by badrishc** [comment]
The pattern is that there is an asynchronous periodic commit thread.

**Comment by badrishc** [comment]
> I believe it's already done.
> 
> This is bcz (on PR code) every call to ReadAsync already increments `clientSession.ctx.serialNum` (before the async state machine kicks in), and that's what `clientSession.WaitForCommitAsync` (executed on the continuation) checks before short circuiting.
> 
> Could you look at that?

I think there is a problem right now because some reads may have completed and others may not.

**Comment by badrishc** [comment]
> BTW, this branch works OK with the patched (PR) code, while failing with the current one.

That would be a bug, that can be fixed without breaking the FIFO semantics of completions. I tried the below testcase and it passes:

```cs
        public async Task AsyncObjectDiskWriteRead2()
        {
            using var session = fht.NewSession();

            for (int i = 0; i < 2000; i++)
            {
                var key = new MyKey { key = i };
                var value = new MyValue { value = i };
                await session.UpsertAsync(key, value);
            }

            List<ValueTask<(Status, MyOutput)>> t = new List<ValueTask<(Status, MyOutput)>>();
            var input = new MyInput();
            for (int i = 0; i < 2000; i++)
            {
                var key = new MyKey { key = i };
                t.Add(session.ReadAsync(key, input));
            }

            for (int i = 0; i < 2000; i++)
            {
                var result = await t[i];
                Assert.IsTrue(result.Item1 == Status.OK);
                Assert.IsTrue(result.Item2.value.value == i);
            }
      }
```

Can you provide a repro (using FASTER API) of what is failing and we can look into it?

**Comment by ThiagoT1** [comment]
You need to make sure the disk IO is being issued. The bug only manifests when completing disk IO.
