### ISSUE TITLE
Kernel32.dll System.DllNotFoundException - LINUX

### ISSUE THREAD

**Issue by cristianKumul** [microsoft/FASTER#249]
We are working with the Faster.Core and we have some problems with Kernel32.dll dependency.

We have used a Linux Docker image but when start the container fails with the following message:

System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies.

Anyone works with UNIX system?

**Comment by badrishc** [comment]
We have used FASTER on Linux with no issues. Is there a call stack?

Also see https://stackoverflow.com/questions/57174692/unable-to-load-shared-library-kernel32-dll-or-one-of-its-dependencies

**Comment by excme** [comment]
> We have used FASTER on Linux with no issues. Is there a call stack?
> 
> Also see https://stackoverflow.com/questions/57174692/unable-to-load-shared-library-kernel32-dll-or-one-of-its-dependencies

Can you help me, please? I use Faster.Server in Docker (in windows console mode are no issues). The connection is established through the standard port. But when calling
```
(Status, (System.Buffers.IMemoryOwner<byte>, int)) status = session.Read(s, t);
session.CompletePending(true);
```
session.CompletePending(true) - is executed indefinitely. 
Can you help me, please?
