### ISSUE TITLE
[C#] Question search in memory

### ISSUE THREAD

**Issue by AlexSenchenko** [microsoft/FASTER#252]
@badrishc 
Is it possible to use FASTER  for in-memory search, like here in SO question
https://stackoverflow.com/questions/14643146/fast-in-memory-search-for-multiple-attributes

Can you please provide an example if yes.

**Comment by badrishc** [comment]
We have a system called FishStore, whose goal is exactly this, perform attribute-based secondary indexing on a log (like a list, but which may span main memory and disk).

FishStore is open source but written in C++. We are currently porting the secondary indexing feature to FASTER C#. Read more about FishStore [here](https://github.com/microsoft/FishStore). The research paper is [here](https://badrish.net/papers/fishstore-sigmod19.pdf).

**Comment by AlexSenchenko** [comment]
@badrishc  thanks for details. Looks very promising. Do you have any plans when the C# migration of FishStore  will be available?

**Comment by badrishc** [comment]
We expect this feature to be generally available in a couple of months, cc @TedHartMS.

**Comment by plaisted** [comment]
@AlexSenchenko FishStore looks very cool as well as Mison. I have a use case to extract specific fields from large JSON objects, are there plans to port Mison to c# or just adding secondary indexing support for FASTER?

**Comment by badrishc** [comment]
Yes, our FishStore open source version uses simdjson as Mison is not open source. We are working on secondary indexing support for FASTER, hope to have it ready in a month or so. I will close this issue for now.
