### ISSUE TITLE
[C++] Is there any limits on the value size?

### ISSUE THREAD

**Issue by b-slim** [microsoft/FASTER#259]
Hello,
Wondering if there is any limit on how big a value can be ? am looking at some use cases where records are above 2MB up to 10MB.
This will be used by a Java App thus only route to go is JNI and DBB.
Please let me know if this makes sense.

**Comment by badrishc** [comment]
A record (8 byte header + key + value) can be at most of size one log page. The log page size is configurable via LogSettings and can be any size.

**Comment by badrishc** [comment]
Oh you are asking C++. Answer is similar, except its a constant, not configurable without recompiling. The page size is 32MB.
