### ISSUE TITLE
[C++] Is it possible to run the C++ version in a work-stealing executor?

### ISSUE THREAD

**Issue by mrobakowski** [microsoft/FASTER#265]
Hi. First of all, very impressive work! I see that in the C# version starting a new session returns a client object that can be used from async tasks, but the C++ version returns only a GUID. Are C++ sessions inherently pinned to threads? Is there any way to use the C++ version of FASTER from a work-stealing async/await-like context?

**Comment by badrishc** [comment]
Yes, the C++ version uses sessions pinned to threads. We added the unpinned session feature in C# due to the need of a majority of (async) use cases there, unlike C++ where most use cases find thread pinning to be sufficient.
