### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by mboogerd** [microsoft/FASTER#271]
The [Past work section](https://microsoft.github.io/FASTER/roadmap#past-work) mentions:

> Full support for .NET core and Linux/Mac

However, the build guide only mentions building on [Windows](https://microsoft.github.io/FASTER/cc#building-on-windows) and [Linux](https://microsoft.github.io/FASTER/cc#building-on-linux). It isn't exactly clear how to build this on macOS.

**Disclaimer / Context**
I'm not a C++ developer, my hope was to use FASTER via [Rust](https://github.com/faster-rs/faster-rs). However, on my macbook I'm stuck building FASTER itself due to `fatal error: 'libaio.h' file not found`.

I don't find it particularly clear whether libaio [should be available on macOS](https://stackoverflow.com/questions/5902662/aio-on-osx-is-it-implemented-in-the-kernel-or-with-user-threads-other-options) or [whether it can be installed at all](https://stackoverflow.com/questions/42698118/brew-how-install-cmake-libaio-devel-libffi-devel-glib2-glib2-devel) ([this](https://noknow.info/it/os/install_libaio_from_source#sec2-1) missed other dependencies, it feels like I'm going down a potentially wrong rabbit hole). If you have any information on how to build this project on macOS (without going the .net core route), that would be very useful!

**Comment by badrishc** [comment]
The support for Mac was tested with FASTER C# using .NET core. For FASTER C++, it should work in theory on Mac as well, but we haven't tried it out. The route you are following seems like the natural direction - let us know if you manage to get it working. Adding @chinkulkarni to comment if he has done this.

**Comment by mboogerd** [comment]
Hi @badrishc, faster-rs is indeed the library I was hoping to work with. However, it focuses only [on providing Linux support](https://github.com/faster-rs/faster-rs#experimental-faster-wrapper-for-rust). I have tried a number of things but from my non-existent C++ knowledge perspective: it looks like getting `libaio` to work may be challenging. Not sure if any other dependencies are hard to port to macOS.

**Comment by badrishc** [comment]
Closing as we do not plan to address MacOS support from our side. We welcome pull requests from interested users on the matter.
