### ISSUE TITLE
[C#] Atomic persist of multiple entries to FasterKV

### ISSUE THREAD

**Issue by kaleho** [microsoft/FASTER#275]
Is there a way to atomically commit multiple entries in FasterKV?

**Comment by badrishc** [comment]
Not out of the box. It's possible with a few changes to FASTER: perform the operations, take a foldover checkpoint/commit only after all the atomic operations are done. Also enforce that reads have to return only committed versions. These require non trivial changes to FASTER.

What's the scenario where you need this?

**Comment by kaleho** [comment]
The scenario is a command/event-sourced system where state is mutated and possibly multiple events are raised. I am trying to persist all atomically to a journal.

**Comment by marius-klimantavicius** [comment]
My 2c - for this I'd go with FasterLog instead of FasterKV but even then I'd have to implement a transaction of sorts manually (entries in log - `[BeginTransaction:T1] [T1:Ev1] [T1:Ev2] [EndTransaction:T1]`, commit to disk and wait for it to be stored, during recovery ignore all transactions that do not have `[EndTransaction]` and of course need to handle interleaving transactions).

**Comment by kaleho** [comment]
Hi Marius, thanks for your help. I did consider going down the FasterLog path initially because it does allow atomic batch commits. The random read specification is what is throwing me. The need to return the known address when the state snapshot is persisted instead of being able to compute the location deterministically via some convention is where I got blocked. Would love to hear thoughts about that if you have the time.

**Comment by kaleho** [comment]
Depending on some feedback, this is my plan for moving forward. I am going to use a FasterLog with a persisted tail iterator _and_ a separate FasterKV as an index. Since the guarantee is to only see committed entries during tail iteration I should be able to grab what I need and the address from that and store it in the FasterKV index. If the batch commit fails I will never receive it during the tail.

**Comment by badrishc** [comment]
Yes, that'll actually work fine. We'll think about how we might make this easier in future with FasterKv

**Comment by badrishc** [comment]
In your proposed solution, reads might see part of the committed transaction and not all of it. Is that okay?

If a transaction were (write A, write B), your committed tail iterator may have upserted A into FasterKV but not yet B. Then a reader would see A and get the older/notfound value for B.

**Comment by kaleho** [comment]
Given the way the index is being built and recovery should work I think it should be fine. I will close the issue.

Thank you @badrishc and @marius-klimantavicius for your help.

**Comment by badrishc** [comment]
Just to understand, why will it will work fine for readers in your case? Is it because you will prevent concurrent readers from accessing data while the FasterKV instance is being updated with newer transaction entries (after FasterLog commits), is that correct?

**Comment by kaleho** [comment]
I need the atomicity of the FasterLog write to ensure the all-or-nothing save so the snapshotted state is consistent with the events that are raised by the mutation. That should handle that failure scenario. The eventual consistency of the events being raised is something the system has been designed to handle and will be driven by being indexed into the KV as the log is tailed. Does it seem like I am missing something?

**Comment by badrishc** [comment]
Consider a batch with two operations: (Write A, Write B) that you commit atomically as a batch.

Your FasterKV updater thread tails the FasterLog iterator, and may have upserted A into FasterKV but not upserted B yet (it is about to upsert it next).

At that instant, a FasterKV reader thread would see A, but would *not* see B (as it has not been inserted yet). The reader will get an older/notfound value for record B.

This may be acceptable in your scenario, but I want to make sure you are aware of this limitation.

**Comment by kaleho** [comment]
I really appreciate your re-visiting that with me. I see where I did not address the concern you raised. Without going into all of it, there are other compensatory measures that do make the solution suitable for my scenario and I do acknowledge that limitation. Your passion for supporting this project and the people using it is really evident.

**Comment by iamirehsan** [comment]
Sorry but I need a sample from Fasterkv but I found nothing can somebody help me 
samples in github did not help me
