### ISSUE TITLE
[c#] KV log scanner hangs on GetNext

### ISSUE THREAD

**Issue by plaisted** [microsoft/FASTER#277]
Using FasterKV from class based c# playground example with some minor modifications:
```csharp
    public class MyKey : IFasterEqualityComparer<MyKey>
    {
        public string Key;

        public long GetHashCode64(ref MyKey key)
        {
            long x = key.Key.GetHashCode();
            return (x << 32) | x;
        }

        public bool Equals(ref MyKey key1, ref MyKey key2)
        {
            return key1.Key.Equals(key2.Key);
        }
    }

    public class MyValue
    {
        public byte[] Data;
    }
```
Initialization:
```csharp
            faster = new FasterKV
                <MyKey, MyValue, MyInput, MyOutput, Empty, MyFunctions>
                (1L << 20, new MyFunctions(),
                new LogSettings {  LogDevice = log, ObjectLogDevice = objlog, MemorySizeBits = 27, PageSizeBits = 23 },
                new CheckpointSettings() { CheckpointDir = "c:\\temp\\cdp\\FASTER\\checkpoints", CheckPointType = CheckpointType.FoldOver },
                new SerializerSettings<MyKey, MyValue> { keySerializer = () => new MyKeySerializer(), valueSerializer = () => new MyValueSerializer() }
                );
```

I add 100,000,000 KVP's with random data, take a checkpoint, and then try iterating all logs such as (no other operations happening):
```csharp
            var scanner = faster.Log.Scan(faster.Log.BeginAddress, faster.Log.TailAddress);
            while (scanner.GetNext(out var info, out MyKey key, out MyValue value))
            {
                Interlocked.Increment(ref numOps);
            }
```

The code hangs indefinitely on `scanner.GetNext` with CPU usage stuck at around 25% (1 core of a 4 core machine). I haven't got a chance to dig into the code for `GenericScanIterator` but do see the main logic is in a while loop so could explain it getting stuck if something was out of wack with addresses. Is there something obviously wrong with what I'm doing?

**Comment by plaisted** [comment]
I *think* this was caused by serialization issues. I wasn't seeing exceptions but it seems to have resolved itself once I noticed the `ref MyKey key` / `ref MyValue value` were null when passed into the de-serialization for values that had to be read from disk. I don't see any examples that construct the object but most are with structs or don't read from disk.  After adding `key ??= new MyKey();` the scanning is working.

I'd suggest for the examples in the playground working with classes to add in the null check / constructor. It is needed in the `IFunctions` implementations as well.

**Comment by plaisted** [comment]
Looks like it's acctually a bug in the `GenericScanIterator`:

Current code:
```csharp
                if (frame.GetInfo(currentFrame, offset).Invalid)
                    continue;
```
Needed fix:
```csharp
                if (frame.GetInfo(currentFrame, offset).Invalid)
                {
                    currentAddress += recordSize;
                    continue;
                }
```

I'll do a PR if I get CLA approval from work otherwise should be simple fix.

**Comment by badrishc** [comment]
Thanks, we are fixing it (required a few edits in other places are well).

**Comment by badrishc** [comment]
Fixed in master.

**Comment by plaisted** [comment]
Great, will reference source directly until the next release.

What causes invalid records? I had several parallel writers of upserts only with no shared keyspace. I thought they would all just write at the tail successfully.

**Comment by badrishc** [comment]
If a tail allocation is insufficient (at the end of a page, for example, we might not have enough space for the record), we have to mark it invalid and retry on the next page. That might explain it.
