### ISSUE TITLE
[C#] Question about IFasterEqualityComparer

### ISSUE THREAD

**Issue by Tornhoof** [microsoft/FASTER#278]
What happens if IFasterEqualityComparer GetHashCode/Equals returns multiple matches?

**Motivation**:
Let's say my Key is composed of two integers, both are database ids.
I'd like to delete values from the kv if I only know one of the ids, for example if the row for the first Id is removed, then  I'd like to remove all the values with Id1, but I do not necessarily know which values of Id2 are stored in the kv and calling them all is not an option.
Having a secondary kv storing all the keys for each Id would be a possibility I'd like to avoid for complexity reason.

Example:
The Comparer below would return multiple possible matches if Id2 is -1.

```csharp

public struct Key
{
   public long Id1;
   public long Id2;
}

public struct KeyComparer : IFasterEqualityComparer<KEy>
{
    public long GetHashCode64(ref Key k)
    {
        return k.Id1;
    }

    public unsafe bool Equals(ref Key k1, ref Key k2)
    {
	var id1Equals = k1.Id1 == k2.Id2;
	if(k2.Id2 == -1)
	{
	    return id1Equals;
	}
	return id1Equals && k1.Id1 == K2.Id2;
    }
}


```

**Comment by plaisted** [comment]
This sounds like a good use case for secondary indexes which are on FASTER's roadmap (see
https://github.com/microsoft/FASTER/issues/252).

Without secondary index (or secondary KV strore) I don't know of a good way to accomplish what you are saying as you would need to have the hashcode be the same for (Id1=val1,Id2=val2), (Id1=val1,Id2=-1), (Id1=-1,Id=val2) as the hashcode comparison would be the first check.

**Comment by Tornhoof** [comment]
Thank you for your quick answer, i'll close this issue and wait for the secondary indices and evaluate again.

**Comment by plaisted** [comment]
FYI not associated with FASTER nor an expert, just been prototyping a few things using it. Someone more clever may be able to come up with a way to get it to work as is.

**Comment by Tornhoof** [comment]
Thank you for your heads-up, nevertheless your points mirror my own findings and my question is answered.
