### ISSUE TITLE
Why do reads eat up a serial no?

### ISSUE THREAD

**Issue by Phylum123** [microsoft/FASTER#279]
Why is it that if you ReadAsync (or any method async) it creates the serial number for you and the non-async version allows you to give it anything? Why does ReadAsync consume a serialNo? 
Shouldn't reads be passive? Couldn't you just take the timestamp of the read and say show me the state of the record before that timestamp rather than using a serial no?

Any help on this would be appreciated :).

**Comment by badrishc** [comment]
We auto increment the serial number in order to simplify the async interface. Perhaps this should be added back in - not sure what's the use case though.

In general, users may want to increment the serial number for reads, as a commit (checkpoint) may declare one read as durable (i.e. the data returned by the read is durable) and the next read as not-yet-durable.

**Comment by Phylum123** [comment]
I was trying to synchronize multiple databases. The problem is that reads use a serial no, so I can
't use that to compare databases if one of them failed, to see how many records behind it is.

Maybe I am missing something about read then? Why would a checkpoint need to make a read durable? The read either happened or it didn't because it failed due to an exception. It doesn't affect data. What would a read look like that is "not-yet-durable"? How does it differ?

**Comment by badrishc** [comment]
When you perform a read in FASTER, it might return data in the mutable region of the log (in memory). This underlying data is subject to loss in case of failure, so the read is not guaranteed to be a read of durable data. After a checkpoint/commit, the data becomes durable, and we report such durability to the used with a commit point (serial number) such that all operations (read and write) until that point correspond to durable data.
