### ISSUE TITLE
[C#] Input-specific functions in IVariableLengthStruct

### ISSUE THREAD

**Issue by badrishc** [microsoft/FASTER#289]
In https://github.com/microsoft/FASTER/pull/270, we added an additional method to `IVariableLengthStruct`:

`int GetLength<Input>(ref T t, ref Input input)`

In addition, we already had this earlier:

`int GetInitialLength<Input>(ref Input input)`

With the moving of `Input` to client sessions (which is a huge improvement, btw), it is causing complications when users have sessions with different input types on the same FASTER store, as the above two functions cannot be typed specifically to a session.

The proposal would be to instead provide these two methods via `ClientSession` (internally, `FasterSession`) so that they may be customized per Input type.

CC @marius-klimantavicius as you authored the above-referenced PR and are in the best position to comment/contribute on this.

**Comment by badrishc** [comment]
Also cc @mito-csod

**Comment by marius-klimantavicius** [comment]
We could move out methods from `IVariableLengthStruct` to `IFasterSession<...>` what I am thinking about is how to handle `Generic` and `Blittable` cases (relatively easy to do) and how to allow the user to specify the required methods (without affecting fixed size cases). One idea is to have `IVariableLengthStruct` as is (or with `<Input>` methods removed) and introduce additional `ISessionVariableLengthStruct` (or similar, naming is difficult) which could be optionally provided when creating client session (for fixed sizes it would be either exception or not used).

**Comment by badrishc** [comment]
Mates sense. We could introduce `IVariableLengthStruct<T, TInput>` that could be provided per session. If not provided, we would default to fall through to existing `IVariableLengthStruct`.

**Comment by badrishc** [comment]
PR is out, will merge soon based on feedback if any.
