### ISSUE TITLE
State Machine race for async clients

### ISSUE THREAD

**Issue by tli2** [microsoft/FASTER#295]
When an async client resumes, it first reads the current state and the state machine object and fast-forwards to the current cycle. This is buggy if another thread simultaneously start a new state machine --- the async thread will capture the new state machine, but believe it to be in the old cycle, because the state it sees is REST, and it cannot differentiate between REST being the end of the last cycle and the beginning of the new cycle. Depending on the state machine being swapped in, the failure can lead to crashes or non-termination of the state machine logic.

The fix should involve capturing the state machine object in session context before suspending a thread.

**Comment by badrishc** [comment]
Related latency (not correctness) issue:  a thread during `OnThreadState` in the state machine accesses global FASTER-level information such as `faster._hybridLogCheckpoint`. If the thread were a catch-up thread, this information may in fact pertain to the future, such as a future `faster._hybridLogCheckpoint.info.finalLogicalAddress`. This would cause the late thread to spin while catching up, until the ongoing (future) condition is satisfied.
