### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by vhe1** [Microsoft/FASTER#30]
I'm getting "Failed  to add reference to 'adv-file-ops'.".
Is there anything I'm doing wrong? I wanted to add it to a 4.7.1 class library project.

This is the output:

Attempting to gather dependency information for package 'FASTER.core.1.0.0' with respect to project 'EventProcessor', targeting '.NETFramework,Version=v4.7.1'
Gathering dependency information took 744,2 ms
Attempting to resolve dependencies for package 'FASTER.core.1.0.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'FASTER.core.1.0.0'
Resolved actions to install package 'FASTER.core.1.0.0'
Retrieving package 'FASTER.core 1.0.0' from 'nuget.org'.
Adding package 'FASTER.core.1.0.0' to folder 'C:\Users\v.hetzer\source\repos\EventSender\packages'
Added package 'FASTER.core.1.0.0' to folder 'C:\Users\v.hetzer\source\repos\EventSender\packages'
Install failed. Rolling back...
Package 'FASTER.core.1.0.0 : Microsoft.CodeAnalysis.CSharp.Scripting [2.8.2, ), System.Reflection.Emit.ILGeneration [4.3.0, ), System.Runtime.CompilerServices.Unsafe [4.5.1, )' does not exist in project 'EventProcessor'
Removing package 'FASTER.core.1.0.0 : Microsoft.CodeAnalysis.CSharp.Scripting [2.8.2, ), System.Reflection.Emit.ILGeneration [4.3.0, ), System.Runtime.CompilerServices.Unsafe [4.5.1, )' from folder 'C:\Users\v.hetzer\source\repos\EventSender\packages'
Removed package 'FASTER.core.1.0.0 : Microsoft.CodeAnalysis.CSharp.Scripting [2.8.2, ), System.Reflection.Emit.ILGeneration [4.3.0, ), System.Runtime.CompilerServices.Unsafe [4.5.1, )' from folder 'C:\Users\v.hetzer\source\repos\EventSender\packages'
Executing nuget actions took 1,73 sec
Failed to add reference to 'adv-file-ops'.
  Please make sure that the file is accessible, and that it is a valid assembly or COM component.
Time Elapsed: 00:00:02.7011605
========== Finished ==========

(The package dependencies _are_ there because I installed them.)

**Comment by badrishc** [comment]
The version of FASTER that you probably found on NuGet is not owned or supported by us. Please download sources and link directly. We do not have binary NuGet packages for FASTER at this point.
