### ISSUE TITLE
How to force FASTER to compact object log?

### ISSUE THREAD

**Issue by AntyaDev** [microsoft/FASTER#308]
I am trying to simulate behavior:

1. I inserted 100 keys
2. I created a snapshot
3. I deleted 100 keys
4. I invoked log.Comapct

Should my object log file become smaller?
or maybe I can somehow override the whole content of the current object file to make it empty?

**Comment by badrishc** [comment]
Log compaction deletes files only at segment granularity, that you can control via settings.

**Comment by AntyaDev** [comment]
thanks,
