### ISSUE TITLE
Can I limit RAM size of my FASTER application

### ISSUE THREAD

**Issue by AntyaDev** [microsoft/FASTER#309]
I would like to set a limit for RAM size used by FASTER to not allow growth over 100MB?
How I can achieve this?

I played with log settings:
```
                logSettings: new LogSettings
                {
                    LogDevice = _logDevice,
                    ObjectLogDevice = _objDevice,
                    PageSizeBits = 12,
                    MemorySizeBits = 20
                },
```

But I don't see any effect.

**Comment by badrishc** [comment]
Yes, you can. The total memory usage of FASTER is governed by `MemorySizeBits`. 2^MemorySizeBits is the total memory used by the main log in memory.

If your keys and values are class objects (not blittable structs), the main log takes 24 bytes per record in the main log (8 byte record header + 8 byte reference to key + 8 byte reference to value). So, the total number of key-value records in memory is approximately `(2^MemorySizeBits)/24`.  Knowing the approximate size of keys and values, you can control the total memory footprint of FASTER when used with C# class objects.

See more details at https://microsoft.github.io/FASTER/docs/tuning

**Comment by AntyaDev** [comment]
Hi @badrishc ,

I tried using these settings:

PageSizeBits = 20, 
MemorySizeBits = 24 

and loaded about 2GB of data.
The thing is that I even after using:

_db.Log.FlushAndEvict(true);
GC.Collect();

I still see in my monitoring that my dotnet app eats ~2GB of RAM.

Do you have any example that I can try to run and see that memory is not grows?

**Comment by AntyaDev** [comment]
Hi @badrishc 

I see very weird behavior on restore:
when I use:
PageSizeBits = 12, 
MemorySizeBits = 20, 

and added from 0 to 2000 keys. after restore, I can't get any value.

Also, I see that when I want to debug I very often get into a situation with deadlock on db.Restore().

**Comment by badrishc** [comment]
Can you share your key and value types, details?

**Comment by badrishc** [comment]
> Also, I see that when I want to debug I very often get into a situation with deadlock on db.Restore().

Make sure you are not trying to call `db.Restore()` on a older disposed `db` instance. See simple example here (working on that branch) for checkpoint-recovery: https://github.com/microsoft/FASTER/blob/updated-samples/cs/samples/StoreCheckpointRecover/Program.cs

**Comment by badrishc** [comment]
I see you deleted the comment on growing memory footprint. Is that resolved now?

**Comment by badrishc** [comment]
Here is an example of demonstrating memory footprint constant in FASTER:

* Start with project at https://github.com/microsoft/FASTER/tree/updated-samples/cs/samples/CacheStore
* Change `PageSizeBits` to `12` and `MemorySizeBits` to `20`
* Change `CacheValue` to the below (inflating size to see effects clearly):
```cs
    public class CacheValue
    {
        public long value;
        public byte[] padding;

        public CacheValue(long first)
        {
            value = first;
            padding = new byte[10000];
        }
    }
```
* Let the program run until upserts finish - you will see that memory stabilizes at around `520`MB during upserts. This is because we have `(1048576/24)=43690` `CacheValue` objects in memory, each of size around `10000` bytes = `440`MB in total.
* The rest of the space is taken up by the hash table, which we configured to be `1L << 20` cache lines each of size 64 bytes, for a total of `64`MB space.
* To confirm, attach to VS and examine the heap - you will notice that the majority of the memory footprint is the `CacheValue` objects, and they account for only around `436`MB, as expected. The hash table is not shown in VS because it is allocated as native pinned memory.
* Finally, note that there will be slight memory growth over time as new keys enter the database, because there will be overflow bucket hash entries allocated (8 bytes) in the hash table. This can also be controlled if needed, by manipulating the hashcode for keys. I will not get into details here as this might not be a critical matter.

**Comment by AntyaDev** [comment]
Thanks for help.

in your example if you uncomment:
PageSizeBits = 12, // (4K pages)
MemorySizeBits = 20 // (1M memory for main log)

and run 0 = random reads

you will get:
Issuing uniform random read workload of 1000000 reads
Unhandled exception. System.Exception: Read error!
   at CacheStore.CacheFunctions.ReadCompletionCallback(CacheKey& key, CacheValue& input, CacheValue& output, CacheContext ctx, Status status) in /Users/anton.mo/Desktop/work/FASTER-New/FASTER/cs/samples/CacheStore/Types.cs:line 91

**Comment by badrishc** [comment]
I am not seeing this issue on my end, either in Release or Debug modes (Windows). Can you share more info on the environment you are running in?

**Comment by AntyaDev** [comment]
Mac 16 Pro.

```
var log = Devices.CreateLogDevice("./hlog.log");

            // Log for storing serialized objects; needed only for class keys/values
            var objlog = Devices.CreateLogDevice("./hlog.obj.log");

            // Define settings for log
            var logSettings = new LogSettings {
                LogDevice = log, 
                ObjectLogDevice = objlog,
                ReadCacheSettings = useReadCache ? new ReadCacheSettings() : null,
                // Uncomment below for low memory footprint demo
                // PageSizeBits = 12, // (4K pages)
                // MemorySizeBits = 20 // (1M memory for main log)
            };

            // Define serializers; otherwise FASTER will use the slower DataContract
            // Needed only for class keys/values
            var serializerSettings = new SerializerSettings<CacheKey, CacheValue> {
                keySerializer = () => new CacheKeySerializer(),
                valueSerializer = () => new CacheValueSerializer()
            };

            // Create instance of store
            var store = new FasterKV<CacheKey, CacheValue>(
                size: 1L << 20,
                logSettings: logSettings,
                checkpointSettings: new CheckpointSettings
                {
                    CheckpointDir = "checkpoints",
                    CheckPointType = CheckpointType.FoldOver
                },
                serializerSettings: serializerSettings,
                comparer: new CacheKey(0)
                );
```

**Comment by badrishc** [comment]
Does this happen with the first read issued by `RandomReadWorkload`? What are the values (output.value and key.key) you see at the point where exception is thrown?

**Comment by AntyaDev** [comment]
Btw. 

I took your branch and uncomment this line
(bool success, Guid token) = store.TakeFullCheckpointAsync(CheckpointType.FoldOver).GetAwaiter().GetResult();

and now I failing with

Writing keys from 0 to 1000000 to FASTER
0: 81M
524288: 145M
Total time to upsert 1000000 elements: 0.676 secs (1479289.94 inserts/sec)
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/anton.mo/Desktop/work/FASTER-New/FASTER/cs/samples/CacheStore/bin/x64/Debug/netcoreapp3.1/checkpoints/index-checkpoints/16b2e7ee-cdac-46a5-ace3-8aec4837ad17/ht.dat.0'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at FASTER.core.ManagedLocalStorageDevice.CreateWriteHandle(Int32 segmentId) in /Users/anton.mo/Desktop/work/FASTER-New/FASTER/cs/src/core/Device/ManagedLocalStorageDevice.cs:line 339
   at FASTER.core.ManagedLocalStorageDevice.<>c__DisplayClass17_0.<AddHandle>b__1() in /Users/anton.mo/Desktop/work/FASTER-New/FASTER/cs/src/core/Device/ManagedLocalStorageDevice.cs:line 358


But then I adopted your example to latest nuget: 
<PackageReference Include="Microsoft.FASTER" Version="2020.7.31.1" />

and use this for chekpoint:
store.TakeFullCheckpoint(out var _);
store.CompleteCheckpointAsync().GetAwaiter().GetResult();

and it works, I mean it doesn't fail on the checkpoint.

one more question: who is clearing checkpoints? (For example, I want to keep n latest checkpoints and clean up the rest)

**Comment by badrishc** [comment]
updated-samples is still work in progress, the checkpoint directory error is a minor one that happens only on non-Windows machines - just pushed an update to fix it (on the same updated-samples branch). Sorry I don't have a mac to test on.

**Comment by badrishc** [comment]
User has to clear old checkpoints. You can extend DeviceLogCommitCheckpointManager to do this, or just do it from outside by checking the directory contents.

**Comment by AntyaDev** [comment]
if (output.value != key.key)
                 0       != 44217
    throw new Exception("Read error!");

It's not deterministic which is really worrying me, I run several times and no error.

> User has to clear old checkpoints. You can extend DeviceLogCommitCheckpointManager to do this, or just do it from outside by checking the directory contents.

that's what I thought. 
thx for your help!

Btw, I see you started simplifying an API, it's cool!

**Comment by badrishc** [comment]
What is `CacheValue` type when you get the error? struct or class?

**Comment by AntyaDev** [comment]
> Do you get this where you adapted the sample to the latest NuGet?
for some time I have seen ob both, but now I can reproduce only on an older version (nuget)

CacheKey: 817325
CacheValue: 0

public struct CacheValue
    {
        public long value;

        public CacheValue(long first)
        {
            value = first;
        }
    }

**Comment by AntyaDev** [comment]
on your latest branch for some reason, I can't reproduce

Writing keys from 0 to 1000000 to FASTER
0: 81M
524288: 145M
Total time to upsert 1000000 elements: 0.659 secs (1517450.68 inserts/sec)
Enter read workload type (0 = random reads; 1 = interactive): 0
Issuing uniform random read workload of 1000000 reads
Total time to read 1000000 elements: 0.557 secs (1795332.14 reads/sec)
Reads completed with PENDING: 0
Press <ENTER> to end

**Comment by badrishc** [comment]
> Reads completed with PENDING: 0
That means nothing is being served by disk. Are you sure you uncommented the two lines?

**Comment by badrishc** [comment]
I meant the two lines related to sizing memory (PageSizeBits and MemorySizeBits).

If you sync the latest code in that branch, you will not get the checkpoint error you show above.

**Comment by AntyaDev** [comment]
Yes, they uncommented

var logSettings = new LogSettings {
                LogDevice = log, 
                ObjectLogDevice = objlog,
                ReadCacheSettings = useReadCache ? new ReadCacheSettings() : null,
                // Uncomment below for low memory footprint demo
                PageSizeBits = 12, // (4K pages)
                MemorySizeBits = 20 // (1M memory for main log)
            };

I can check on my Ubuntu just to compare.

**Comment by badrishc** [comment]
When memory footprint is made low using PageSizeBits and MemorySizeBits, you should NOT see this message with 0 pending reads. Can you confirm the same.

> Reads completed with PENDING: 0

**Comment by AntyaDev** [comment]
Ok, now I got how to reproduce it on your latest changes.

So if I run with defaults without any checkpoints then I got this:

Writing keys from 0 to 1000000 to FASTER
0: 81M
524288: 145M
Total time to upsert 1000000 elements: 0.709 secs (1410437.24 inserts/sec)
Enter read workload type (0 = random reads; 1 = interactive): 0
Issuing uniform random read workload of 1000000 reads
Total time to read 1000000 elements: 0.507 secs (1972386.59 reads/sec)
Reads completed with PENDING: 0

But when I run with low footprint:

```
var logSettings = new LogSettings {
                LogDevice = log, 
                ObjectLogDevice = objlog,
                ReadCacheSettings = useReadCache ? new ReadCacheSettings() : null,
                // Uncomment below for low memory footprint demo
                PageSizeBits = 12, // (4K pages)
                MemorySizeBits = 20 // (1M memory for main log)
            };
```

I am getting:

Writing keys from 0 to 1000000 to FASTER
0: 16M
524288: 90M
Total time to upsert 1000000 elements: 1.214 secs (823723.23 inserts/sec)
Enter read workload type (0 = random reads; 1 = interactive): 0
Issuing uniform random read workload of 1000000 reads
Unhandled exception. System.Exception: Read error!
   at CacheStore.CacheFunctions.ReadCompletionCallback(CacheKey& key, CacheValue& input, CacheValue& output, CacheContext ctx, Status status) in /Users/anton.mo/Desktop/work/FASTER-New/FASTER/cs/samples/CacheStore/Types.cs:line 93
   at FASTER.core.ClientSession`6.AsyncFasterSession.ReadCompletionCallback(Key& key, Input& input, Output& output, Context ctx, Status status) in /Users/anton.mo/Desktop/work/FASTER-New/FASTER/cs/src/core/ClientSession/ClientSession.cs:line 609

**Comment by badrishc** [comment]
Ok, looks like it is something OS specific, for that storage device being accessed though `ManagedLocalStorageDevice`. Using `ManagedLocalStorageDevice` on Windows does not reproduce the same issue.

**Comment by badrishc** [comment]
Can you see if it happens on the first read you issue? Does it always happen, or non-deterministically?

**Comment by AntyaDev** [comment]
I can reproduce it always but the key's value is different between runs:
KEY: 726243
KEY: 558884
KEY: 726243
...

let me check on Ubuntu

**Comment by AntyaDev** [comment]
I checked on Ubuntu 20.04
the same behavior:

Writing keys from 0 to 1000000 to FASTER
0: 28M
524288: 105M
Total time to upsert 1000000 elements: 2.796 secs (357653.79 inserts/sec)
Enter read workload type (0 = random reads; 1 = interactive): 0
Issuing uniform random read workload of 1000000 reads
Unhandled exception. System.Exception: Read error!
   at CacheStore.CacheFunctions.ReadCompletionCallback(CacheKey& key, CacheValue& input, CacheValue& output, CacheContext ctx, Status status) in /home/antyadev/Desktop/work/FASTER-NEW/FASTER/cs/samples/CacheStore/Types.cs:line 91
   at FASTER.core.ClientSession`6.AsyncFasterSession.ReadCompletionCallback(Key& key, Input& input, Output& output, Context ctx, Status status) in /home/antyadev/Desktop/work/FASTER-NEW/FASTER/cs/src/core/ClientSession/ClientSession.cs:line 609

**Comment by badrishc** [comment]
That is indeed extremely odd. We will provision a linux machine and get to the bottom of this.

**Comment by badrishc** [comment]
Tried many times on Linux using WSL (Windows Subsystem for Linux), seems to work fine.

```
$ dotnet run
Writing keys from 0 to 1000000 to FASTER
0: 18M
524288: 89M
Total time to upsert 1000000 elements: 1.388 secs (720461.10 inserts/sec)
Enter read workload type (0 = random reads; 1 = interactive): 0
Issuing uniform random read workload of 1000000 reads
Total time to read 1000000 elements: 16.386 secs (61027.71 reads/sec)
Reads completed with PENDING: 956619
Press <ENTER> to end
```

**Comment by badrishc** [comment]
OK - this was easy to fix once I got my hands on a real Linux box. The PR https://github.com/microsoft/FASTER/issues/309 fixes it.

Basically, in Windows it is acceptable to perform parallel reads on the same handle. However, on non-Windows platforms, you have to sequentialize operations on the same file handle.

We were already taking care of this for parallel Writes on non-Windows. The linked PR does the same for Reads as well.

**Comment by AntyaDev** [comment]
Thank you so much for this fix!

**Comment by TechnikEmpire** [comment]
Sorry to necro this ancient thread, but if you modify the given sample to actually destroy and recreate the store instance, and then attempt recovery, while limiting the memory usage, it crashes with the same error as originally reported. I've tested this again and again, even with my own entirely bespoke code, in C# and C++. I cannot, for the life of me, figure out why. Any insights? Should I make a fork for repro purposes?
