### ISSUE TITLE
Shared Memory

### ISSUE THREAD

**Issue by thegreathir** [Microsoft/FASTER#32]
Is it available to use Faster across processes? I mean allocating Faster in Shared Memory or set it to use Shared Memory as device!

**Comment by badrishc** [comment]
* If you want to access FASTER data remotely (from a different process or machine), you could do so by creating a sockets interface to the API of the store, owned by one process. We don't have such a "server" out of the box as we focus on embedded in the first version, but this would be interesting.

* A device in FASTER is where the colder part of the log goes to reside longer term. Making the device reside in shared memory is interesting, but I'm not sure what value it would provide over the remote access API mentioned above.

**Comment by thegreathir** [comment]
> I'm not sure what value it would provide over the remote access API mentioned above.
It's FASTER(!). The Approach you mentioned has one copy more than allocating faster on shared memory and share it between processes!

Any way, Do you think is it possible to allocating FASTER on shared memory (with boost shared memory allocator for example)? And if yes will you make it possible to config FASTER to use a foreign allocator?

**Comment by badrishc** [comment]
Yes, you would need to implement your own "device" instead of the provides ones such as https://github.com/Microsoft/FASTER/blob/master/cc/src/device/file_system_disk.h
