### ISSUE TITLE
[C#] FasterKV for Span<byte> keys and values

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [microsoft/FASTER#329]
Do you think there would be value in a primitive like a `FasterKV` but that only operated on `Span<byte>` for the keys and values?

I'm migrating some test code from LMDB and really came to appreciate the simplicity of just working with blobs.

**Comment by badrishc** [comment]
Yes, absolutely. This has been on our radar for a while. It's actually not hard to pull off as a layer over our 'varlen' struct support.

Related, FasterLog already works on top of Span<byte>, see here: https://github.com/microsoft/FASTER/blob/master/docs/cs/FasterLog.md

**Comment by mito-csod** [comment]
In the same spirit, what do you think about supporting Memory<T> and ReadOnlyMemory<T> in FasterLog.EnqueueAsync(),, @badrishc? It would let us use pooled memory chunks we might have gotten elsewhere without the extra copying to byte[], and still let us use async. Happy to send a PR if you think it's a worthwhile addition.

**Comment by badrishc** [comment]
> In the same spirit, what do you think about supporting Memory and ReadOnlyMemory in FasterLog.EnqueueAsync(),, @badrishc? It would let us use pooled memory chunks we might have gotten elsewhere without the extra copying to byte[], and still let us use async. Happy to send a PR if you think it's a worthwhile addition.

Yes, that would definitely be a worthwhile addition!

**Comment by mito-csod** [comment]
My bad, it looks like the ReadOnlyMemory implementation is already there--intellisense tricked me!
