### ISSUE TITLE
How to iterate records?

### ISSUE THREAD

**Issue by ace37** [Microsoft/FASTER#34]

**Comment by badrishc** [comment]
Iteration is not implemented yet, but should be fairly easy to add. Are you trying the C# or C++ version?

**Comment by diegotormes** [comment]
I need iterate too. I'm using c# version.

**Comment by chiwanpark** [comment]
Iterator are also needed in C++ version.

**Comment by badrishc** [comment]
We now have a scan interface to iterate through all records in the log; see https://github.com/Microsoft/FASTER/pull/90.

This is slightly different from iteration, in that it returns the entire history of the store including records that were subsequently overwritten. One can perform duplicate elimination on top to get a true iterator. To get an idea of how to do this, see our log compaction logic here: https://github.com/Microsoft/FASTER/blob/a06ad6a198bce52f9ba802383285b6c82e1bca08/cs/src/core/Index/FASTER/LogAccessor.cs#L152

We do not plan to add iterators to the C++ version, but will consider reasonable PRs.
