### ISSUE TITLE
Can faster scale out? 

### ISSUE THREAD

**Issue by andtii** [microsoft/FASTER#344]
Does faster support a scaleout model where faster can run on different nodes and persist/read from same Storage?

**Comment by marius-klimantavicius** [comment]
No there is no such support.

**Comment by andtii** [comment]
![image](https://user-images.githubusercontent.com/1434571/94811499-bc8a8e80-03f5-11eb-803f-8e76bb2d9382.png)
I see something is cooking - https://microsoft.github.io/FASTER/roadmap

**Comment by badrishc** [comment]
Right now, we do not have any code to share in this regard. However, this feature indeed on our longer-term roadmap, in stages:
* Basic client -> single server support via remote API
* Scale-out (multiple servers, sharded state) without dynamic elasticity/state migration
* Elasticity

We would be very interested in the reasons for your query. Is this something you want to use, or contribute? What is the scenario, and what features are most important to you?

You can also read our recent [research paper](https://arxiv.org/pdf/2006.03206.pdf), that describes the kind of performance one can expect in a remote client-server setting with FASTER.

**Comment by badrishc** [comment]
Coming to think of it, there is one important thing you can certainly do even today with FASTER. Maybe this is what you were looking for:

You can use a shared cloud storage log as your backing store, and fire up as many read-only instances of FASTER KV (on different machines) as you want to scale up your read workload. The only restriction is that only one FASTER instance is allowed to write to the database at any point in time.

In fact, there is a working example of exactly this design pattern, here:
* https://github.com/microsoft/FASTER/tree/master/cs/samples/SecondaryReaderStore

In this example, if you replace the local storage device (line 26) with a cloud storage device, as in this example below, you get the above-mentioned functionality.
* https://github.com/microsoft/FASTER/tree/master/cs/samples/AzureBackedStore

Hope this helps.
