### ISSUE TITLE
[C#] Remote FASTER KV support under client-server model

### ISSUE THREAD

**Issue by badrishc** [microsoft/FASTER#348]
We are excited to announce that the C# version of FASTER (the KV store + cache) will soon add the ability to support remote clients in a standard "client-server" deployment model.

The overall approach is:
* Create a FASTER KV server with custom types and functionality on a specified port
* Instantiate lightweight FASTER clients that connect to a destination server machine and port
* Client-side sessions are mostly compatible with the existing local `ClientSession` API. Each client session establishes a separate connection to the server, with a shadow session on the server side.

The first version will use a highly optimized custom binary data format along with a C# client to demonstrate the best-case performance. We will welcome contributions for clients in other languages as well.

In future, we plan to investigate compatibility with existing protocols as well, so that existing open-source clients can talk to FASTER as well, perhaps at lower performance.

Look out for a PR linking to this issue soon!

**Comment by gelihu** [comment]
Would it be possible to support a Messaging Queuing system(Faster Log + Server) also in any near future 😉  ?

**Comment by badrishc** [comment]
Yes, that's possible. Are you looking for just the current FasterLog API, but accessed via remote?

**Comment by gelihu** [comment]
> Yes, that's possible. Are you looking for just the current FasterLog API, but accessed via remote?

Yes sir!
