### ISSUE TITLE
SpanByte.ToByteArray() returns only the first 16 byte of the data if not used are reference

### ISSUE THREAD

**Issue by resetcoder** [microsoft/FASTER#360]
When iterating through entries in the log like

```
                using (IFasterScanIterator<SpanByte, SpanByte> iterator = kv.Log.Scan(kv.Log.BeginAddress, kv.Log.TailAddress))
                {
                    while (iterator.GetNext(out RecordInfo recordInfo))
                    {
                            // processing entry
                    }
                }
```
If I use process like

```
                        SpanByte keyObj = iterator.GetKey();
                        Console.WriteLine("Key: " + Encoding.ASCII.GetString(keyObj.ToByteArray()));
```
then I get back only the first 16 byte of the data, and some junk bytes (probably pointer value, or irrelevant part of the memory, which may cause memory access violation exception).

If It process it like

```
                        ref SpanByte keyObj = ref iterator.GetKey();
                        Console.WriteLine("Key: " + Encoding.ASCII.GetString(keyObj.ToByteArray()));
```
then it works fine.

Anyways, this is not working if I use it as an out parameter, then I get only the first 16 bytes again:
```
                    while (iterator.GetNext(out RecordInfo recordInfo, out SpanByte keyObj, out SpanByte valueObj))
                    {
                        Console.WriteLine("Key: " + Encoding.ASCII.GetString(keyObj.ToByteArray()));
                    }
```
and reffing didn't help either:
```
                    while (iterator.GetNext(out RecordInfo recordInfo, out SpanByte keyObj, out SpanByte valueObj))
                    {
                        ref SpanByte refKeyObj = ref keyObj;
                        Console.WriteLine("Key: " + Encoding.ASCII.GetString(refKeyObj.ToByteArray()));
                    }
```

This means either SpanByte ToByteArray() method gets the data the wrong way if not referenced, or can not be used as out parameter.

**Comment by badrishc** [comment]
Yes, that's the way SpanByte works. It's not a bug. Varlen structs are like pointers, your can only access them via ref variable. The overloads with out will not work. If this is not acceptable, you can use Memory, or byte[] via object log.

**Comment by badrishc** [comment]
The reason we have ref GetKey etc is exactly for this reason, to be able to work with varlen structs.

**Comment by resetcoder** [comment]
I kept an eye on the source of the SpanByte and thought this is somehow normal, but this still means it can not be used the way I described above, it may help to someone, and may avoid confusion why it is not working right if they try get it through the iterator out parameter.
Btw iterator may have a ref parameter instead, or in addition.

> The reason we have ref GetKey etc is exactly for this reason, to be able to work with varlen structs.

Ok if this was planned, then this is a non-issue.

**Comment by badrishc** [comment]
Iterator `ref parameter` will not help. It has to be a `ref return` variable, for varlen to work correctly. We might add a warning of someone uses the out version with SpanByte.

**Comment by badrishc** [comment]
> Anyways, this is not working if I use it as an out parameter, then I get only the first 16 bytes again:
> 
> ```
>                     while (iterator.GetNext(out RecordInfo recordInfo, out SpanByte keyObj, out SpanByte valueObj))
>                     {
>                         Console.WriteLine("Key: " + Encoding.ASCII.GetString(keyObj.ToByteArray()));
>                     }
> ```

FYI, if you do the above with `SpanByte` you will get an exception saying it is not supported (not first 16 bytes).

`System.NotSupportedException: 'Use GetNext(out RecordInfo) to retrieve references to key/value'.`

**Comment by resetcoder** [comment]
It's fine for me, but it was a bit confusing. I know the project is still in progress, but without complete documentation this may cause some confusion. I've noticed I can use SpanByte only if reffed, so I've been using it since the beginning with ref.
Btw it caused some problem when I tried to make extension for SpanByte, and I just couldn't pass it anyhow to the extension method, because couldn't read only the first 16 bytes even if it was ref. This way a few days ago, I don't really remember how I did it, I may try again, because adding SetString() and GetString() would be nice, since keys are usually strings, but better to store them as byte[]. It is not a big problem, though, conversion in place is not a biggie.

**Comment by badrishc** [comment]
Non-power-users should avoid `SpanByte` and use `Memory<T>` which behaves identically to normal C# types. `SpanByte` is a rather unique construct (pointer-based) that cannot be ever accessed in a non-`ref` setting, and as a return parameter it has to be a `ref return` value, not a `ref` or `out` param.
