### ISSUE TITLE
Dispose does not seem to properly release local file

### ISSUE THREAD

**Issue by mnmr** [microsoft/FASTER#363]
It does not seem like FasterLog releases the file handle for the local storage device when it is disposed.

The following XUnit test demonstrates the problem:

```
        [Fact]
        public async Task FileReleaseOnDisposeTest()
        {
            const string path = @"d:\codeum\faster\dispose2";
            ClearTargetDirectory(path);

            var fileName = Path.Combine(path, "store");
            var device = Devices.CreateLogDevice(fileName, deleteOnClose:false);
            var faster = new FasterLog(new FasterLogSettings { LogDevice = device });

            foreach (var item in Enumerable.Range(1, 1000))
            {
                await faster.EnqueueAsync(BitConverter.GetBytes(item)).ConfigureAwait(false);
            }
            await faster.CommitAsync().ConfigureAwait(false);
            faster.Dispose();

            ClearTargetDirectory(path);
            Assert.True(!File.Exists(fileName));
        }
```

This unit test fails with the following error:

```
System.IO.IOException: The process cannot access the file 'store.0' because it is being used by another process.

System.IO.IOException
The process cannot access the file 'store.0' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at RF.Test.Common.Faster.FasterLogTests.ClearTargetDirectory(String path) in D:\Code\RabbitFoot\src\Tests\RF.Test.Common\Faster\FasterLogTests.cs:line 24
   at RF.Test.Common.Faster.FasterLogTests.FileReleaseOnDisposeTest() in D:\Code\RabbitFoot\src\Tests\RF.Test.Common\Faster\FasterLogTests.cs:line 220
```

No iterators are created here, so the internal logRefCount should not have been incremented beyond 1. Reflection access to the logRefCount field after Dispose confirms that it has been reduced to 0, but the ClearTargetDirectory method fails because the file is still locked.

**Comment by plaisted** [comment]
`IDevice` you are creating using `Devices.CreateLogDevice(fileName, deleteOnClose:false);` implements `IDisposable` which is likely holding the lock.

**Comment by mnmr** [comment]
> `IDevice` you are creating using `Devices.CreateLogDevice(fileName, deleteOnClose:false);` implements `IDisposable` which is likely holding the lock.

That solves it, thanks! Still think FasterLog should dispose the inner device, but there could be reasons for not doing so.

**Comment by badrishc** [comment]
You created the device, so you would be responsible for disposing it as per usual norms. Just putting a `using` in front of both device and log will do the right thing.

**Comment by mnmr** [comment]
> You created the device, so you would be responsible for disposing it as per usual norms. 

I just assumed that the only thing to dispose for FasterLog would be the device, and thus that I wouldn't need to dispose anything else. It never even occurred to me to dispose the IDevice directly, which is of course a blunder.

> Just putting a `using` in front of both device and log will do the right thing.

It's rather long-lived so that won't work, but my wrapper class now properly disposes both the device and the FasterLog instance, and all seems to be well after that.
