### ISSUE TITLE
File size is not visible from Windows Explorer while application is running

### ISSUE THREAD

**Issue by mnmr** [microsoft/FASTER#364]
I am wondering why file sizes aren't available in Windows Explorer (or other tools to navigate the Windows file system). Only after the application exits are the real file size reported. For example, if the file size is 50kb at start, it will remain so until the application is stopped, at which point it will reflect the actual amount of data written (e.g. 1.5mb).

We always commit data written (using CommitAsync) after a batch of writes/enqueues complete.

The described behavior is identical across all tested ranges of PSB/MSB option values, but for reference this is how we create the store: 
```
            faster = new FasterLog(new FasterLogSettings
            {
                LogDevice = device, 
                ReadOnlyMode = readOnly, 
                MutableFraction = 0, 
                PageSizeBits = 15, 
                MemorySizeBits = 17, 
                SegmentSizeBits = 30
            });
```

**Comment by badrishc** [comment]
We don't update the file size metadata after every write, in order to avoid the overhead. You can preallocate the file to the segment size if you wish, by setting preallocateFile: true in the call to create the device.

**Comment by mnmr** [comment]
> We don't update the file size metadata after every write, in order to avoid the overhead.
Ah, that explains it. I was slightly worried that commit wasn't properly flushing to the file, because I couldn't see the writes being reflected. Is there perhaps a mechanism to periodically or forcefully update the metadata?

> You can preallocate the file to the segment size if you wish, by setting preallocateFile: true in the call to create the device.

I suppose using a smaller segment size would let us see when new segments are added, but I'm not too much of a fan of taking that path (we don't expect to save more than 100mb for a store, but will have thousands of them, so would like to save on the file handles).

**Comment by badrishc** [comment]
If you right click the file and check the size in properties, does it reflect the correct size?

**Comment by badrishc** [comment]
To clarify, we just use `WriteFile` Interop call on Windows (or standard .NET library call on non-Windows) which performs unbuffered overlapped I/O, so you are guaranteed that the data was flushed to disk.

This seems more like a caching behavior of directory info in explorer. For example, as mentioned above, if you right-click the file and check properties, the size is right (and the size in explorer also updates to the correct one once you perform this action!).

**Comment by mnmr** [comment]
Thank you for clarifying!
