### ISSUE TITLE
[C++] How to run ycsb workload for FASTER?

### ISSUE THREAD

**Issue by pentium3** [microsoft/FASTER#372]
As stated in https://github.com/microsoft/FASTER/tree/master/cc/benchmark-dir , I run ycsb basic and save its output to a file (named ycsbload in my case), and trying to run process_ycsb to convert YCSB "basic" output to the format we expect. But the process_ycsb get stuck and can not get any output. 

```
$ ./process_ycsb
Requires two arguments: file copied from, file copied to.
$ ./process_ycsb ycsbload ycsbload_fast

```

Do you have any idea about this issue? Thanks

**Comment by badrishc** [comment]
Try adding the following line right before calling `from_file.getline(buffer, sizeof(buffer))` (line 27)

```
from_file.clear();
```
