### ISSUE TITLE
how to use growIndex?

### ISSUE THREAD

**Issue by mstaros** [microsoft/FASTER#375]
What is the correct way of using growIndex? should all  the sessions be suspended beforehand?
And  if there is a possibility to grow memory?

**Comment by badrishc** [comment]
GrowIndex can be used while sessions are running, but this is not being tested, so it would be safer to do it with suspended sessions.

For the hybrid log, the memory allocation is pre-defined and cannot be changed dynamically. However you could checkpoint FASTER, kill the old instance, and recover a new instance with smaller hybrid log memory setting.

**Comment by mstaros** [comment]
> GrowIndex can be used while sessions are running, but this is not being tested, so it would be safer to do it with suspended sessions.
> 
> For the hybrid log, the memory allocation is pre-defined and cannot be changed dynamically. However you could checkpoint FASTER, kill the old instance, and recover a new instance with smaller hybrid log memory setting.

And how to wait for GrowIndex command to finish?
