### ISSUE TITLE
Can I use this on an asp.net core web garden (multi processes)

### ISSUE THREAD

**Issue by haiduong87** [microsoft/FASTER#376]
Hi,

Is this safe to use FASTER in a multi processes environment?
I'm looking for something to replace IMemoryCache

Thank you!

**Comment by badrishc** [comment]
Core FASTER is a library that works within the current process (embedded). We are working on remote FASTER that you can access across processes (via TCP). See here: https://github.com/microsoft/FASTER/issues/348
