### ISSUE TITLE
[C++] Error when running benchmark

### ISSUE THREAD

**Issue by pentium3** [microsoft/FASTER#383]
As stated in https://github.com/microsoft/FASTER/tree/master/cc/benchmark-dir , I run ycsb basic and save its output to a file (named ycsbload_basic / ycsbrun_basic in my case), and run process_ycsb to convert YCSB "basic" output to the format we expect(named ycsbload_fast / ycsbrun_fast in my case). but when I run benchmark, there is a error:

```
$ ./benchmark 0 1 ycsbload_fast ycsbrun_fast 
loading keys from ycsbload_fast into memory...
Init file load fail!
$ 
```

I found that was caused because the number of records does not match a pre-defined kInitCount = 250000000 (https://github.com/microsoft/FASTER/blob/master/cc/benchmark-dir/benchmark.cc#L365). Does it mean it only support workload with 250M records?

**Comment by badrishc** [comment]
You can update the benchmark code for your purposes, including the init and txn counts which are hardcoded there.
