### ISSUE TITLE
LogSettings bit sizes do not apply to ObjectLogDevice

### ISSUE THREAD

**Issue by plaisted** [microsoft/FASTER#390]
This is potentially "as designed" but I was completing some basic testing on the new helper functions for c# FASTER. The code looks similar to the following:

```csharp
        static Random rnd = new Random();
        static async Task<Guid> WriteFaster(int count, int size)
        {
            using var log = Devices.CreateLogDevice(@"c:\temp\iotest\hlog.log");
            using var objlog = Devices.CreateLogDevice(@"c:\temp\iotest\objlog.log");
            using var store = new FasterKV<int, byte[]>(1L << 20, new LogSettings { LogDevice = log, ObjectLogDevice = objlog });
            using var session = store.For(new SimpleFunctions<int, byte[]>()).NewSession<SimpleFunctions<int, byte[]>>();
            for (var i = 0; i < count; i++)
            {
                var bytes = new byte[size];
                rnd.NextBytes(bytes);
                session.Upsert(i, bytes);
            }

            await session.CompletePendingAsync();
            var checkpoint = await store.TakeFullCheckpointAsync(CheckpointType.Snapshot);
            await store.CompleteCheckpointAsync();
            return checkpoint.token;
        }
```

When using a large `size` I began having OOM issues. It appears that the memory settings only apply to the primary log, and ignore anything with the object log. For example using a `size` of 100000 (100 KB) I had to use the following settings `MemorySizeBits = 19, PageSizeBits = 16, SegmentSizeBits = 18` to keep memory usage ~5GB and objlog segment size to 1GB. In this example where the `byte[]` payload size is fixed this is easy to fix memory issues as the log to object log size ratio is constant. In a more real implementation, the byte[] size would fluctuate meaning larger than expected payloads would lead to much larger memory (and log segment sizes) than expected.

Is there any way to limit the total memory used by both the primary and object logs other than artificially setting a low primary log memory limit to force the object log to disk?

**Comment by badrishc** [comment]
FASTER does not really look at _what_ objects you are storing in the log. As far as FASTER is concerned, there is a page of pointers to user data (C# objects that can be of arbitrary size and change size over time as well). As a result, we are only able to control the size of the page of pointers.

If you want to control memory manually, you can always periodically call `store.Log.ShiftHeadAddress(newAddress, true)`. This will flush the log and corresponding objects to disk to get the memory utilization back to what you want.

If you have other suggestions, please feel free to drop them here.

**Comment by badrishc** [comment]
Also, if your values are just byte arrays, then you should use `Memory<byte>` as value type. That will completely eliminate the need for an object log, as all data will be directly placed on the main log. You will get much better performance as well.

See https://github.com/microsoft/FASTER/pull/354 for details.

**Comment by plaisted** [comment]
I ended up switching to the Memory<T> based implementation and everything worked as expected regarding memory use. In my case the performance didn't really change but I was probably IO bound.

I think it's worth adding a note to the documentation about the object log memory not being monitored by FASTER. It's a little unintuitive to me that FASTER is holding/managing the memory for the object log but ignores how much memory is used.

**Comment by badrishc** [comment]
Thanks, yes we will add this to docs. Re: performance, when you are IO bound, the memory(byte) solution might issue half as many IOs to storage. This is because with object log we have to first retrieve data from main log and then follow pointer to data from object log.
