### ISSUE TITLE
errno usage that should be under _DEBUG code

### ISSUE THREAD

**Issue by luiszun** [Microsoft/FASTER#4]
There are a few error conditions in src/environment/file_linux.cc that assign errno to a new int and then return without doing anything with it.

Those probably are there to see the errno with a debugger. I am assuming those should be behind an ifdef _DEBUG?

like this

```
    if(result == -1) {
#ifdef _DEBUG
      int error = errno;
#endif
      return Status::IOError;
    }
```

EDIT: Styling for the code block

**Comment by jahunter-m** [comment]
Yes, pretty much. Might be better to expose to the return Status; the host would probably find OS errno's useful...

**Comment by luiszun** [comment]
Are you accepting PRs?

**Comment by jahunter-m** [comment]
We are accepting PRs from contributors with signed CLAs; thanks.

One thing to keep in mind here is that we would like the C++ and C# versions to remain roughly in sync. Putting a _DEBUG around the assignment to int error, as you do above, is a change that's local to C++, and so it's safe to make. If we were to expose the error number to the return Status, then that change would have to be coordinated with the C# version as well (i.e., how does C# report file errors?).

**Comment by badrishc** [comment]
We don't plan to change the return status in FASTER C++ at this point, in order to maintain compatibility with C#.
