### ISSUE TITLE
Is this a bug? 

### ISSUE THREAD

**Issue by qq911712051** [microsoft/FASTER#400]
code in "cc/src/core/persistent_memory_malloc.h",  the code should use division here? 
<img width="1471" alt="image" src="https://user-images.githubusercontent.com/19927580/107140176-47a70280-695b-11eb-8299-488fe80cbb02.png">

**Comment by badrishc** [comment]
Sure looks like it.

**Comment by badrishc** [comment]
Fixed in master.
