### ISSUE TITLE
Questions: how to list all keys of KV and how to delete a key?

### ISSUE THREAD

**Issue by lanyusan** [microsoft/FASTER#404]
Hi, 
I am considering using FASTER KV for API call counter by hour, for example each key is `[apiId]_[startTimestamp]_[endTimestamp]`, value is call count incremented by each call. Then a scanner will run each hour to read last hour's statistics then delete those keys.

The scanner needs to list all the keys currently held by FASTER KV and delete the keys once data is pulled and stored in a statistic database. 

I couldn't find documentation for the two use cases.

Can some one give some advice? 

Thanks in advance.

**Comment by badrishc** [comment]
We have added the relevant documentation:

Listing all keys active in the database: https://microsoft.github.io/FASTER/docs/fasterkv-basics/#key-iteration
Delete a given key from the database: https://microsoft.github.io/FASTER/docs/fasterkv-basics/#delete

**Comment by badrishc** [comment]
Also, if you want to clear the entire database, it is much more efficient to simply shift the begin address to the tail. Begin address refers to the first active entry in the FASTER record log.

```cs
store.Log.ShiftBeginAddress(store.Log.TailAddress);
```

More details on log operations supported by FASTER: https://microsoft.github.io/FASTER/docs/fasterkv-basics/#log-operations

**Comment by lanyusan** [comment]
Very helpful. Thanks.
