### ISSUE TITLE
[C#] Is it okay to use faster instead of in-memory or distributed caches in net core mvc enviornment?

### ISSUE THREAD

**Issue by aloksharma1** [microsoft/FASTER#405]
Hello,

i am new to faster and i am mostly using memory cache or distributed cache in my general net core mvc projects, now i am implementing a layer of Redis and found out about faster while searching on same.

so here is my question can i replace in-memory or distributed caching completely with faster or such swapping is not good for web purposes, please advice.

here is what i am aiming for :
a L2 or L3 caching scenario with mem cached/ distributed--> Redis cached scenario (deep caching) 

thanks

**Comment by badrishc** [comment]
Yes, the use case sounds like a good fit for FASTER. Take a look at our samples and try it out to see if it meets your needs.
