### ISSUE TITLE
[C++] use customed key-value type

### ISSUE THREAD

**Issue by pentium3** [microsoft/FASTER#407]
Hi. In the current implementation I found that both keys and values are uint64_t.  https://github.com/microsoft/FASTER/blob/master/cc/benchmark-dir/benchmark.cc#L104

How could I modify to support 1KB string type value?

Thanks

**Comment by badrishc** [comment]
The test samples show how to use variable length keys and values. For example, see this one:

https://github.com/microsoft/FASTER/blob/c8bf594f0535db0c7dcd4337ee68248cfccd8ed1/cc/test/in_memory_test.cc#L322

You will need to modify the benchmark yourself to handle this along such lines.

**Comment by pentium3** [comment]
Thanks. Do you support user-defined key size as well?

**Comment by badrishc** [comment]
Yes, in the linked test page there is an example with custom keys.

**Comment by pentium3** [comment]
Thanks. Do you mena in this example? 

https://github.com/microsoft/FASTER/blob/c8bf594f0535db0c7dcd4337ee68248cfccd8ed1/cc/test/in_memory_test.cc#L1911


what's the difference between Key and ShallowKey in this case?

**Comment by badrishc** [comment]
Not sure, you need to go through all samples.

ShallowKey: https://github.com/microsoft/FASTER/pull/282
