### ISSUE TITLE
[C#] Object Log Truncation Behaviour

### ISSUE THREAD

**Issue by JeremyTCD** [microsoft/FASTER#410]
Hi! Object log devices don't truncate according to `capacity`. Also, reading records that should've been truncated return `OK` instead of `NOTFOUND`.

[Repro](https://github.com/JeremyTCD/Repro.Faster.ObjectLogTruncation) (usage: clone, build in vs, run)

Quick reference:

```cs
public class Program
{
    public static async Task Main()
    {
        // Cache directory
        string cacheDirectory = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "FasterCache");
        TryDeleteDirectory(cacheDirectory); // Clean up so previous runs don't affect current run

        // Settings
        string logFileName = "dummyLog";
        IDevice logDevice = Devices.CreateLogDevice(Path.Combine(cacheDirectory, $"{logFileName}.log"),
            // Same size as a segment (see log settings below)
            capacity: 4095);
        IDevice objectLogDevice = Devices.CreateLogDevice(Path.Combine(cacheDirectory, $"{logFileName}.obj.log"),
            // Same size as a segment (see log settings below)
            capacity: 4095);
        var logSettings = new LogSettings
        {
            LogDevice = logDevice,
            ObjectLogDevice = objectLogDevice,
            PageSizeBits = 9,
            MemorySizeBits = 10,
            // Same as device capacity (see log devices above)
            SegmentSizeBits = 12
        };

        // Store
        var fasterKVStore = new FasterKV<int, string>(1L << 20, logSettings);
        var session = fasterKVStore.For(new SimpleFunctions<int, string>()).NewSession<SimpleFunctions<int, string>>();

        // Execution
        int numRecords = 1000;
        Parallel.For(0, numRecords, key => session.Upsert(key, "dummyString"));

        // Log files
        IEnumerable<string> logFiles = Directory.EnumerateFiles(cacheDirectory, $"{logFileName}.log*");
        int numLogFiles = logFiles.Count();
        Console.WriteLine($"Expected num log files: 1, actual num log files: {numLogFiles}");

        // Object log files
        IEnumerable<string> objectLogFiles = Directory.EnumerateFiles(cacheDirectory, $"{logFileName}.obj.log*");
        int numObjectLogFiles = objectLogFiles.Count();
        Console.WriteLine($"\nExpected num object log files: 1, actual num object log files: {numObjectLogFiles}");

        // Print files
        Console.WriteLine($"\nLog files:");
        foreach (string file in logFiles)
        {
            Console.WriteLine("    " + Path.GetFileName(file));
        }
        Console.WriteLine($"\nObject log files:");
        foreach (string filePath in objectLogFiles)
        {
            Console.WriteLine("    " + Path.GetFileName(filePath));
        }

        // Try reading truncated record
        Console.WriteLine($"\nReading truncated record with key 0 ...");
        (Status status, string value) = (await session.ReadAsync(0).ConfigureAwait(false)).Complete();
        Console.WriteLine($"Status: {status}, Value: {value}"); // Status should be NOTFOUND
    }

    private static void TryDeleteDirectory(string directory)
    {
        try
        {
            Directory.Delete(directory, true);
        }
        catch
        {
            // Do nothing
        }
    }
}
```

Output:

```
Expected num log files: 1, actual num log files: 1

Expected num object log files: 1, actual num object log files: 6

Log files:
    dummyLog.log.5

Object log files:
    dummyLog.obj.log.0
    dummyLog.obj.log.1
    dummyLog.obj.log.2
    dummyLog.obj.log.3
    dummyLog.obj.log.4
    dummyLog.obj.log.5

Reading truncated record with key 0 ...
Status: OK, Value:
```

**Comment by badrishc** [comment]
Capacity should not be used to truncate the log. Instead, call ShiftBeginAddress (or call compaction with shift begin address to true).

**Comment by JeremyTCD** [comment]
Thanks for the quick response. I ended up moving to `SpanByte`.  Capacity based truncation seems to work for the main log (at least when it's local storage based), will double check.

https://github.com/microsoft/FASTER/blob/e163614dcee9a9a3e8f90bfe2599e7c78570f5fa/cs/src/core/Device/StorageDeviceBase.cs#L282-L289

**Comment by badrishc** [comment]
It is dangerous to use capacity to truncate, because the main index is not made aware of this. The main index considers items before BeginAddress to be deleted, and this variable needs to be updated. Otherwise, the system tries to access deleted files if the index or hash chain address corresponds to a deleted one, and behavior is unspecfied.

This is why ShiftBeginAddress is the right approach. It will also delete the old log part, at segment boundaries of course.

We might remove capacity in future in order to avoid users mistakenly use this to delete log without updating the index.

**Comment by badrishc** [comment]
Your SpanByte experiment sounds interesting. Let us know what you think of this vs object log. The other (safer) item to consider is our native support for Memory<byte>. There is a PR with the details of this as well.

**Comment by JeremyTCD** [comment]
> It is dangerous to use capacity to truncate, because the main index is not made aware of this

Ah I see okay. Stopped using `capacity` to truncate.  

I've implemented all [ObjLog](https://github.com/JeringTech/KeyValueStore/blob/main/src/KeyValueStore/AlternativeImplementations/ObjLog/ObjLogMixedStorageKVStore.cs), [Memory](https://github.com/JeringTech/KeyValueStore/blob/main/src/KeyValueStore/AlternativeImplementations/Memory/MemoryMixedStorageKVStore.cs) and [SpanByte](https://github.com/JeringTech/KeyValueStore/blob/main/src/KeyValueStore/MixedStorageKVStore.cs) key-value stores in [this repo](https://github.com/JeringTech/KeyValueStore).  

`SpanByte` implementation is significantly faster and allocates less than ObjLog for upserts.  

Am having trouble with reads though, both the `SpanByte` and `Memory` implementations are underwhelming (slower than ObjLog) and have extremely high standard deviations. I don't think it's my [benchmark](https://github.com/JeringTech/KeyValueStore/blob/main/perf/KeyValueStore/LowMemoryUsageBenchmarks.cs) logic since the ObjLog implementation runs fine. I've tried doing nothing with the result `IMemoryOwner` in my `ReadAsync` wrapper methods. Also tried the benchmarks with the latest Faster commits, neither attempt affected the results. Will open a new issue with details/repro soon.
