### ISSUE TITLE
Question: How do I use FASTER (C++) headers without filename collisions?

### ISSUE THREAD

**Issue by boinst** [microsoft/FASTER#412]
How do I use FASTER (C++) headers without filename collisions?

Sorry if this is a silly question. I have compiled the C++ version using CMake per [the build directions](https://microsoft.github.io/FASTER/docs/fasterkv-cpp/). Now I'm working on integrating it with my project. The [samples](https://github.com/microsoft/FASTER/blob/master/cc/playground/sum_store-dir/sum_store.h) include FASTER headers as follows: 

```
#include "core/faster.h"
#include "core/utility.h"
#include "device/file_system_disk.h"
```

Which is OK, but then "faster.h" includes a bunch of internal headers like "alloc.h" and "record.h" with no "core" or "device" prefix, as follows:

```
#include "alloc.h"
#include "record.h"
#include "guid.h"
```

Now surely this means I need the "core" and "device" header directories in my include paths? Surely the generic names like "alloc" and "record" have a strong risk of having the same name as another library or the same name as my own headers? Am I missing something obvious? Is this by design? The build system in my own project is Visual Studio C++, the intricacies of CMake are somewhat foreign to me.

Thanks sincerely in advance for any guidance you can provide.

**Comment by badrishc** [comment]
See this issue and PR, perhaps something similar would work?

* https://github.com/microsoft/FASTER/issues/266
* https://github.com/microsoft/FASTER/pull/276

**Comment by boinst** [comment]
Thank you @badrishc those linked issues are relevant, but not quite the same issue. In this case I'm concerned about the collision of the header filename rather than the symbol. If I have `"guid.h"` in my own code (I don't, this is hyperthetical), I won't be able to successfully compile against FASTER. The compiler will resolve one or the other header but not both.

**Comment by badrishc** [comment]
Any thoughts @dongx-psu ?

**Comment by dongx-psu** [comment]
I would put all faster header files under a directory called `faster`. And then include the upper-level directory as the root include directory. In this case, it forces you to add something like `faster/core/faster.h` in your program

**Comment by boinst** [comment]
Thank you @dongx-psu .

If I could include `faster/core/faster.h` as you suggest, that would be ideal.

I was surprised to find that when I `#include "faster/core/faster.h"`, then `guid.h` on [line 27](https://github.com/microsoft/FASTER/blob/97d768e53a61f6190e66a361765b8108631df7f7/cc/src/core/faster.h#L25) at least is correctly resolved. 

The first error I encounter is this one:

`1>persistent_memory_malloc.h(13,10): fatal error C1083: Cannot open include file: 'device/file_system_disk.h': No such file or directory`

That leads me to conclude that I still need to have the root `faster` directory in my include paths, and then I can include `core/faster.h`, but at least I don't need the `core`, `device`, etc sub-directories in my include paths. That's something, and that really resolves the larger fraction of my concern overall. Thank you for your guidance. Happy to close the ticket here if you're also happy.

**Comment by badrishc** [comment]
I think it can be closed.
