### ISSUE TITLE
[C#] Log Device Throttling Strategies

### ISSUE THREAD

**Issue by hiteshmadan** [microsoft/FASTER#432]
The device throttling done today in AllocatorBase assumes that the device is a consistent low latency device, that any spike in device load is a minor blip, and thus its a good idea to continually spin and keep hammer-retrying the throttle operation.

```
public void AsyncGetFromDisk(long fromLogical,
                        int numBytes,
                        AsyncIOContext<Key, Value> context,
                        SectorAlignedMemory result = default)
{
    if (epoch.ThisInstanceProtected()) // Do not spin for unprotected IO threads
    {
        while (device.Throttle())
        {
            device.TryComplete();
            Thread.Yield();
            epoch.ProtectAndDrain();
        }
    }
```
With remote stores mounted to a local file system that have higher latency, higher variability in latencies, and possibility for brownouts, this leads to CPU burn and eventual process hang. Without a backpressure signal to be given to incoming load, the fasterlog read/write requests just keep on piling up and hitting this throttle-yield spin loop.

A different throttling strategy appears necessary - one that does a limited number of retries and then gives up. Give up can either be via a Try* pattern where a boolean return value tells the FasterLog API caller that the operation failed, or via exceptions.

The alternative of FasterLog API callers doing their own throttling gates is pretty suboptimal due to a lack of insight into the current state of the device.

An equally important consideration is whether there are any read vs. write fairness issues with a common throttle method on the IDevice: Can an aggressive, high rate write load crowd out the readers ?

**Comment by badrishc** [comment]
As per recent PRs, `ManagedLocalStorageDevice` no longer uses spin-based throttling, but instead uses an async pool of handles, thereby mitigating this issue for that device.

`LocalStorageDevice` continues to use spin-based throttling as that allows us to saturate IOPS for extremely high-performance NVMe storage drives. You can disable the throttle limit by setting `device.ThrottleLimit` to `int.MaxValue`.

**Comment by hiteshmadan** [comment]
Yes, recent fixes have mitigated this issue already. Closing this issue out.
