### ISSUE TITLE
Is it possible to recovery operations that are after the last snapshot?

### ISSUE THREAD

**Issue by AnthonyLloyd** [Microsoft/FASTER#44]
Hi,

I've been experimenting and it seems you can only recover as at a snapshot token. It doesn't apply log items. Is this the case? Is it possible to recover more?

Many Thanks

**Comment by badrishc** [comment]
One could in theory recover all the persisted items in the hybrid log even after the last snapshot token, but the resulting recovered state would not be consistent with the following desirable property: "if operation X is persisted, then all operations before X in the input operation sequence are persisted as well (and none after)". The reason has to do with in-place updates in the mutable region of the hybrid log -- see Sec. 6.5 in this paper for a brief explanation: https://www.microsoft.com/en-us/research/uploads/prod/2018/03/faster-sigmod18.pdf

Do you have a scenario where the loss of this consistency property after recovery would be fine? Adding @gunaprsd as well.

**Comment by AnthonyLloyd** [comment]
Not really, just thinking that you have more data. I see this will make it difficult to know how up to date you are. Thanks
