### ISSUE TITLE
[C#] Version Wrap Around

### ISSUE THREAD

**Issue by tli2** [microsoft/FASTER#442]
FASTER record headers only have 13bits reserved for a version number, and therefore version numbers can wrap around. This can lead to a bug in the CPR state machine as operations check if record version is less than the session version to decide whether to read-copy-update. They could decide to in-place overwrite a v_new entry with an v_old entry during PREPARE phase when v_new < v_old due to a wrap around.

**Proposed fix:**
Change version checks from < to != across the code base. This results in some false positives where safe records maybe RCUed, but will always be correct.

**Mitigation:**
Version numbers elsewhere in FASTER has at least 7 bytes of resolution. We can write full resolution version numbers into each page header (max version in a page), and do not check per-record if  session_version > max_page_version

**Comment by badrishc** [comment]
Yes, rollover of checkpoint versions is a known limitation. This should not affect scenarios where operations do not overlap ongoing checkpoints at the time of version rollover. We will address this in the next update.
