### ISSUE TITLE
Question about SpanByte and Async methods

### ISSUE THREAD

**Issue by Tornhoof** [microsoft/FASTER#444]
If we use SpanByte it's required to have fixed input, how long does it need to be fixed, according to the comment for the full operation, is that correct? is the full operation until ``Complete()`` is called?
As fixed/unsafe code in general does not work with async, how is it supposed (if at all) work with async?

We can work around the async&unsafe problem by using code such as below, method ``ReadAsync`` which checks the result of the valueTask for completeness and calls an async method if not. But that breaks the fixed statement as far as I understand, as the pinning will be released at the end of the fixed block and that will be earlier than the ``Complete()`` statement in ``CompleteAsync()``.

So can we use SpanByte at all with async code, or should we just switch to SpanByteAndMemory for everything?
This means implementing our own ``SpanByteFunctions`` just for ``SpanByteAndMemory`` like in https://github.com/microsoft/FASTER/blob/9ef252702395ac3d2123044fa89dd54ef17e4aaa/cs/src/core/VarLen/SpanByteFunctions.cs#L74-L76
and probably deriving from FunctionBase directly and copying the current logic from SpanByteFunctions around.

As you're currently adding more async methods it appears that async is the way to go for new implementations?

```csharp
using System;
using System.Reflection.Metadata.Ecma335;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
using FASTER.core;

namespace FasterTest
{
    class Program
    {
        static async Task Main(string[] args)
        {
            using var cache = new Cache();
            cache.Upsert<long, long>(1, 2);
            var value = await cache.ReadAsync<long, long>(1);
        }
    }

    public sealed class Cache : IDisposable
    {
        private readonly IDevice _log;
        private readonly FasterKV<SpanByte, SpanByte> _store;
        private readonly CustomSpanByteFunctions _simpleFunctions = new();

        public Cache()
        {
            _log = Devices.CreateLogDevice("hlog.log", deleteOnClose: true);
            _store = new FasterKV<SpanByte, SpanByte>(1L << 20,
                new LogSettings
                {
                    LogDevice = _log,
                    ReadCacheSettings = new ReadCacheSettings(),
                });
        }

        public void Upsert<TKey, TValue>(TKey key, TValue value) where TKey : unmanaged where TValue : unmanaged
        {
            var session = GetSession();
            unsafe
            {
                var keySpan = MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref Unsafe.AsRef(key), 1));
                fixed (byte* _ = keySpan)
                {
                    SpanByte keySpanByte = SpanByte.FromFixedSpan(keySpan);
                    var dataSpan = MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref Unsafe.AsRef(value), 1));
                    fixed (byte* __ = dataSpan)
                    {
                        var dataSpanByte = SpanByte.FromFixedSpan(dataSpan);
                        session.Upsert(ref keySpanByte, ref dataSpanByte);
                    }

                }
            }
            ReleaseSession(session);
        }

        public ValueTask<TValue?> ReadAsync<TKey, TValue>(TKey key, CancellationToken cancellationToken = default)
            where TKey : unmanaged where TValue : unmanaged
        {
            TValue? result = default;
            var session = GetSession();
            unsafe
            {
                Span<byte> keySpan = MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref Unsafe.AsRef(key), 1));
                fixed (byte* _ = keySpan)
                {
                    SpanByte keySpanByte = SpanByte.FromFixedSpan(keySpan); // how long does it need to be fixed?
                    var tuple = session.ReadAsync(ref keySpanByte, token: cancellationToken);
                    if (tuple.IsCompletedSuccessfully)
                    {
                        var (status, memory) = tuple.Result.Complete();
                        if (status == Status.OK)
                        {
                            result = Deserialize<TValue>(memory);
                        }

                        ReleaseSession(session);
                    }
                    else
                    {
                        return CompleteAsync<TValue>(tuple, session);
                    }
                }
            }

            return new ValueTask<TValue?>(result);
        }

        private TValue? Deserialize<TValue>(SpanByteAndMemory memory) where TValue : struct
        {
            var span = memory.IsSpanByte ? memory.SpanByte.AsSpan() : memory.Memory.Memory.Span;
            if (MemoryMarshal.TryRead<TValue>(span, out var value))
            {
                return value;
            }

            memory.Memory?.Dispose();
            return default;
        }

        private async ValueTask<TValue?> CompleteAsync<TValue>(ValueTask<FasterKV<SpanByte, SpanByte>.ReadAsyncResult<SpanByte, SpanByteAndMemory, Empty>> valueTask,
            ClientSession<SpanByte, SpanByte, SpanByte, SpanByteAndMemory, Empty, CustomSpanByteFunctions> session) where TValue : struct
        {
            try
            {
                var readAsyncResult = await valueTask.ConfigureAwait(false);
                var (status, memory) = readAsyncResult.Complete();
                ReleaseSession(session);
                return status == Status.OK ? Deserialize<TValue>(memory) : default(TValue?);
            }
            catch
            {
                session.Dispose();
                return default;
            }
        }

        private ClientSession<SpanByte, SpanByte, SpanByte, SpanByteAndMemory, Empty, CustomSpanByteFunctions> GetSession()
        {
            var session = _store.For(_simpleFunctions).NewSession<CustomSpanByteFunctions>();
            return session;
        }

        private void ReleaseSession(
            ClientSession<SpanByte, SpanByte, SpanByte, SpanByteAndMemory, Empty, CustomSpanByteFunctions> session)
        {
            session.Dispose();
        }


        public void Dispose()
        {
            _log.Dispose();
            _store.Dispose();
        }

        private sealed class CustomSpanByteFunctions : SpanByteFunctions<Empty>
        {
        }
    }

}

```

**Comment by badrishc** [comment]
>If we use SpanByte it's required to have fixed input, how long does it need to be fixed, according to the comment for the full operation, is that correct? is the full operation until Complete() is called?

Data only needs to be fixed until the operation comes back from the initial call. When an operation goes pending, we copy the data to an internal buffer before returning control to you, so you no longer need it fixed.

Note that if key/value are value-types on the stack (not heap) then you may not need to pin them at all.

**Comment by badrishc** [comment]
> So can we use SpanByte at all with async code, or should we just switch to SpanByteAndMemory for everything?

If you are having trouble with fixing and pinning, you can also use `Memory<byte>` as value and `ReadOnlyMemory<byte>` as key. See this for a sample: https://github.com/microsoft/FASTER/blob/9ef252702395ac3d2123044fa89dd54ef17e4aaa/cs/samples/StoreVarLenTypes/Program.cs#L37

**Comment by badrishc** [comment]
> As you're currently adding more async methods it appears that async is the way to go for new implementations?

Not necessarily. It depends on your performance targets. C# async gives ease of usablity, but comes at some performance cost. We support both, and async methods are using sync methods under the hood so the sync API isn't going away anywhere.

**Comment by Tornhoof** [comment]
Thank you very much for your detailed answers.

> Data only needs to be fixed until the operation comes back from the initial call. When an operation goes pending, we copy the data to an internal buffer before returning control to you, so you no longer need it fixed.

Ah great, then looks like I'm fine with my current approach.

> Not necessarily. It depends on your performance targets. C# async gives ease of usablity, but comes at some performance cost. We support both, and async methods are using sync methods under the hood so the sync API isn't going away anywhere.

Thanks, that leaves more options open for me.
