### ISSUE TITLE
Wrapper for JVM languages

### ISSUE THREAD

**Issue by amit2103** [microsoft/FASTER#445]
Hi, 

Thanks for the awesome library, are there any plans to create a wrapper for the JVM languages like Java  or Scala ?
Since RocksDB is used in a lot of the projects, I was thinking that, FASTER can be used in a lot of the scenarios with better results.

Regards

**Comment by badrishc** [comment]
That would be useful, but we have no plans to create one at the moment. Contributions are welcome. Someone created a rust wrapper for FASTER C++ here: https://github.com/faster-rs/faster-rs

**Comment by amit2103** [comment]
Thanks let me try if I can do a port for the C++ version via JNA
