### ISSUE TITLE
KV performance characteristics for 100% reads

### ISSUE THREAD

**Issue by edsvisinditus** [microsoft/FASTER#448]
Hi,

I am considering using FASTER in a scenario where all data will be loaded into the FASTER KV store on application start. After this point only read operations will be executed against the KV store.

It seems that FASTER fares pretty well in these 100% read scenarios (page 10): https://www.microsoft.com/en-us/research/uploads/prod/2018/03/faster-sigmod18.pdf

However I was wondering what are the performance characteristics of FASTER in a 100% read situation, when the amount of data exceeds the amount of available memory resulting in reads from the disk? 

Is FASTER still expected to compare favorably with other solutions in this scenario? Or is FASTER perhaps not even the right tool for this kind of use case?

Thank you in advance.

**Comment by badrishc** [comment]
FASTER should work great in this situation. It will simply saturate the IOPS (random IO capability) of the underlying device, and throughput will depend on this.

Further, if there won't be further upserts, you can eliminate the main log from main memory entirely (FlushAndEvict). Also, you can provision a read cache to hold the read-hot data (feature in C#, being ported to C++).

**Comment by edsvisinditus** [comment]
Hi Badrish,

Thank you, this is great advice! 

I’ve been playing around with evicting the main log from memory and it seems to work well.

I will definitely give the read cache a try. To maximize performance, should I simply increase the MemorySizeBits read cache setting to consume all of the memory of the host (of course taking into account the memory required for the hash index)?

Also as I am storing objects I am using a separate object log. Am I correct in assuming that entries from the object log won’t be stored in the read cache?
