### ISSUE TITLE
[c++] do we have IO stat information in FASTER?

### ISSUE THREAD

**Issue by pentium3** [microsoft/FASTER#453]
Hi. Could I get low level disk I/O informations such as `block reads`, `block cache hits`, `read-bytes`, `write-bytes` from FASTER? 

like this type of report provided by rocksdb:  https://github.com/facebook/rocksdb/issues/6448

**Comment by badrishc** [comment]
Not out of the box. You can instrument the device API to add metrics that you care about. Just need to keep it low overhead so as to not affect performance.
