### ISSUE TITLE
[QUESTION] FasterLog and Raft

### ISSUE THREAD

**Issue by sakno** [microsoft/FASTER#461]
Hello,

I'm author of [.NEXT](https://sakno.github.io/dotNext/) library that provides fully-featured implementation of Raft consensus protocol for building clustered microservices with ASP.NET Core. The library contains implementation of [persistent Write-Ahead Log](https://github.com/sakno/dotNext/blob/develop/src/cluster/DotNext.Net.Cluster/Net/Cluster/Consensus/Raft/PersistentState.cs) for Raft. Some developers use the library for building real-world applications and asked me about performance of WAL shipped out-of-the-box. Currently, it's not good as FasterLog for some reasons. That's why I would like to evaluate usage of FasterLog as a replacement of my current implementation.

## Q1: Accessing by index
WAL from .NEXT addresses log entries by their index. FasterLog uses logical address for accessing log entries. What is the best way to convert index to logical address and vice versa in FastLog? Do I need to keep some mapping cache for that?

## Q2: Committing of log entries
Both implementations have similar behavior of commit procedure. However, WAL from .NEXT can commit log entries up to the specific index which is required by Raft. In FasterLog a whole head must be committed. How I can specify the logical address for the commit?

## Q3: Dropping uncommitted entries
WAL from .NEXT allows to drop uncommitted log entries from the head. How I can do the same thing in FasterLog? Is `TruncateUntil` method the right to do that?

## Q4: Concurrent access
WAL from .NEXT thread-safety is guaranteed by the custom async lock:
* Multiple readers can co-exist in the same time without blocking. This allows to do replication process with cluster members in parallel.
* Write lock is mutually exclusive with read lock
* Compaction lock can co-exist with write lock because compaction works with the head of WAL and writes always incremental and require access to the tail. As a result, writes can be done in parallel with log compaction.

How the concurrency is organized in FasterLog? Is it possible to remove data from the tail while appending new data to the head? Also, I saw that you have head iterator. How it works in situations when I'm reading data from the tail while removing data from the tail in the same time?

## Q5: Log compaction
I'm using log snapshotting as an approach to log compaction. It means that some committed log entries in the tail can be squashed to a single one and stored as a snapshot log entry. I prefer to store snapshot in separated file. How I can remove committed log entries from the tail in parallel with writes to the head in FasterLog?

## Q6: Reading entries
Does FasterLog allow to read uncommitted entries? Maybe I missed something, but `ReadAsync` requires logical address. And how to read the specific range of log entries instead of reading to the end of the log?

Thanks in advance for any advice!

**Comment by badrishc** [comment]
> What is the best way to convert index to logical address and vice versa in FastLog?

FasterLog exposes logical addresses, so if you want to access via record id, then you would need to maintain a map. `FasterKV` is one way to achieve this, but you can implement your own mapping table on top.

Thinking aloud, an alternative to using `FasterLog` could be to use `FasterKV` directly, with a monotonic `index` as key. The `FasterKV` fold-over checkpointing technique actually commits the log similarly. You would enqueue entries using the `Upsert` API, use a small memory size, and call `TakeHybridLogCheckpoint` in lieu of commit. To iterate entries you would just use the log iterator API.

> How I can specify the logical address for the commit?

Commit internally calls `allocator.ShiftReadOnlyToTail` [here](https://github.com/microsoft/FASTER/blob/4a993d149dc7f6311b66cd90d1dabe301f2c9a23/cs/src/core/Index/FasterLog/FasterLog.cs#L1213). This would need to instead use `allocator.ShiftReadOnlyAddress(long shiftUntil)`. It is not exposed but I can easily imagine adding an overload for this.

> drop uncommitted log entries from the tail

You mean there might be uncommitted recent entries at the tail that you do not want to flush to log? An enqueue of a record means that you want to commit it, so a commit thread might be committing it in parallel. One way is to simply kill and restore the FasterLog as uncommitted entries will be lost that way. Or perhaps you can iterate into these entries and invalidate them at application level (but they might be getting committed simultaneously by the commit thread, you need to handle that).

> concurrent access

`FASTER` achieves thread safety using latch-free algorithms and epoch protection, details are in our papers. This information is not necessary as user of our API, though, as it is internal to the system. See a recent video explaining this [here](https://youtu.be/4Y0oNFud-VA).

> How I can remove committed log entries from the head in parallel with writes to the tail in FasterLog?

It should be safe to call `TruncateUntil` to remove committed entries, in parallel to concurrent enqueues into the log.

> Does FasterLog allow to read uncommitted entries? Maybe I missed something, but ReadAsync requires logical address.

You can iterate uncommitted entries, see [here](https://microsoft.github.io/FASTER/docs/fasterlog-basics/#iteration-for-uncommitted-data-publishsubscribe) for docs. `ReadAsync` is not useful here, it is used only if you want to random-access a particular entry with known address in the log.

> And how to read the specific range of log entries instead of reading to the end of the log?

It can be done using `log.Scan` -- which takes the end address as an argument. See the docs linked above.

**Comment by sakno** [comment]
> You mean there might be uncommitted recent entries at the tail that you do not want to flush to log?

It was a typo. From the head of course. By tail I meant only committed log entries.

> An enqueue of a record means that you want to commit it

Not in Raft. Commit is a process executing when the majority of cluster nodes confirm that the range of log entries are added in uncommitted state. The erasure of head can be caused by crash of leader. In this case, uncommitted entries may be rewritten by another leader in the cluster. Raft uses a technique similar to _two-phase commit_ in this case.

> One way is to simply kill and restore the FasterLog as uncommitted entries will be lost that way

Such an approach looks problematic for me. I need to introduce additional synchronization. Also, I think that destruction and re-creation of FasterLog is not cheap. Moreover, this operation cannot be done in parallel with log compaction.

Anyway, many thanks for your answers. I'll continue the evaluation.

**Comment by badrishc** [comment]
Hmm, I see. You can add the uncommitted entries to FasterLog and make sure you do not call Commit. Hold on to the physical addresses of the log records. If two-phase succeeds then call Commit. If not, mark them as invalid, or if that is not acceptable then you atomically move TailAddress back to CommittedUntilAddress. This is not doable with external-facing API though (it could be exposed to user, I guess, as a Rollback operation).

Another thought is to maintain a separate uncommitted log, and move the records to the main log after two-phase. This might create synchronization issues.

**Comment by sakno** [comment]
> You can add the uncommitted entries to FasterLog

That is problematic too. According to FasterLog docs, the commit can be forced by the log itself if the pages gets filled up.

**Comment by badrishc** [comment]
> > You can add the uncommitted entries to FasterLog
> 
> That is problematic too. According to FasterLog docs, the commit can be forced by the log itself if the page gets filled up.

Not if you size the page appropriately, have enough pages in memory to hold the uncommitted data, and increase the `MutableFraction` setting so that every page does not immediately commit. See https://microsoft.github.io/FASTER/docs/fasterlog-tuning/ for details.

**Comment by badrishc** [comment]
Basically, by setting `MutableFraction` to 1, FASTER will not flush any page until the entire in-memory buffer is full (i.e., you have 2<sup>MemorySizeBits</sup> worth of uncommitted pages). Using this with a sufficiently large memory buffer, you can issue enqueues into `FasterLog` that will stay in memory and not get flushed automatically. Then, when you are ready to commit, you call `Commit` which will flush to disk and commit everything.

I am closing this issue for now. Feel free to re-open if you run into any issues.
