### ISSUE TITLE
tuning FASTER parameters in c++

### ISSUE THREAD

**Issue by pentium3** [microsoft/FASTER#464]
In https://microsoft.github.io/FASTER/docs/fasterkv-tuning/ , the page mentioned that we can change many parameters like `PageSizeBits` by `LogSettings` . But it is seems for C# only. How could we do the same in c++?

**Comment by badrishc** [comment]
Yes,  you have to get into the source code to change these constants in C++. Look for kPageSize in persistent_memory_malloc.h for example.
