### ISSUE TITLE
Retrieve variable length key in log scan

### ISSUE THREAD

**Issue by timothycoleman** [microsoft/FASTER#476]
EDIT: i see, the code below does work if i change the `GetKey` call to use `ref` instead of copying the spanbyte... although its not completely clear to me why that would be

ORIGINAL:
I'm getting a behaviour that I don't understand in the code below. I'm trying to obtain my variable length key during a log scan but it appears to only have the first part of it. Am I making a mistake here? Thanks!

```
    [TestFixture]
    internal class ReproSpanByteKeyStorage
    {
        class Functions : FunctionsBase<SpanByte, long, long, long, Empty>
        {
        }

        [Test]
        public unsafe void Repro()
        {
            var log = Devices.CreateLogDevice(TestContext.CurrentContext.TestDirectory + "/BasicFasterTests.log", deleteOnClose: true);
            var fht = new FasterKV<SpanByte, long>(
                size: 1L << 27,
                new LogSettings
                {
                    LogDevice = log,
                    MemorySizeBits = 15,
                    PageSizeBits = 12,
                });
            var session = fht.For(new Functions()).NewSession<Functions>();

            void Write(string keyString, long value)
            {
                var key = MemoryMarshal.Cast<char, byte>(keyString.AsSpan());
                fixed (byte* _ = key)
                {
                    var sb = SpanByte.FromFixedSpan(key);
                    Assert.AreEqual(Status.OK, session.Upsert(sb, value));
                }
            }

            void ReadKeyFromIter(string expectedKey, IFasterScanIterator<SpanByte, long> iter)
            {
                Assert.True(iter.GetNext(out var recordInfo));
                var key = iter.GetKey();
                var span = key.AsReadOnlySpan();
                var chars = MemoryMarshal.Cast<byte, char>(span);
                var s = new string(chars);
                Assert.AreEqual(expectedKey, s);
            }

            // write a couple of keys
            var shortKey = "abcde";
            var longerKey = "abcdefghijklmnopqrstuv";
            Write(shortKey, 1);
            Write(longerKey, 2);

            // try to find keys when iterating
            using var iter = fht.Log.Scan(0, fht.Log.TailAddress);

            // finds short key no problem
            ReadKeyFromIter(shortKey, iter);

            // fails to find longer key:
            /* String lengths are both 22. Strings differ at index 6.
               Expected: "abcdefghijklmnopqrstuv"
               But was:  "abcdef\u0001\0\0\f팘鲊ǃ\0\udf80ᢿ\u0092\0\udf90ᢿ\u0092\0"
             */
            ReadKeyFromIter(longerKey, iter);
        }
    }
```

**Comment by badrishc** [comment]
The behavior you notice is as expected. Details follow:

`SpanByte` is an unsafe type that -- in serialized form -- slaps a C# `struct` type over a variable-length sequence of bytes in memory. The compile-time size of this struct is fixed. When you pass it without `ref`, because it is treated as a value type, the runtime will copy over only the fixed header of the struct. On the other hand, `ref` types are like pointers so they continue to reference the original full value.

**Comment by timothycoleman** [comment]
Ahh I see. When I had a quick look I thought the payload field was a pointer to the payload, and therefore I was expecting it to copy no problem and still reference the same data

```
[FieldOffset(4)]
private IntPtr payload;
```

However, looking more closely and from your explanation I see that it actually is the beginning of the payload it self.

Thanks for the pointer (so to speak..) it all makes sense now

**Comment by badrishc** [comment]
`SpanByte` is a variant type: when you create it initially, it is in unserialized form, and there it is indeed stored as you describe (length and pointer to payload). However,  inside Faster it gets stored as its serialized equivalent but using the same structure. When we return data from Faster,  we retain the serialized form,  which is what you are seeing.

**Comment by timothycoleman** [comment]
got it, thanks again for your help (and excellent project!)
