### ISSUE TITLE
AzureStorageNamedDeviceFactory doesn't find commit files

### ISSUE THREAD

**Issue by smolatom** [microsoft/FASTER#478]
[This foreach loop](https://github.com/microsoft/FASTER/blob/9ef252702395ac3d2123044fa89dd54ef17e4aaa/cs/src/devices/AzureStorageDevice/AzureStorageNamedDeviceFactory.cs#L94) ignores the input parameter `path` and hence, in my opinion, cannot locate the commit files. The opinion is supported by [this method](https://github.com/microsoft/FASTER/blob/9ef252702395ac3d2123044fa89dd54ef17e4aaa/cs/src/core/Index/CheckpointManagement/DeviceLogCommitCheckpointManager.cs#L106), which is, as far as I understand it, supposed to list commit files looking into a subdirectory `log-commits`.

I expect that the structure of blobs and directories in a blob container is similar to the local storage implementation:
```
+ base (directory)
--+ segment.0 (blob)
--+ log-commits (directory)
-----+ commit.0.0 (blob)
```

As it is ignoring `path`, it is actually looking into `base` instead of `log-commits` and returns segment blobs.

If I change [this line](https://github.com/microsoft/FASTER/blob/9ef252702395ac3d2123044fa89dd54ef17e4aaa/cs/src/devices/AzureStorageDevice/AzureStorageNamedDeviceFactory.cs#L94) to `foreach (var entry in baseRef.GetDirectoryReference(path).ListBlobs().Where(b => b as CloudPageBlob != null)` it works like charm.

The below code is what I do to create an Azure based FasterLog instance.
```
var device = new AzureStorageDevice(connectionString, containerName, directoryName, blobName);

var deviceFactory = new AzureStorageNamedDeviceFactory(connectionString);
var checkpointNamingScheme = new DefaultCheckpointNamingScheme($"{containerName}/{directoryName}");
var logCommitManager = new DeviceLogCommitCheckpointManager(
    deviceFactory,
    checkpointNamingScheme);

_log = new FasterLog(new FasterLogSettings { LogDevice = device, LogCommitManager = logCommitManager });
```

**Comment by badrishc** [comment]
Thank you for the catch. The linked PR fixes it.
