### ISSUE TITLE
[C++] The implementation of LightEpoch may have a bug

### ISSUE THREAD

**Issue by qq911712051** [microsoft/FASTER#481]
file path:  cc/src/core/light_epoch.h
description:
    I recently used LightEpoch as an asynchronous framework, but i found some action will be executed before other thread  "StopSession",  then i found a bug in source-code:
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/19927580/119591850-f3406980-be09-11eb-9f4f-246f6e273913.png">
and the above counts from 0,  but when you calculate "safe_to_reclaim_epoch", you do start from 1.
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/19927580/119592036-4e725c00-be0a-11eb-8763-5ea920698880.png">

**Comment by qq911712051** [comment]
I’m curious, why didn’t you trigger this bug when you tested?

**Comment by badrishc** [comment]
The main thread has ID 0, and we generally do not perform operations on this thread. This may be the reason it has not manifested in the past. We will look into it and fix.
