### ISSUE TITLE
[Question] what will be happened when logical address overflow in FasterLog?

### ISSUE THREAD

**Issue by itn3000** [microsoft/FASTER#493]
Currently, logical address(used in `Scan` or other) seems to be increased monotonically when adding data in FasterLog.
Therefore, logical address overflow will be happened in (distant?)future.

I don't know what will be happened and what I should do(or no problem?) in FasterLog when overflow.
Is there a documentation about it?

**Comment by badrishc** [comment]
It is 64-bit long so we would not have an issue for a really long time. We might move to 128-bit by then. If necessary it might also be easy to work around by killing process and adjusting the address space via recovery metadata to re-start at zero (BeginAddress). Or we could add rollover logic. But this seems unnecessary given the availability of 64 bits.

**Comment by itn3000** [comment]
Thank you for responding, I understand.
