### ISSUE TITLE
[C#] Growing Values in RMW operations

### ISSUE THREAD

**Issue by pablofrommars** [microsoft/FASTER#512]
Similar to the problem described in #136. It would useful to be able to increase/modify the size of values during RMW operations. IFunctions.CopyUpdater allocates the size of newValue equals to the size of the old value.

Looks like the c++ port has support for the feature (#145), Is there a workaround for c#?

Thanks to anyone involved!

**Comment by badrishc** [comment]
This is already supported. The basic idea is:
1. Return `false` from `InPlaceUpdater`
2. FASTER will call `GetLength` (provided via `SessionVariableLengthStructSettings` parameter to `NewSession`) to get the size of the new value given the old value and the input.
3. FASTER will allocate this (larger) length, and call `CopyUpdater` with new value of this length.

See example here: https://github.com/microsoft/FASTER/blob/master/cs/samples/StoreVarLenTypes/AsciiSumSample.cs

**Comment by pablofrommars** [comment]
That's great news for my use case.

Thank you so much for the lightning fast support.
