### ISSUE TITLE
Performance comparison with ConcurrentDictionary

### ISSUE THREAD

**Issue by kamikyo** [microsoft/FASTER#538]
Here is my BenchmarkDotnet code:
```
[MemoryDiagnoser]
[Config(typeof(DontForceGcCollectionsConfig))]
public class FasterTest
{
    [Params((int)1E+2, (int)1E+3, (int)1E+4, (int)1E+5, (int)1E+6)]
    public int GetCount { get; set; }

    public ConcurrentDictionary<string, LocData> cdic;
    public FasterKV<string, LocData> faster;
    public ClientSession<string, LocData, LocData, LocData, Empty, IFunctions<string, LocData, LocData, LocData, Empty>> session;

    [GlobalSetup]
    public void GlobalSetup()
    {
        cdic = new ConcurrentDictionary<string, LocData>();
        faster = new FasterKV<string, LocData>(1L << 20, new LogSettings { LogDevice = new NullDevice(), ObjectLogDevice = new NullDevice() });

        session = faster.NewSession(new SimpleFunctions<string, LocData>((a, b) => a));
    }

    [Benchmark]
    public void CDIC()
    {
        Random random = new Random();
        LocData d = new LocData();
        cdic.AddOrUpdate(random.Next(GetCount).ToString(), new LocData(), (k, v) => d);
    }

    [Benchmark]
    public void Faster()
    {
        Random random = new Random();
        string key = random.Next(GetCount).ToString();
        LocData d = new LocData();
        session.RMW(ref key, ref d);
    }
}
```

LocData like this:
`public class LocData { }`

This is the final run out result
![image](https://user-images.githubusercontent.com/7645337/128288728-2c8e599d-d98d-467b-8279-a1472853a2fe.png)

As you can see, there is not much difference in write performance between the two.
Therefore, is it because I am not using FASTER correctly?

**Comment by badrishc** [comment]
First of all, using C# classes as key or value types makes everything slow and dependent on GC, resulting in lesser differences.  Second,  FASTER is a full fledged key value store with recovery and larger than memory support. Third, see this article for how to properly compare the two: https://github.com/Microsoft/FASTER/wiki/Performance-of-FASTER-in-C%23

**Comment by kamikyo** [comment]
Thank you for your reply, it made me learn a lot
