### ISSUE TITLE
Make the intro more palatable to business people

### ISSUE THREAD

**Issue by lynxnathan** [Microsoft/FASTER#6]
> What differentiates FASTER are its cache-optimized index that achieves very high performance — up to 160 million operations per second when data fits in memory; 

Where?

I too can make magic given enough resources. I propose making clear on the readme where this tool can aggregate value, specifically on the context given by this issue's title.

**Comment by cryptoquick** [comment]
This repo is woefully under-documented.

**Comment by lynxnathan** [comment]
Also be aware that "its unique “hybrid record log” design to 160 million operations per second when data fits in memory", if I'm reading correctly, should use the term "designed to". 

But most importantly, if this is to be used by the industry and receive the benefits thereof, make sure you are selling this as it should.

**Comment by lynxnathan** [comment]
Not trying to be de A*HOLE in the bunch either BTW. I see you guys are trying to make the effort to make this public. So make it compelling.

I mean, we all are going to be making a dime on this, right? 😃

**Comment by badrishc** [comment]
Thanks for the feedback. We do plan to update the README and add wiki pages. In the meantime, read our paper at https://www.microsoft.com/en-us/research/uploads/prod/2018/03/faster-sigmod18.pdf for performance specifics.

**Comment by Tanachha** [comment]
This correct plan

**Comment by treenew** [comment]
man up

**Comment by badrishc** [comment]
Intro updated, wiki pages being added.
