### ISSUE TITLE
[C#] FasterLogIterator.CompleteUntilRecordAt() should not verify checksum of the record, even if checksumming is enabled

### ISSUE THREAD

**Issue by mito-csod** [microsoft/FASTER#601]
CompleteUntilRecordAt() currently fails occasionally due to checksum failures. This is because the AsyncGetHeaderOnlyFromDiskCallback method reads only enough data in to capture the header. The solution is to never verify checksum in GetRecordLengthAndFree()--this should be "safe" since this method is not used to retrieve records themselves.

**Comment by badrishc** [comment]
Makes sense, merged PR.
