### ISSUE TITLE
old segment file is not deleted even if truncated in FasterLog.

### ISSUE THREAD

**Issue by itn3000** [microsoft/FASTER#626]
# Overview

some segment files are not deleted in another session.
This leads some garbage files are remained if app is rebooted.

# Environment

* dotnet 6.0(dotnet-sdk-6.0)
* Microsoft.FASTER.Core 1.9.10
* Windows 11 x64

# Steps to reproduce

1. open IDevice with `Devices.CreateLogDevice` and create `FasterLog`
2. insert logs so that multiple segment files are created
3. close FasterLog and IDevice
4. open IDevice and FasterLog with same options as previous
5. Truncating with `FasterLog.TruncateUntil(FasterLog.TailAddress)`
6. close FasterLog and IDevice

test code is https://gist.github.com/itn3000/5cbfd41d166ae41173a45d5d4792c03e

# Expected

There is only last segment file after truncating

# Actual

All segment files are existing after truncating.

**Comment by itn3000** [comment]
When truncated in same session, old segment files are deleted.

**Comment by badrishc** [comment]
Thanks for the details and repro. The truncation algorithm was only deleting segments whose handles it had cached in memory. The linked PR should fix this.
