### ISSUE TITLE
CheckpointSettings.RemoveOutdated does not remove checkpoints between recoveries

### ISSUE THREAD

**Issue by dhhoang** [microsoft/FASTER#651]
I've been testing FasterKV with `CheckpointSettings.RemoveOutdated` set to true to avoid polluting the directory. So far it seems like this will only remove checkpoints within  one lifetime of `FasterKV`. If my application restarts and re-create `FasterKV`, the old checkpoints are not removed.
So I tried to delete the checkpoint after recovering, and it seems to work:
```csharp
var store = new FasterKV(...);
store.Recover();
if(Directory.Exists(checkpoint_dir)){
   Directory.Delete(checkpoint_dir, recursive:true);
}
```
My question is: is it a safe thing to do? Will it impact the correctness of the `FasterKV` store?

**Comment by badrishc** [comment]
We need to retain the last checkpoint, as it would be needed for recovery in case the application crashed immediately after calling Recover(). During recovery, we delete all checkpoints except the one we just recovered to, for this reason.

**Comment by badrishc** [comment]
When you recreate FASTER during recovery, are you making sure you set RemoveOutdated to true on that instance of FASTER? The code [here](https://github.com/microsoft/FASTER/blob/aa440882740422ed61c7b54b87d9e97ee8bb30f4/cs/src/core/Index/CheckpointManagement/DeviceLogCommitCheckpointManager.cs#L390) deletes all unrelated checkpoints during recovery, so if you are not seeing this behavior a stand alone repro would be good.

**Comment by dhhoang** [comment]
Ok, I managed to narrow down the issue:
* Calling `store.Recover()` removes the old checkpoint directories
* Calling `store.RecoverAsync()` does not.

Reprod code (run this 5 times and look at the check point directory):
```csharp
class Program
{
    public static async Task Main(string[] args)
    {
        var storeDir = "C:\\path\\to\\test\\dir";
        var checkpointDir = Path.Combine(storeDir, "checkpoint");
        using var log = Devices.CreateLogDevice(Path.Combine(storeDir, "hlog.log")); // backing storage device
        using var store = new FasterKV<long, long>(
            1L << 20, // hash table size (number of 64-byte buckets)
            new LogSettings
            {
                LogDevice = log,
                MemorySizeBits = 9,
                PageSizeBits = 9
            }, // log settings (devices, page size, memory size, etc.)
            new CheckpointSettings
            {
                CheckpointDir = Path.Combine(storeDir, "checkpoint"),
                RemoveOutdated = true
            }
        );
        if (Directory.Exists(checkpointDir))
        {
            await store.RecoverAsync();
        }

        // Create a session per sequence of interactions with FASTER
        // We use default callback functions with a custom merger: RMW merges input by adding it to value
        using var s = store.NewSession(new SimpleFunctions<long, long>((a, b) => a + b));
        long key = 1, value = 1, output = 0;

        // Upsert and Read
        s.Upsert(ref key, ref value);
        s.Read(ref key, ref output);
        Debug.Assert(output == value);

        Console.WriteLine("Success!");
        await store.TakeFullCheckpointAsync(CheckpointType.FoldOver);
    }
}
```

**Comment by badrishc** [comment]
Thanks for pointing out this divergence - we have fixed the isssue in latest on master branch.
