### ISSUE TITLE
Faster Remote Sample code for asp.net core projects?

### ISSUE THREAD

**Issue by aloksharma1** [microsoft/FASTER#680]
Hello, 
i want to use faster remote for server webfarm scenario (multi-processor), but i cant find any samples for that in repo. Also i am using asp.net core so if you have any minimal repo for that it would be greatly appreciated.

thanks

**Comment by badrishc** [comment]
We dont have any specific examples for asp.net core, but the stuff in https://github.com/microsoft/FASTER/tree/main/cs/remote/samples can help you get started. Feel free to contribute examples back if you create some.

**Comment by aloksharma1** [comment]
ok, the thing with new asp is dependency injection. what do you think i should use for Faster Cache KV, singleton or scoped? i will surely build a PR sample once everything starts working as i want.

**Comment by aloksharma1** [comment]
> Asp.net older version here, we use singleton

thanks for the input

**Comment by aloksharma1** [comment]
@badrishc back again with a few questions regarding implementation i am doing:
1. does faster have a cache expiry time like .net in-memory cache (docs [MemoryCacheEntryOptions](https://docs.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-6.0#memorycacheentryoptions))
2. can the log settings be updated once a faster device is created (this is to facilitate deferent scenarios where we don't need to restart whole app for some settings variations like memory size, compaction threshold etc.)
3. i cant find a method to update an existing key values in docs
4. in some samples you are using BinaryObjectSerializer and some don't, will I have performance benefit if I use plain string values (for example using json serialization to keep values as string)?

thanks for your time

**Comment by aloksharma1** [comment]
@badrishc can you please reply back to this, i am almost finished with main implementations.

thanks

**Comment by badrishc** [comment]
1. You need to implement it yourself using RMW which is very powerful but requires some deeper knowledge to use.  Sorry we are unable to help with individual requests, but our samples should help. By default things never expire, but if null device is used for storage, then records expire when they leave main memory.

2. Basic log settings are fixed but memory size can be controlled dynamically using EmptyPageCount. See our sample at https://github.com/microsoft/FASTER/tree/main/cs/samples/MemOnlyCache.

3. Please benchmark it yourself and choose whichever serializer works best for you.

**Comment by badrishc** [comment]
You do not need to keep the log device undisposed, that is, you can call Dipose. As long as the files on disk are not deleted, everything should be fine.

To access all cache keys, you can perform store.Iterate() which will return all the keys in the database. https://github.com/microsoft/FASTER/blob/main/cs/src/core/Index/FASTER/FASTERIterator.cs

**Comment by aloksharma1** [comment]
ok, all points done working on nuget packaging & sample project. 
thanks for your valuable time.

**Comment by badrishc** [comment]
Fantastic! If this is open source, feel free to drop a link here :).
