### ISSUE TITLE
Storing POD types that have std::string fields.

### ISSUE THREAD

**Issue by ximo1234** [microsoft/FASTER#686]
Hello.

We have a bug using FASTER 4 CPP (v1.9.16) when storing objects that contain std::string fields.
The bug is happening only on windows not on Linux.

We have attached an example that reproduces the bug.
If we build the solution and run MyProject putting a breakpoint on FasterCacheDatasource.hpp::100 we see that the value stored for the fields std::string is not correct.

Why could it be happening?

Thanks.

[FasterExample.zip](https://github.com/microsoft/FASTER/files/8379029/FasterExample.zip)
![breakpoint](https://user-images.githubusercontent.com/94611343/160799659-9466c31d-7de1-4624-8d25-9f6d81220a40.png)

**Comment by badrishc** [comment]
It might be related to the way you have defined the callbacks. Sorry we are unable to help resolve individual issues in C++ at the moment. If you see a solution and wish to submit a PR, that will be welcome. Our unit tests are highly detailed and cover variable length data types as well.
