### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by AtlantisDe** [microsoft/FASTER#690]
Too difficult to get started! Excuse me, how to save the database? All the sample code is running in memory? Can't save to hard disk?

### like LevelDB.Standard
- it is so easy 
- [oodrive/leveldb.net](https://github.com/oodrive/leveldb.net)

```c#
var options = new LevelDB.Options { CreateIfMissing = true };
var db = new LevelDB.DB(options, @"C:\temp\tempdb");

 db.Put("NA", "Na");

// Closing a Database
db.Close();

```

**Comment by badrishc** [comment]
It appears you may have skipped our samples. For example, here is a sample that does checkpoint/recovery: https://github.com/microsoft/FASTER/tree/main/cs/samples/StoreCheckpointRecover

FASTER is not comparable to LevelDB. Latter uses LSM tree based technology which is neither memory optimized nor in the same performance ballpark. FASTER optimizes for main memory behavior, and does not persist by default unless you opt-in via periodic checkpointing. There is a learning curve, but that is fundamental to the level of flexibility and performance that this work aims to offer as a middleware library.
