### ISSUE TITLE
Feature Request: Cache Priority Setting for Tailed Log

### ISSUE THREAD

**Issue by aloksharma1** [microsoft/FASTER#698]
Hi,
i think it would be a great idea to to mark caches with a priority level, so whenever log compaction is called such marked caches which needs high availability all times are given first priority to stay in memory instead of persistence cache store.

for example something like this in library:

`await session.UpsertAsync(ref keySpanByte, ref objSpanByte, PriorityLevel.Memory).ConfigureAwait(false); `

so whenever log compaction is called on heap, the marked data can stay in memory addresses (based on hardcoded FIFO/LIFO & available memory space), it would be a great addition imho.

thanks

**Comment by badrishc** [comment]
This feature can be implemented outside the core DB by maintaining different stores with different priority levels. Each store can customize its use of main memory vs storage layers. It is overall preferable to keep the core DB layer simple when it is possible to build more complex functionality on top in a layered fashion.
