### ISSUE TITLE
Compaction based garbage collection

### ISSUE THREAD

**Issue by badrishc** [Microsoft/FASTER#70]
Currently we support garbage collection based on expiry of keys, via truncation from the head of the log. This has extremely low overhead, and captures the cases where there is a limit on TTL of all keys. However, there are cases where actual compaction of live keys is necessary. Thus, we need an mechanism to roll forward pages from the head, by determining liveness of keys in the pages to be expired, and reinserting live keys at the tail. Adding @gunaprsd.

**Comment by gunaprsd** [comment]
It is impossible to avoid scanning through the records (to check the key) when you use an approximate summary of keys such as bloom filter. One alternative is to store the keys in a separate file alongside the hybrid log. This can also be computed as an offline post-processing. 

For every page or segment we have a keys file. We wish to garbage collect `segments[0]` and the subsequent segments are `segments[1], ..., segments[n]'. 

## Hash-Table Based Solution
The only requirement on the keys file is that it must contain all keys that have a record in the corresponding hybrid log segment. 

```Csharp
hashTable = create hash table from segments[0].keys file to {valid, invalid}
for(int i = 1; i <= n; i++) {
  other = segments[i].keys;
  foreach(var key in other) {
    if(hashTable[key] == 'valid') {
      hashTable[key] = 'invalid';
    }
  }
}

foreach(var key in hashTable.keys) {
  if(hashTable[key] == 'invalid') {
    create corresponding record at tail;
  }
}
```

## Sort-Merge-Diff Solution
Another variant is to have a sorted keys file for each segment. For each `segments[i]` with `i > 0`, we scan through sorted keys and merge-diff with that of `segments[0]`

```Csharp
res = segments[0].sorted_keys;
for(int i = 1; i <= n; i++) {
 seg = res;
 res.clear();
 other = segments[1].sorted_keys;
 seg.begin();
 other.begin();
 while(seg.hasNext() && other.hasNext()) {
   if(seg.front() == other.front()) {
    seg.next();
    other.next();
   } else if (seg.front() < other.front()) {
    res.add(seg.front());
    seg.next();
   } else {
    other.next();
   }
 }
 while(seg.hasNext()) {
  res.add(seg.next());
 }
 seg.close();
 other.close();
 res.close();
}
```

## Comparison
|                | Hash-Table-Based                         | Sort-Merge-Diff                                                    |
|----------------|------------------------------------------|--------------------------------------------------------------------|
| Memory         | Entire key-set of one segment (its hash table) and a page | Two pages                                                          |
| GC-Time        | Scan through only keys in other segment  | Scan through both segments and rewrite keys for GC segment n times |
| Pre-processing | Simply write out keys                    | Need to sort the keys                                              |

**Comment by badrishc** [comment]
Compaction is now merged to master!
