### ISSUE TITLE
Effect of MemorySize on simple example

### ISSUE THREAD

**Issue by danielearwicker** [microsoft/FASTER#701]
Apologies for noob question, I am trying a simple example where I load a `FasterKV<string, string>` with lots of pairs, take a full check point, and print out `Process.GetCurrentProcess().WorkingSet64` at various points (after `GC.Collect`), to see if I can detect any effect of changing the  `FasterKVSettings.MemorySize` property.

My first try was with 1 million upserts and the results confused me:

I started with the default `1L << 34`:

```
upserting: 00:00:07.8522498
Memory: 536.1953125 MB

checkpointing: 00:00:18.1642144
Memory: 850.23046875 MB
```

Then I took `MemorySize` down to `1L << 25`, the lowest it can go, same as page size and got:

```
upserting: 00:00:07.9030933
Memory: 501.46875 MB

checkpointing: 00:00:16.7472909
Memory: 844.40234375 MB
```

The end result is many times greater than implied by `MemorySize` (based on my obviously super-naive interpretation.) But also I'd expect the upserting stage to get slower if it is needing to spill out to the storage device as it goes, so that doesn't seem to happen at this scale. Basically they're almost but not quite the same (I did some repetitions and the slight fall in memory usage appears consistent, not just noise).

Then I tried with 10 million upserts. This is  `MemorySize` = `1L << 34`:

```
upserting: 00:01:14.0851202
Memory: 3.8975486755371094 GB

checkpointing: 00:02:14.2100113
Memory: 4.817070007324219 GB
```

This is `1L << 25`:

```
upserting: 00:03:13.8693017
Memory: 733.15625 MB

checkpointing: 00:00:12.9585244
Memory: 731.83203125 MB
```

Bingo - in fact, it now ends up using _less_ than for 1 million. The total time upserting + checkpointing is the same, about 3:28, but with the lower `MemorySize` the time is shifted mostly to the upserting stage. This I understand! So it's clearly spilling out to storage as I fill it up, because it's hitting a limit. It's just not as low as the limit I imagined.

So I'm naively looking for a control knob that I can set to limit the _total_ memory impact of using a KV such that it will try to stay within that limit. What I've found is a control knob that controls the scale of _something_ held in memory, but I'd need to multiply it by something specific to my test to get the actual memory requirement, e.g. the average size of my keys and/or values?

Is there anything like a total memory limit that I can set somehow, or should I just estimate (or test) on a per-application basis?

**Comment by badrishc** [comment]
Good analysis! Yes, the behavior is a bit nuanced with reference types stored in FASTER. Strings are reference types. In this case, FASTER's log settings specify the size of pages that contain references to key and value strings. Each record takes up 24 bytes in the log (8 byte record header, 8 byte reference to key string, and 8 byte reference to value string). Thus the computation of real memory footprint is indirect.

We have documentation that explains this more, and a sample that shows how you can compute and control the exact memory footprint of FASTER in the presence of reference types, here: https://microsoft.github.io/FASTER/docs/fasterkv-tuning/#log-memory-size-with-c-heap-objects

**Comment by badrishc** [comment]
If your average key/value size is stable, then a simple solution, in lieu of precise tracking, would be:
* N = Num records in memory = Total allocated memory log size in bytes (M) divided by 24 bytes
* Multiply N by (avg key size + avg value size) to get total reference data size (R)
* The avg key/value size may need to be slightly overestimated above string.Length as C# has some string overheads and each character occupies 2 bytes (so, maybe `20 + 2 * string.Length`?)
* Total memory footprint of log = M + R
* For total memory usage of FASTER, do not forget to include index size, overflow bucket size. See here for an example: https://github.com/microsoft/FASTER/blob/c2d4b7b38700bb790f639ef8bc304ef169e0793b/cs/samples/MemOnlyCache/CacheSizeTracker.cs#L26
