### ISSUE TITLE
VersionChangeStateMachine.NextState(SystemState start) - FASTER.core.FasterException: Invalid Enum Argument

### ISSUE THREAD

**Issue by cmadh** [microsoft/FASTER#704]
Unfortunately I'm not able to reproduce the issue without running my application for multiple hours but from time to time the following exception is thrown 

> FASTER.core.FasterException: Invalid Enum Argument
   at FASTER.core.VersionChangeStateMachine.NextState(SystemState start)
   at FASTER.core.HybridLogCheckpointStateMachine.NextState(SystemState start)
   at FASTER.core.FasterKV`2.ThreadStateMachineStep[Input,Output,Context,FasterSession](FasterExecutionContext`3 ctx, FasterSession fasterSession, List`1 valueTasks, CancellationToken token)

followed by and endless loop of ReadCompletionCallbacks and the exception above.

**Application is continously calling** 
    
```
        public async Task<Status> Write(SomeClass someObj)
        {
             long id= someObj.Number;

             var result = await _session.UpsertAsync(ref id, ref someObj);
             while (result.Status.IsPending)
                 result = await result.CompleteAsync();
             return result.Status;
        }
```

**While frequently taking Checkpoints (index checkpoint after every 30th log-checkpoint)**

```
        private void CommitThread()
        {
            if (_options.LogCheckpointInterval is null or 0)
                return;

            int logCheckpointsTaken = 0;

            while (true)
            {
                try
                {
                    Thread.Sleep(_options.LogCheckpointInterval.Value);

                    _store.TakeHybridLogCheckpointAsync(CheckpointType.FoldOver, true).GetAwaiter().GetResult();

                    if (_options.FlushAfterCheckpoint)
                            _store.Log.FlushAndEvict(true);

                    if (logCheckpointsTaken % _options.IndexCheckpointMultiplier == 0)
                            _store.TakeIndexCheckpointAsync().GetAwaiter().GetResult();

                    logCheckpointsTaken++;
                }
                catch (Exception ex)
                {
                    Log.Error(ex, "");
                }
            }
        }
```

**Comment by cmadh** [comment]
Since I did some changes to seasion-pooling it hasn't happened again so I assume it only happened due to using a single session for multiple write-operations in parallel. 

Not sure if this issue needs further investigation or could be closed.

**Comment by badrishc** [comment]
We were also unable to get this to repro, so closing. Will monitor to see if it recurs.
