### ISSUE TITLE
DeleteInfo.RecordInfo is not assigned when calling ConcurrentDeleter

### ISSUE THREAD

**Issue by sebastianburckhardt** [microsoft/FASTER#706]
The `RecordInfo` field of the `DeleteInfo` struct that is passed into `ConcurrentDeleter` is not being assigned before the call.

This causes the cache size tracking to be off. For example, in the samples, the class `MemonlyCache.CacheFunctions` needs the record info to be properly set:
```csharp
public override bool ConcurrentDeleter(ref CacheKey key, ref CacheValue value, ref DeleteInfo deleteInfo)
        {
            sizeTracker.AddTrackedSize(-value.GetSize);
            // Record is marked invalid (failed to insert), dispose key as well
            if (deleteInfo.RecordInfo.Invalid)
                sizeTracker.AddTrackedSize(-key.GetSize);
            return true;
        }
```

This appears to be the root cause of the Netherite issues https://github.com/microsoft/durabletask-netherite/issues/132 and https://github.com/microsoft/durabletask-netherite/issues/160.

**Comment by badrishc** [comment]
Thanks for the report, we should have a fix and new release tomorrow.
