### ISSUE TITLE
Minor release 2.0.8 breaks library built with 2.0.1

### ISSUE THREAD

**Issue by kwaclaw** [microsoft/FASTER#713]
On instantiating FasterLog I get this exception:
```
    System.MissingMethodException: Method not found: 'Void FASTER.core.FasterLog..ctor(FASTER.core.FasterLogSettings)'.
```

this is part of my code (was built with v2.0.1 under .NET 6.0):
```
    public FasterChannel(string deviceLogPath) {
      _device = Devices.CreateLogDevice(deviceLogPath);
      _log = new FasterLog(new FasterLogSettings { LogDevice = _device });
    }
```

When I replace FASTER.core.dll with the original version 2.0.1 the exception goes away.

Looks like it binds to a method signature that went missing, because the signature with the optional parameter is not the same as the one without.

**Comment by TedHartMS** [comment]
Thanks for the report. Currently we do not guarantee binary compatibility of releases; you will probably need to rebuild. We will update this in the future if our release cadence changes.
