### ISSUE TITLE
Unusual HighCPU - CPU traces shows most of the time was spent in ReserveEntry, GetNextInternal and GetNext

### ISSUE THREAD

**Issue by abko-auto** [microsoft/FASTER#716]
Is there any known issue? I have recently seen this happening on few nodes.

CPU spike
![image](https://user-images.githubusercontent.com/66053025/174557949-36fbe892-bd5e-474f-bfdd-7ff83337906b.png)

Stack trace from profiler.
![image](https://user-images.githubusercontent.com/66053025/174558283-177e26e3-f67a-4549-a1ab-81066b5c2d80.png)

**Comment by badrishc** [comment]
No, nothing comes to mind. We have a similar scenario running in stable mode for a while. If you are able to provide a stand alone repro, please feel free to re-open.
