### ISSUE TITLE
How to recover from snapshot after process restart?

### ISSUE THREAD

**Issue by marius-klimantavicius** [Microsoft/FASTER#73]
Is it possible to recover FASTER state from snapshots after process restart (crash). All of the examples regarding recovery are for the same process and uses `Guid` that was returned by `TakeFullCheckpoint`. Does it mean that this `Guid` should be stored somewhere (DB for durability) after taking a checkpoint, then during startup it would be read and used for recovery?
What if multiple threads had performed checkpoint - which `Guid` should be used for recovery?

**Comment by badrishc** [comment]
Yes, the point of checkpointing is to be able to recover FASTER after a process failure/crash.

The Checkpoint call returns a `Guid` that the user is responsible for persisting, e.g., in a local file or database. During recovery, you read the `Guid` and use it as the parameter to [Recover](https://github.com/Microsoft/FASTER/blob/c4a2c68e1881b448c6d500bc2248b2155a340444/cs/src/core/Index/FASTER/FASTER.cs#L175). This allows the reader to create multiple checkpoints and choose which one to recover to. One may also take separate checkpoints of the [index](https://github.com/Microsoft/FASTER/blob/c4a2c68e1881b448c6d500bc2248b2155a340444/cs/src/core/Index/FASTER/FASTER.cs#L138) and [hybrid log](https://github.com/Microsoft/FASTER/blob/c4a2c68e1881b448c6d500bc2248b2155a340444/cs/src/core/Index/FASTER/FASTER.cs#L157), and combine these checkpoints to control recovery time.

If multiple threads were interacting with FASTER, each thread should persist its session ID (obtained during [StartSession](https://github.com/Microsoft/FASTER/blob/c4a2c68e1881b448c6d500bc2248b2155a340444/cs/src/core/Index/FASTER/FASTER.cs#L194)). During recovery, each thread registers with FASTER using its session ID, using [ContinueSession](https://github.com/Microsoft/FASTER/blob/c4a2c68e1881b448c6d500bc2248b2155a340444/cs/src/core/Index/FASTER/FASTER.cs#L205). This call will return the operation sequence number from which the thread should continue feeding input operations after recovery.

You can take a look at the [SumStore](https://github.com/Microsoft/FASTER/tree/master/cs/playground/SumStore) example for more details. This example allows you to recover after a crash. Adding @gunaprsd as well (feel free to chime in with more details or corrections).
