### ISSUE TITLE
Null Reference Exception after disposing the last Iterator

### ISSUE THREAD

**Issue by DieterP99** [microsoft/FASTER#737]
We got an NullReferenceException during writing to the Log, because disposing the only Iterator from our reading task disposes the fasterLog object.

See Line 556 in FasterLogScanIterator.Dispose()
            if (Interlocked.Decrement(ref fasterLog.logRefCount) == 0)
                fasterLog.TrueDispose();

Please remove this lines from the dispose, if possible.

**Comment by badrishc** [comment]
The refcount starts at 1, and every Scan call increments the refcount by 1 here: FasterLog.cs:1405

So the stated issue should not occur if you pair the Scan with exactly one dispose call of the scan iterator.

**Comment by DieterP99** [comment]
Sure, I see this seems not to be the problem.

I created a test in FasterLogTests.cs.
I got a NullReferenceException in this test, because into.Iterators is null:
 if (_lastPersistedIterators.Count != **info.Iterators**.Count)
                return true;

Here is the Code:

`

        [Test]
        [Category("FasterLog")]
        public async ValueTask FasterLogAsyncConsumerTestAfterDisposeIterator([Values] LogChecksumType logChecksum)
        {
            device = Devices.CreateLogDevice(path + "fasterlog.log", deleteOnClose: true);
            var logSettings = new FasterLogSettings { LogDevice = device, LogChecksum = logChecksum, LogCommitManager = manager, TryRecoverLatest = false };
            log = await FasterLog.CreateAsync(logSettings);

            byte[] entry = new byte[entryLength];
            for (int i = 0; i < entryLength; i++)
                entry[i] = (byte)i;

            for (int i = 0; i < numEntries; i++)
            {
                log.Enqueue(entry);
            }
            log.Commit(true);


            // Test is working if I add this Iterator
            //using var iter2 = log.Scan(0, long.MaxValue, "TEST2");
            
            var nextAddress = 0L;
            using (var iter = log.Scan(0, long.MaxValue, "TEST"))
            {
                var count = 0;
                while (iter.GetNext(out _,out _, out _, out nextAddress)) count++;
                log.Commit(true);
                Assert.AreEqual(numEntries, count);
            }

            entry = new byte[entryLength];
            for (int i = 0; i < entryLength; i++)
                entry[i] = (byte)i;

            for (int i = 0; i < numEntries; i++)
            {
                log.Enqueue(entry);
            }
`

![25-08-_2022_15-34-01](https://user-images.githubusercontent.com/111874306/186679028-7d8b9a08-cbd8-49c9-9f24-d3b8a9399258.png)

`
            **log.Commit(true);**
            log.CompleteLog(true);

            using (var iter = log.Scan(nextAddress, long.MaxValue, "TEST"))
            {
                var counter = new Counter(log);
                var consumer = new TestConsumer(counter, entry);
                await iter.ConsumeAllAsync(consumer);
                Assert.AreEqual(numEntries, counter.count);
            }


        }

    }`

**Comment by badrishc** [comment]
Thanks for the report. Feel free to submit a fix as pull request, it will take a bit of time for us to review this.
