### ISSUE TITLE
Combine with Orleans 

### ISSUE THREAD

**Issue by SalimiHabib** [microsoft/FASTER#745]
I don't have much time to test and analyze all capability of this fascinating piece of work , but do need to know is it possible to use it in combination with Microsoft Orleans ( distributed database ) for faster reading a big catalogue of data (with distribution capability)?
thank you

**Comment by badrishc** [comment]
FASTER is a C# library that can be used in the context of any app fabric, including Orleans. FASTER can also directly be driven by cloud storage by using AzureStorageDevice as the backing store. You can host your distributed database in grains and access it from other parts of the application. We do not have any samples out of the box that show how to do it, but feel free to contribute here or to the Orleans repo.
