### ISSUE TITLE
Support lifecycle

### ISSUE THREAD

**Issue by Swimburger** [microsoft/FASTER#749]
Going through docs and issues, I can't tell what the support policy is for this project. 
Does Microsoft offer support for this? How long are major versions supported? What OS's are supported?

**Comment by badrishc** [comment]
FASTER is an MSR (Microsoft Research) project, and is used in production in many use cases at Microsoft and in open source, as well as in our own ongoing newer research work. We are passionate about the project and are generally responsive to bug reports, but do not have a formal support guarantee model. We avoid making breaking changes if it is a minor release. FASTER runs on all platforms supported by .NET. Hope this helps.

**Comment by Swimburger** [comment]
Very clear, thank you~
