### ISSUE TITLE
Recover from latest successful checkpoint

### ISSUE THREAD

**Issue by gunaprsd** [Microsoft/FASTER#75]
## Issue
Currently FASTER requires user to provide the appropriate checkpoint GUID for recovery. This is useful for advanced users who might want to do time travel and recover to an earlier checkpoint. But, we need a simpler API that will simply recovery from latest checkpoint. 

## Proposal
This feature is simple to implement. When FASTER moves into the PERSISTENCE_CALLBACK phase (Checkpoint.cs), we can write the current checkpoint GUID into a separate file. During recovery we can always look into this file to recover the latest checkpoint.

**Comment by matthewbrookes** [comment]
Is this closed because it's no longer being considered?
