### ISSUE TITLE
How to tune FasterKV C++ port for larger-than-memory workloads?

### ISSUE THREAD

**Issue by YongjunHe** [microsoft/FASTER#758]
Hi,

I benchmarked FasterKV using https://github.com/microsoft/FASTER/blob/main/cc/benchmark-dir/benchmark.cc on a machine with 32-core, 256 GB memory, and 500 GB SSD. Under the provided setting (in memory ycsb_a_50_50 zipfian workload), FasterKV can achieve 2972590.54 ops/second/thread while RocksDB can only achieve 77741.42 ops/second/thread.

However, after I reduced the log_size from 16 GB to 4 GB and kept everything else the same, FasterKV can only achieve 9678.36 ops/second/thread while RocksDB with 2 * 2 GB wirte_buffer_sizes can still achieve 43225.64 ops/second/thread.

I then reduced kOffsetBits from 25 to 17 but the performance was nearly the same. The performance gap between FasterKV and RocksDB was also nearly the same under the larger-than-memory ycsb_rmw_100 zipfian workload. Is there anything I can tune to accelerate FasterKV under larger-than-memory workloads?

**Comment by badrishc** [comment]
# Running a disk IOPS bound benchmark in FASTER C++

## Parameters
* 8 byte keys, 8 byte values 
* Uniform distribution
* 100% reads
* Log size: 192MB (most data is on disk)
* Index size: 4GB (~16 bytes/key)

Varying #threads, reporting total throughput in Kilo ops/sec

## Code Changes

* Comment out [store_t store{ init_size, 17179869184, "D:\\storage" };]
* Uncomment [store_t store{ init_size, 1048576 * 192ULL, "D:\\storage", 0.4 };]

Note:
* To use less than 192MB of log memory, reduce page size to 4MB (kOffsetBits=22 in address.h). This allows you to reduce log memory down to 24MB (1048576 * 24ULL) in benchmark.cc.

## Command

For 16 threads (use uniform workload files):

```sh
benchmark.exe 2 16 d:\ycsb_files\load_uniform_250M_raw.dat d:\ycsb_files\run_uniform_250M_1000M_raw.dat
```


Note: You can verify random IOPS limits using diskspd.exe ([link](https://github.com/Microsoft/diskspd/)) as below for 20 threads:

```sh
diskspd.exe -d30 -F20 -r -w0 -Sh -b512 -o12 -c8G d:\diskspdtest.dat
```

## Expected performance on modern SSD

![image](https://user-images.githubusercontent.com/18355833/200976687-4d631a33-185a-4082-997b-d4f559eb8a06.png)

**Comment by YongjunHe** [comment]
Hi @badrishc ,

Thanks for replying so quickly.

I tried to reproduce your workload and settings but failed to achieve the same performance immediately. Then I verified the IOPS of my disk as you suggested. I used [fio](https://github.com/axboe/fio) since I am using a Linux server.
```
fio --randrepeat=1 --ioengine=libaio --direct=1 --gtod_reduce=1 --name=fiotest --filename=testfio --bs=4k --iodepth=64 --size=8G --readwrite=randrw --rwmixread=50
fiotest: (groupid=0, jobs=1): err= 0: pid=1856: Thu Nov 10 14:00:35 2022
  read: IOPS=10.7k, BW=41.8MiB/s (43.8MB/s)(4098MiB/98132msec)
  write: IOPS=10.7k, BW=41.7MiB/s (43.7MB/s)(4094MiB/98132msec); 0 zone resets
```
Given the statistics and the previous experimental results, I think FasterKV is more sensitive to IOPS than RocksDB. So I switched to a server with better-performance disks.
```
fiotest: (groupid=0, jobs=1): err= 0: pid=27988: Thu Nov 10 16:40:03 2022
  read: IOPS=181k, BW=706MiB/s (740MB/s)(4098MiB/5807msec)
  write: IOPS=180k, BW=705MiB/s (739MB/s)(4094MiB/5807msec); 0 zone resets
```

Then I got more reasonable experimental results as shown below (all of the workloads use 250 million 8-byte key 8-byte value database). **FasterKV beats RocksDB by 3.6x under Zipfian larger-than-memory read-write-mixed workload and 1.6x under Zipfian larger-than-memory read-modify-write workload.** I think the performance gap between FasterKV and RocksDB will be bigger if the disk IOPS can be higher.
![image](https://user-images.githubusercontent.com/11996826/201156079-3dd9d7a8-da64-4808-a702-ab5ecb23b8fb.png)

**Comment by patelprateek** [comment]
@badrishc @YongjunHe : For read only workloads , it doesn't seem that faster KV performs worse than rocksDB ?

**Comment by YongjunHe** [comment]
> @badrishc @YongjunHe : For read only workloads , it doesn't seem that faster KV performs worse than rocksDB ?

For larger-than-memory read-only workloads, FASTER performs better than RocksDB when the data distribution is skewed.
For in-memory data, FASTER outperforms RocksDB in any distribution or workload.

**Comment by patelprateek** [comment]
@YongjunHe : in the results you posted the perf for uniform distribution reads seems to be lower throughput for fasterKV , are these for larger than memory database ? 

Also curious if you have looked into speedb , splinterdb for a perfroamnce comparison ?
