### ISSUE TITLE
Detecting data corruption for checkpoint files

### ISSUE THREAD

**Issue by gunaprsd** [microsoft/FASTER#76]
## Issue
Currently, we rely on windows file system API to write, flush and protect the files that have important meta information regarding checkpoints and session recovery points. We need to be able to ensure whatever data we read back during recovery is protected and free from any data corruption.

## Proposal
One way to do this is using checksum integrity verifiers. Simply, we can generate a hash for each file and ensure that the hash of the file being used for recovery is consistent.

**Comment by badrishc** [comment]
Closing as this is not on the roadmap as a core FASTER feature at this point. One may implement a custom `IDevice` that supports this outside the core library. We may re-open the issue in future, or accept contributions from users.
