### ISSUE TITLE
LightEpoch, it seems to not guarantee the atomicity of storing epoch in the table entry

### ISSUE THREAD

**Issue by Jiboxiake** [microsoft/FASTER#760]
Just try to point out from https://github.com/microsoft/FASTER/blob/main/cs/src/core/Epochs/LightEpoch.cs , ProtectAndDrain seems to just use a simple assignment to store the epoch. Will this cause any concurrency issues if we consider this as fetching the global CurrentEpoch and then store it at the local epoch entry? (*(tableAligned + entry)).localCurrentEpoch = CurrentEpoch;

**Comment by badrishc** [comment]
The local table entry is dedicated to this thread, so there should be no atomicity issue. CurrentEpoch is 64 bits so the read of this will never be broken.

**Comment by Jiboxiake** [comment]
Thank you. But as far as I'm concerned, (*(tableAligned + entry)).localCurrentEpoch = CurrentEpoch, involves fetching the current epoch and storing it in the local entry. Those are two operations. There can be other threads scanning the table to find the safe epoch. My concern lies in if the fetch happens with the original epoch, and then the store doesn't happen immediately (e.g. thread being scheduled out). Next someone bumps the epoch and tries to find a safe epoch. It may assume the previous epoch is safe. If the other thread is scheduled back, it may store the old epoch and break the consistency. Is this a concern? Thanks.

**Comment by badrishc** [comment]
Thanks for analyzing this logic. The scenario you describe has been considered in the design of epochs. We are just capturing some (possibly lazy) value of the global CurrentEpoch. It is fine if this thread gets swapped out before it saves that value into its local entry. If the thread was unable to copy it before getting swapped, its entry will just remain OLDER, thereby preventing safe epoch from moving forward. Note that an epoch being safe implies that all previous epochs are safe as well. Thus this is not a concern.

**Comment by Jiboxiake** [comment]
Thank you so much! It makes sense then.

**Comment by Jiboxiake** [comment]
Hello, sorry to continue asking about it. I have double checked ComputeNewSafeToReclaimEpoch and release. I found ComputeNewSafeToReclaimEpoch will only consider non-zero epochs when calculating a safe epoch and Release will reset a thread's epoch to 0. So will this still be a problem? Thanks.

**Comment by badrishc** [comment]
Why would it be a problem? Release sets the epoch to 0, which removes it from consideration for safety, and we know at that point (when it sets to 0) the thread is no longer participating in protection, so it would be fine to move the safe epoch forward.

I think it would be better for discussion if you can come up with a specific sequence that you find results in an error state.

**Comment by badrishc** [comment]
In this case the thread will potentially be at an epoch earlier than the safe epoch. However, it will not see that prior state of the world, since it is entering epoch protection for the first time. So, any drain actions that executed as a result of the safe epoch erroneously moving forward, do not negatively affect the system.

**Comment by Jiboxiake** [comment]
I think I now get your point. My concern was that a thread has an old epoch but the safe epoch moves forward. Now it seems like it will not be that harmful as your described. Thanks.
