### ISSUE TITLE
Sample broken, Debug.Assert fails, RMW doesn't update output reference

### ISSUE THREAD

**Issue by tskarman** [microsoft/FASTER#762]
These two samples run into a failed assertion around `Debug.Assert(output == value + 20);`.

- https://github.com/microsoft/FASTER/blob/main/docs/_pages/home.md
- https://github.com/microsoft/FASTER/blob/main/docs/_docs/20-fasterkv-basics.md

While this sample that is not using the `ref output` signature of `RMW` but does a separate `.Read()` does not fail the assertion.

- https://github.com/microsoft/FASTER/blob/main/docs/_docs/01-quick-start-guide.md

From skimming the sample source it looked to me like the samples are using an implementation that is incomplete. But since the sample snippet from the docs doesn't actually use the sample source, there is prob. more going on so I'll leave the interpretation to you.

Blame links with line numbers to quickly jump to the respective samples:

Failing:
- https://github.com/microsoft/FASTER/blame/main/docs/_pages/home.md#L113
- https://github.com/microsoft/FASTER/blame/main/docs/_docs/20-fasterkv-basics.md#L388

Not failing:
- https://github.com/microsoft/FASTER/blame/main/docs/_docs/01-quick-start-guide.md#L53

**Comment by badrishc** [comment]
Good catch, the samples were assuming that the `IFunctions` implementation copies the new value to output, which `SimpleFunctions` did not. We have fixed `SimpleFunctions` to perform this copy to output. Note that you can always (recommended) write your own `IFunctions` implementation, extending from `FunctionsBase` or `SimpleFunctions`, for whatever behavior you desire. This commit fixes the issue for our in-built `SimpleFunctions`: https://github.com/microsoft/FASTER/pull/759/commits/39af951e1fb909d36ae6a15893e16312b1bab6f6

**Comment by tskarman** [comment]
thank you! :-)
