### ISSUE TITLE
RecoverFiles fails to int.Parse on bareName nuget v.2.1.0 using .net7 on windows 10

### ISSUE THREAD

**Issue by Astn** [microsoft/FASTER#767]
Thanks for the amazing Library! It's a very impressive work.

I'm trying to recover files after shutting down.

In my log directory I have:
```
logfile
logfile.0
```
The logic for populating the segids is picking up `logfile` and trying to parse an end off of the back of it. It seems like it the expectation is that di.GetFiles("*") would only return files that a have `logfile` as the beginning portion, but should exclude `logfile`.

I end up with an int.Parse error as it tries to parse an empty string from:
```c#
            foreach (System.IO.FileInfo item in di.GetFiles(bareName + "*"))
            {
                int segmentId = Int32.Parse(item.Name.Replace(bareName, "").Replace(".", ""));
                ...
            }
```
I think we should add an extra check inside the loop to continue if we end up with an empty segment number string.

eg:
```c#
// (Managed)LocalStorageDevice.cs :: private void RecoverFiles()
            foreach (System.IO.FileInfo item in di.GetFiles(bareName + "*"))
            {
                // on .net7 windows 10 we are getting bareName as one of the files returned from DirectoryInfo.GetFiles
                // the file that is bareName has no ".{segmentId}" appended, so the int32.parse below would fail.
                if (item.Name == bareName)
                {
                    continue;
                }
                
                int segmentId = Int32.Parse(item.Name.Replace(bareName, "").Replace(".", ""));
                
                ...
            }
```

Would you like me to submit a PR?

**Comment by badrishc** [comment]
Great details and thanks for the fix, this makes sense!
