### ISSUE TITLE
tryRecoverLatest of FasterKV does not work

### ISSUE THREAD

**Issue by EugeneZhudro** [microsoft/FASTER#771]
I used this serializer for emulation problems with recovery:

`public sealed class OnlyForTestSerializer<T> : BinaryObjectSerializer<T>
{
        private readonly static DataContractSerializer serializer = new DataContractSerializer(typeof(T)); 
        public override void Deserialize(out T obj)
        {            
            throw new Exception("My test exception");
        }
        public override void Serialize(ref T obj)
        {
            using var ms = new MemoryStream();
            using (var _writer = XmlDictionaryWriter.CreateBinaryWriter(ms, null, null, false))
                serializer.WriteObject(_writer, obj);
            writer.Write((int)ms.Position);
            writer.Write(ms.ToArray());
        }
   }`

In the result of my test, I get an unhandled exception and my application stopped

**Comment by badrishc** [comment]
Do you have a stand alone repro? We have many samples in the repo for how to use serializers correctly. Thanks.

**Comment by EugeneZhudro** [comment]
I have a real-life situation in my project. After an emergency close my application sometimes FASTER files are broken. As result, my application does not start because every start stops an unhandled exception.

I will prepare an example and share it with you

**Comment by badrishc** [comment]
We don't handle exceptions if they are propagated outside the serializer code. Please use try/catch and handle the exception inside your serializer.

**Comment by EugeneZhudro** [comment]
It was just an example. In my real project, we don't use a custom serializer. We create a FasterKV with a default serializer and time-to-time call TakeHybridLogCheckpointAsync(CheckpointType.FoldOver). All work fine but If we stop our application and try to start again we have an UNHANDLED exception when we try to Recover our FacterKV with the option tryRecoverLatest (not very often). As I checked the code of FasterKV we should just skip the issue with recover and continue BUT It doesn't work at all! In a result our application stop and we don't have any possibility continue work without removing the folder with FATER's files
