### ISSUE TITLE
AsciiSumSample fails

### ISSUE THREAD

**Issue by cmadh** [microsoft/FASTER#777]
The AsciiSumSample in StoreVarLenTypes.csproj fails (seems to fail after or while the call to `store.Log.FlushAndEvict(true);` ) and prints "Error" to the console.

Version v2.2.0.

WSL2 Ubuntu 20.04, .net 7.0.101

    # dotnet run StoreVarLenTypes.csproj
    Error!
    MemoryByteSample: Success!
    MemoryIntSample: Success!
    SpanByteSample: Success!
    Press <ENTER>

Likely a different issue but running it from within Visual Studio in Debug Mode on Windows or WSL2, System.ArgumentExceptions are thrown (in GCHandle.cs) for the other samples:

    Error!
    Assuming 512 byte sector alignment for disk with file hlog.log
    Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
    Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
    MemoryByteSample: Success!
    Assuming 512 byte sector alignment for disk with file hlog.log
    Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
    Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
    MemoryIntSample: Success!
    Assuming 512 byte sector alignment for disk with file hlog.log
    SpanByteSample: Success!
    Press <ENTER>

**Comment by badrishc** [comment]
> The AsciiSumSample in StoreVarLenTypes.csproj fails (seems to fail after or while the call to store.Log.FlushAndEvict(true); ) and prints "Error" to the console.

RMW changed a while back so that it returns pending if it needs to do an IO. This is why you see a pending status. The line 62 should just be `if (!_status.IsPending)`.

**Comment by badrishc** [comment]
> Assuming 512 byte sector alignment for disk with file hlog.log

this is reasonable, as the input does not contain a drive path such as 'c:/` as prefix.

**Comment by badrishc** [comment]
> Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll

This can be ignored, we use an exception mechanism in Utility.cs line 160 to determine if a type is blittable.
