### ISSUE TITLE
Chained Entry Infinite Loop - ReadAddress Sample

### ISSUE THREAD

**Issue by adam-dot-cohen** [microsoft/FASTER#791]
There appears to be a bug that was introduced in the 2.2.0 release (version 2.1.0 works fine) that effects chained log entries.  After writing chained values, attempting to read using `ReadOptions.StartAddress` the second call to `session.Read` results in an infinite loop in [Faster.cs line 602](https://github.com/microsoft/FASTER/blob/main/cs/src/core/Index/FASTER/FASTER.cs#L602).

To reproduce the error, simply run the VersionedRead sample application after merging the bug fix that I've submitted under PR #790.  If you change project dependency to the 2.1.0 Nuget package, the issue will not occur. 

See comment below for reference to line to debug...

```csharp
private static void ScanStore(FasterKV<Key, Value> store, int keyValue)
{
	using var session = store.For(new Functions()).NewSession<Functions>();

	Console.WriteLine($"Sync scanning records for key {keyValue}");

	var output = default(Value);
	var input = default(Value);
	var key = new Key(keyValue);
	ReadOptions readOptions = new() { ReadFlags = ReadFlags.DisableReadCache };
	for (int lap = 9; /* tested in loop */; --lap)
	{
		//INFITE LOOP OCCURES ON THE SECOND CALL
		var status = session.Read(ref key, ref input, ref output, ref readOptions, out var recordMetadata, serialNo: maxLap + 1);

		if (status.IsPending)
		{
			session.CompletePendingWithOutputs(out var completedOutputs, wait: true);
			using (completedOutputs)
			{
				completedOutputs.Next();
				recordMetadata = completedOutputs.Current.RecordMetadata;
				status = completedOutputs.Current.Status;
			}
		}

		if (readOptions.StartAddress >= store.Log.BeginAddress)
			break;

		readOptions.StartAddress = recordMetadata.RecordInfo.PreviousAddress;
	}
}
```

**Comment by badrishc** [comment]
Merged, thanks!

**Comment by badrishc** [comment]
This commit fixes it: https://github.com/microsoft/FASTER/pull/789/commits/35019e9296dede07be0c4267e7cdc0b3c21ea934 - PR is open.
