### ISSUE TITLE
Where can i read version wise changelogs?

### ISSUE THREAD

**Issue by aloksharma1** [microsoft/FASTER#798]
Hello,

My faster cache layer is built on faster version 1.9.16 which is using checks like `Status.PENDING` but when i updated to newer version 2.3.6 this and `session.Compact` have broken down.
`session.Compact(compactUntilAddress, true);`
i am using status checks on a lot of places, please guide.

**Comment by badrishc** [comment]
All releases are here: https://github.com/microsoft/FASTER/releases

Closed pull requests are here: https://github.com/microsoft/FASTER/pulls?q=is%3Apr+is%3Aclosed

You should be able to determine the changes looking through these. We do not maintain a separate change log.

Status, just the naming has changed. It should be easy to update. Just look at the latest samples. The PR for status code update is here: https://github.com/microsoft/FASTER/pull/638

**Comment by aloksharma1** [comment]
thank you
