### ISSUE TITLE
Unity Implementation? C#

### ISSUE THREAD

**Issue by bureto** [Microsoft/FASTER#81]
I've been trying to get this to work with Unity but no matter what I do it doesn't seem to work. Would there be any reason that it is incompatible? I have tried using different methods from the examples (SumStore, and a slightly modified version of it) and it kept giving me the same problem: 
It froze on startup, sometimes it would recover and was able to finish but I usually had to just kill the program. I could have reduced the amount of data, but the weird thing is that when it would occasionally finish, all that was left in the log files was just one single folder and I noticed that the folder was also missing a lot of stuff. 

After trying to troubleshoot it for a while I decided to instead just make my own script.
I was using much less data in my script (length of 30), but I'm getting the same sort of issues. 
Currently what is happening is the `info.dat` file is missing in `index-checkpoints` guid folder, and the cpr-checkpoints guid folders are completely empty. There was a more things going wrong that I can't recall (that were happening when I  was using the pre-made examples), but the general gist is that I'm having a hard time getting it to work in Unity.

Is there any hope for me?
Thanks for your time :)

**Comment by bureto** [comment]
Hi there gunaprsd, 

1. It runs just about the same with checkpoints disabled (it freezes in the editor). One trick I have found to get it from freezing was to run it as a headless build.

2. It doesn't seem so, no matter how many checkpoints scheduled to be taken it will finish before completing the first one. Unfortunately, I think the process is being stopped before any meaningful information is being written down (even in a headless build). For instance, the `Populate successful` is not being shown in the console window, and instead I have to get the output from the .txt output file. 

Here is the output from my build:
```
UnloadTime: 0.731746 ms
Populate successful

 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

5a54b1a0-7ec8-4e1f-b7b9-510152ec82af

 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 45)

Setting up 4 worker threads for Enlighten.
  Thread -> id: 1ed8 -> priority: 1 
  Thread -> id: 20a0 -> priority: 1 
  Thread -> id: 1c74 -> priority: 1 
  Thread -> id: 764 -> priority: 1 

```

**Comment by bureto** [comment]
Hi badrishc, 

I attempted to setup this repo this morning for you guys, I apologize in advanced for it's messiness; it was my first time uploading a unity project. 
You may want to look at [this](https://github.com/bureto/Unity-FASTER-test/blob/master/Assets/test.cs) first, it's the only thing I made different. The rest is pretty much from your guys' examples. 

My:

- Scripting Runtime Version: .NET 4.x
- Scripting Backend: Mono
- Api Compatibility Level: .NET 4.x

**Comment by badrishc** [comment]
Your code might be ending before even one checkpoint has completed. After calling TakeFullCheckpoint, you can ensure that checkpointing completes by calling CompleteCheckpoint(true). This will ensure that checkpoint has finished, at the expense of blocking the thread until it is done. See example here: https://github.com/Microsoft/FASTER/blob/0586bae5639d2758d1052ce34a48955f2a6d90c9/cs/test/SimpleRecoveryTest.cs#L65

**Comment by bureto** [comment]
When I call CompleteCheckpoint(true), the program freezes (which would be understandable if had huge amount of data), but I can run it just fine in Visual Studio (takes < 1 second). I am convinced now that it is a bug on Unity's side. Thanks for the help, I'll see if I can port over my project into my own solution.
