### ISSUE TITLE
should we have a function ContainsKey for ClientSession? when we only check if item exists by key.

### ISSUE THREAD

**Issue by bmrxntfj** [microsoft/FASTER#816]
sorry, i make a mistake.
I have a scene that only check if item exists in cache. so i want a function like "bool ContainsKey(key)", but read a full data by Read of ClientSession and compare it like "session.Read(key)!=null".

**Comment by badrishc** [comment]
you can just perform a Read and check it yourself. there is no performance advantage to ContainsKey, as compared to a Read.

**Comment by bmrxntfj** [comment]
> you can just perform a Read and check it yourself. there is no performance advantage to ContainsKey, as compared to a Read.

thanks very much, i feel like it get performance advantage like others normal cache. I will study this code well. Thanks Again!!!
