### ISSUE TITLE
Broken link to Playground example

### ISSUE THREAD

**Issue by alexeyzimarev** [microsoft/FASTER#831]
This page https://microsoft.github.io/FASTER/docs/fasterlog-basics/ contains the following:

> Note that while RefreshUncommitted incurs a small CPU overhead to the write operation, it does not perform any I/O operation. The example in [playground](https://github.com/microsoft/FASTER/tree/master/cs/playground/FasterLogPubSub) shows how to use this feature.

However, the link is broken as there's no `FasterLogPubSub` sample in the repository anymore.

**Comment by alexeyzimarev** [comment]
I guess this is where it should be pointing to https://github.com/microsoft/FASTER/blob/00ed6ea3bf1420ed5840d231644f3845c4b2440c/cs/samples/FasterLogPubSub/Program.cs

**Comment by badrishc** [comment]
Thanks, fixed.
