### ISSUE TITLE
Commit only certain records

### ISSUE THREAD

**Issue by Phylum123** [microsoft/FASTER#834]
I want to use faster log as a queue (record order is important)  but when I commit, only records with the first byte being a 1, should ever commit. Also I need to be able to delete any record regardless of its position in the queue.  Is this possible with faster log or faster kv?

**Comment by Phylum123** [comment]
Does fasterKV keep the underlying log in append order? IE there is no optimization or something that moves records around? IF that is the case, then I just have to worry about the selective commit.

**Comment by badrishc** [comment]
FasterKV might perform an in place update, other than that it should be in order.
