### ISSUE TITLE
Is removing in the road map?

### ISSUE THREAD

**Issue by vzayko** [Microsoft/FASTER#85]
Do you plan to add removing operation any time soon? Thanks!

**Comment by badrishc** [comment]
Yes, deleting via tombstone records is planned, but you can also do it yourself at the application level by updating the record with a field that indicates it is marked as deleted. Are you using the C# or C++ version of FASTER?

**Comment by vzayko** [comment]
Thank you for the info and idea! I use c# version.

**Comment by badrishc** [comment]
We are in the process of adding first-class support for both deletes and periodic log compaction. See PRs https://github.com/Microsoft/FASTER/pull/112 and https://github.com/Microsoft/FASTER/pull/114 for details.

**Comment by badrishc** [comment]
Support for deletes is now merged to master.
