### ISSUE TITLE
in memory concurrent support dictionary

### ISSUE THREAD

**Issue by MarshalOfficial** [microsoft/FASTER#853]
Is it possible to use Faster as a concurrent dictionary for in-memory usage (without any persistent), I'm looking for something better than ```ConcurrentDictionary<long, object>``` in C#

**Comment by tcsaddul** [comment]
Try this:  https://github.com/VSadov/NonBlocking

**Comment by badrishc** [comment]
Yes, it can be used as an in memory hash table. You just have to use NullDevice as your backing IDevice.

**Comment by MarshalOfficial** [comment]
> Yes, it can be used as an in memory hash table. You just have to use NullDevice as your backing IDevice.

Thanks
