### ISSUE TITLE
Can FASTER replace Redis? Is there a caching mechanism similar to Redis RDP?

### ISSUE THREAD

**Issue by BoyFaceGirl** [microsoft/FASTER#869]
What is the essential difference between FASTER and memercache? Compared to memercache, which is more advantageous in terms of write speed or query speed? Compared to Redis?

**Comment by badrishc** [comment]
FASTER is a key-value library that can be used in any application or service. Check our research papers [here](https://microsoft.github.io/FASTER/docs/td-research-papers/) for more comparisons to other systems.
