### ISSUE TITLE
C++ make test fails test #3 and test #4 never seems to end?!

### ISSUE THREAD

**Issue by simonhf** [Microsoft/FASTER#87]
Following the build instructions and running make worked without issue on my Ubuntu VM. However running 'make test' didn't work so well:

```
$ make test
Running tests...
Test project /home/simon/FASTER/cc/build/Release
    Start 1: in_memory_test
1/5 Test #1: in_memory_test ...................   Passed    2.18 sec
    Start 2: malloc_fixed_page_size_test
2/5 Test #2: malloc_fixed_page_size_test ......   Passed   13.12 sec
    Start 3: paging_queue_test
3/5 Test #3: paging_queue_test ................***Exception: Other340.92 sec
    Start 4: recovery_queue_test
```

Is test #4 running 'forever' because test #3 failed?
How to debug the test #3 failure?
How long should make test normally take to run?
Is there a way to make it run faster as a kind of quick test after a code change?

**Comment by simonhf** [comment]
More info: Upon re-running make test I monitored the paging_queue_test program for test #3. While running, it used all CPU and memory usage slowly climbed to about 2 GB out of 4 GB total on the VM. Then memory stopped climbing for a good long while, and started climbing again until eventually the exception happens again at higher memory usage.
I'm guessing test #3 requires a minimum amount of GB of RAM to run? It would be good to fix the test so that it complains with a human friendly warning if not enough RAM, instead of the cryptic failure currently output after many minutes.

**Comment by badrishc** [comment]
Thanks, we will look into fixing the test to provide such a warning. We also accept PRs after the CLA is signed :).

**Comment by badrishc** [comment]
We have reduced the testcase data sizes and number of threads so that they complete quicker when run on normal machines.
