### ISSUE TITLE
Implement atomic GetOrAdd/AddOrUpdate equivalency from ConcurrentDictionary<>

### ISSUE THREAD

**Issue by stealthin** [microsoft/FASTER#873]
Hello,

Firstable, a huge thanks for this amazing library.

I have a question: I'm using the [SpanByteFunctions](https://github.com/microsoft/FASTER/blob/main/cs/src/core/VarLen/SpanByteFunctions.cs) and I'd like to know if it would be possible to implement a behavior to mimic the atomic operations [GetOrAdd](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd?view=net-7.0) and [AddOrUpdate](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.addorupdate?view=net-7.0).

Would it be feasible, and if so, would you mind sharing a code to override the default implementation from SpanByteFunctions?

Many thanks.

**Comment by badrishc** [comment]
You can implement any of these using RMW in FASTER. For example, TryAdd is discussed here: https://github.com/microsoft/FASTER/pull/345#issuecomment-701617849
