### ISSUE TITLE
Would like example of using a string key in C++ please

### ISSUE THREAD

**Issue by simonhf** [microsoft/FASTER#88]
I noticed that the paper says:

"Note that keys are not part of the Faster hash index, unlike many traditional designs, which provides two benefits:
• It reduces the in-memory footprint of the hash index, allowing
us to retain it entirely in memory.
• It separates user data and index metadata, which allows us to
mix and match the hash index with different record allocators."

And also the benchmark-dir/README.md says:

"The output of YCSB's "basic" driver is verbose. A typical line looks like:

  INSERT usertable user5575651532496486335 [ field1='...' ... ]

To speed up file ingestion, our basic YCSB benchmark assumes that the input
file consists only of the 8-byte-integer portion of the key--e.g.:

  5575651532496486335"

Does FASTER support string keys? And if so, is there any example C++ code showing string key manipulation?

**Comment by badrishc** [comment]
@matthewbrookes added a testcase that shows how to handle variable length keys at https://github.com/microsoft/FASTER/pull/128. The same example can be used to handle string keys in C++.
