### ISSUE TITLE
Reduce memory usage for FasterKV

### ISSUE THREAD

**Issue by AqlaSolutions** [microsoft/FASTER#880]
What's causing this 5GB amount of memory usage and what can we do to reduce it and use disk instead?

![image](https://github.com/microsoft/FASTER/assets/3465565/330e7186-526f-4935-8718-df02ed09f9e1)

**Comment by dominicpalmer** [comment]
Are you using references for keys/values? What's your `MemorySizeBits`? I can recommend [this section](https://microsoft.github.io/FASTER/docs/fasterkv-tuning/#log-memory-size-with-c-heap-objects)of the docs.

**Comment by AqlaSolutions** [comment]
Solved by reducing `FasterKVSettings.MemorySize`
