### ISSUE TITLE
Full checkpoint deletes only one log file

### ISSUE THREAD

**Issue by AqlaSolutions** [microsoft/FASTER#881]
I have 74 `hlog.log.*` files 1GB each. When I do this:

            _fasterKv.Log.ShiftBeginAddress(_fasterKv.Log.HeadAddress);
            _fasterKv.TryInitiateFullCheckpoint(out _, CheckpointType.FoldOver);

it deletes only one log file per checkpoint but others stay.

How can I force it to delete everything else?

**Comment by AqlaSolutions** [comment]
It looks like checkpoint state machine hangs and never changes from 21 to 37 state

**Comment by AqlaSolutions** [comment]
I tried calling `TakeFullCheckpointAsync` instead and it completed in seconds but no log files were removed at all this time.

**Comment by AqlaSolutions** [comment]
I ended up writing a code to automatically remove files with segment number < BeginAddress or > Head or Tail Address segments after checkpoints.

**Comment by badrishc** [comment]
I'm not sure why it isn't deleting for you, works fine in our deployments. Feel free to reopen if you have a stand alone repro.
