### ISSUE TITLE
store.TakeFullCheckpointAsync(CheckpointType.FoldOver) stucks forever

### ISSUE THREAD

**Issue by wangjia184** [microsoft/FASTER#887]
I tried the following line to dump a full checkpoint, and it stucks forever. No error, no exception.
```csharp
await store.TakeFullCheckpointAsync(CheckpointType.FoldOver)
```

After changing to the following approach, it works well.
```csharp
await store.TakeHybridLogCheckpointAsync(CheckpointType.Snapshot, tryIncremental: false);
```

Why does it stuck?

**Comment by badrishc** [comment]
Hard to say without a repro. It works fine in our tests. Feel free to reopen if you have a stand alone repro to share.
