### ISSUE TITLE
Does logicAddress change if I truncate the first part of FASTER.log?

### ISSUE THREAD

**Issue by wangjia184** [microsoft/FASTER#894]
`EnqueueAsync` method returns logical address.   

```
|A|B|C|D|E|F|
```

Suppose I have enqueued `F` in the tail and received the logic address returned from `EnqueueAsync` method.
Now if I truncate `A` & `B` by calling `TruncateUntilPageStart` method.  
Will the address of `F` be different from the value previouly returned from `EnqueueAsync`?

**Comment by badrishc** [comment]
No it will stay the same. The address is immutable.
