### ISSUE TITLE
Add a reference to the roadmap in the Readme

### ISSUE THREAD

**Issue by kasajian** [Microsoft/FASTER#9]
By having a reference to the Roadmap, you can address several issues.  First, it tells people you're not done and where the gaps are, and Second, if anyone is interested in contributing, they can start engaging in high-level discussions -- experimenting, etc.

**Comment by badrishc** [comment]
Roadmap is available at our GitHub Pages website. Direct link [here](https://microsoft.github.io/FASTER/roadmap).
