### ISSUE TITLE
Where does the data gets stored.

### ISSUE THREAD

**Issue by vibeeshan025** [Microsoft/FASTER#93]
I am just exploring this repo. Any available sample is not storing the data to the provided log file.

Is there any working sample which used the log file.

**Comment by badrishc** [comment]
Hi, FASTER uses a hybrid log, where the tail of the log is kept purely in memory. As long as the tail fits in memory (and you have not taken a checkpoint), the log files will not be created. Make sure you ingest enough data that the log starts spilling to storage.

Another option is to force the mutable portion of the log to storage, by moving the read-only marker of the log to the tail:

h.ShiftReadOnlyAddress(h.LogTailAddress);

Alternatively, if you take a checkpoint you should see checkpoint files get created. If you take a [fold-over checkpoint](https://github.com/Microsoft/FASTER/tree/master/cs#checkpointing-and-recovery), the log will be flushed until the tail as well as part of the checkpoint.

Also, note that in many examples, for keeping it simple and avoiding growth of local temp files, we use a flag that automatically deletes log files when the program closes:

Devices.CreateLogDevice(Path.GetTempPath() + "hlog.log", **deleteOnClose: true**);

In a real deployment, you would not set deleteOnClose to true.
