### ISSUE TITLE
Unable to reserve an epoch entry

### ISSUE THREAD

**Issue by somecoder2019** [Microsoft/FASTER#94]
Hi,

This might be related to the question asked by some other user about where data is stored. I don't see the log files getting created.

But the program runs and it was processing my computation. I am doing some analysis that generated a million records in a tree form. I am using FASTER to both store the records and the index (additional records added to overcome the fact that faster doesn't have build in indexing).

But I see the below exception after some time. 

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to reserve an epoch entry, try increasing the epoch table size (kTableSize)) ---> System.Exception: Unable to reserve an epoch entry, try increasing the epoch table size (kTableSize)
   at FASTER.core.LightEpoch.ReserveEntry(Int32 startIndex, Int32 threadId) in D:\a\1\s\cs\src\core\Epochs\LightEpoch.cs:line 325
   at FASTER.core.LightEpoch.ReserveEntryForThread() in D:\a\1\s\cs\src\core\Epochs\LightEpoch.cs:line 346
   at FASTER.core.FasterKV`6.InternalRefresh() in D:\a\1\s\cs\src\core\Index\FASTER\FASTERThread.cs:line 49
   at FASTER.core.FasterKV`6.InternalAcquire() in D:\a\1\s\cs\src\core\Index\FASTER\FASTERThread.cs:line 29
```

**Comment by badrishc** [comment]
Please refer to the response [here](https://github.com/Microsoft/FASTER/issues/93) for help with log creation.

How many threads are you using with FASTER? The code assumes an upper limit, defined [here](https://github.com/Microsoft/FASTER/blob/4b7a687e43a9e6966a6e43953d14b1adb11ac0d4/cs/src/core/Epochs/LightEpoch.cs#L31).

I would try to make sure you are not creating too many threads to use with FASTER. If you are sure you need more than the number of threads specified in the limit above, you may increase the limit (in powers of two).

**Comment by somecoder2019** [comment]
Thanks Badrish.

I am not creating threads. I am using task parallel library. Parallel.Foreach on an IEnumerable. Then I process each record which creates multiple entries and in turn processes each of them an so on. Think of doing graph search on a graph of unknown size.

Based on your explanation, I think TPL is creating more threads than the upper limit of FASTER.

I will do a work around and see if this error goes away.
