### ISSUE TITLE
At what level is locking enforced?

### ISSUE THREAD

**Issue by somecoder2019** [Microsoft/FASTER#97]
So, if I have a million records and there are threads constantly reading and writing all of them, at what level does FASTER locking work? Does it provide serializable consistency?

**Comment by badrishc** [comment]
FASTER uses a hybrid record log. For records in the mutable region, it operates similarly to any shared in-memory data structure, and user threads manage concurrent record access (they may take latches or use interlocked operations), and CPU cache coherence will provide consistency in shared memory.

For records in the immutable part of the log, FASTER atomically copies over the record to the tail (mutable region) for update by user threads (we use a compare-and-swap on the hash index entry for this).

If you are referring to recovery, FASTER provides a Checkpoint primitive. The guarantee is that all operations until a particular point (per thread) are persisted, and none after. Read more [here](https://github.com/Microsoft/FASTER#recovery-in-faster) and in the paper [here](https://www.microsoft.com/en-us/research/uploads/prod/2019/01/cpr-sigmod19.pdf).

**Comment by somecoder2019** [comment]
Thanks Badrish!
