### ISSUE TITLE
System.Exception: Can acquire only in REST phase!

### ISSUE THREAD

**Issue by somecoder2019** [Microsoft/FASTER#98]
I am doing some transactions using FASTER and kicked off a parallel thread to take snapshots. I am seeing the exception in the worker threads.

What could be the reason?

**Comment by badrishc** [comment]
Currently, new threads cannot register themselves with faster while a checkpoint is in progress, so that it can properly report progress to all active threads. Try to retry after checkpoint has been taken.

**Comment by somecoder2019** [comment]
Thanks Badrish!
